#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define SONICGLVL_ICON                          101
#define IDR_TOOLMENU                            103
#define IDD_LEFT_DIALOG                         107
#define IDD_BOTTOM_DIALOG                       111
#define IDD_TOP_DIALOG                          115
#define IDD_EDIT_BOOL_DIALOG                    117
#define IDD_EDIT_FLOAT_DIALOG                   119
#define IDD_EDIT_STRING_DIALOG                  121
#define IDD_EDIT_VECTOR_DIALOG                  123
#define IDD_EDIT_VECTOR_LIST_DIALOG             125
#define IDD_EDIT_ID_DIALOG                      127
#define IDD_EDIT_ID_LIST_DIALOG                 129
#define IDD_MULTISETPARAM_DIALOG                131
#define IDD_MATERIAL_EDITOR                     133
#define IDD_MATERIAL_EDITOR_PREVIEW             135
#define IDD_PHYSICS_EDITOR                      137
#define IDC_EDIT_FLOAT_VALUE                    40000
#define IDC_PALETTE_CATEGORY                    40000
#define IDE_BOTTOM_SELECTION_POS_X              40000
#define IDE_EDIT_VECTOR_X                       40000
#define IDE_MULTISETPARAM_X                     40000
#define IDL_COLLISION_LIST                      40000
#define IDR_MATERIAL_MODEL_MODE                 40000
#define IDS_EDIT_VECTOR_LIST_X                  40000
#define IDT_EDIT_ID_LIST_POINT                  40000
#define IDT_EDIT_ID_POINT                       40000
#define IMD_OPEN_LEVEL                          40000
#define IDB_DELETE_PHYSICS                      40001
#define IDB_EDIT_ID_SELECT_FROM_VIEWPORT        40001
#define IDC_EDIT_STRING_VALUE                   40001
#define IDE_BOTTOM_SELECTION_POS_Y              40001
#define IDE_EDIT_VECTOR_Y                       40001
#define IDE_MULTISETPARAM_Y                     40001
#define IDL_EDIT_ID_LIST_LIST                   40001
#define IDL_PALETTE_LIST                        40001
#define IDR_MATERIAL_MATERIAL_MODE              40001
#define IDS_EDIT_VECTOR_LIST_Y                  40001
#define IMD_SAVE_LEVEL_DATA                     40001
#define IDB_EDIT_ID_LIST_CREATE                 40002
#define IDB_IMPORT_PHYSICS                      40002
#define IDC_EDIT_ID_VALUE                       40002
#define IDE_BOTTOM_SELECTION_POS_Z              40002
#define IDE_EDIT_VECTOR_Z                       40002
#define IDE_MULTISETPARAM_Z                     40002
#define IDL_PROPERTIES_LIST                     40002
#define IDR_MATERIAL_TERRAIN_MODE               40002
#define IDS_EDIT_VECTOR_LIST_Z                  40002
#define IMD_SAVE_LEVEL_TERRAIN                  40002
#define IDB_EDIT_ID_GO_TO_TARGET                40003
#define IDB_EDIT_ID_LIST_DELETE                 40003
#define IDC_EDIT_BOOL_VALUE                     40003
#define IDE_BOTTOM_SELECTION_ROT_X              40003
#define IDE_EDIT_VECTOR_LIST_Y                  40003
#define IDG_STAGE_INFORMATION                   40003
#define IDS_EDIT_VECTOR_X                       40003
#define IDS_MULTISETPARAM_X                     40003
#define IDT_MATERIAL_MODEL_OPEN                 40003
#define IMD_CLOSE                               40003
#define IDB_EDIT_ID_LIST_MOVE_UP                40004
#define IDB_MATERIAL_LOAD_MODEL                 40004
#define IDE_BOTTOM_SELECTION_ROT_Y              40004
#define IDE_EDIT_VECTOR_LIST_Z                  40004
#define IDE_MULTISETPARAM_COUNT                 40004
#define IDG_PALETTE_GROUP                       40004
#define IDS_EDIT_VECTOR_Y                       40004
#define IMD_UNDO                                40004
#define IDB_EDIT_ID_LIST_MOVE_DOWN              40005
#define IDB_EDIT_VECTOR_LIST_CREATE             40005
#define IDB_MATERIAL_SAVE_MODEL                 40005
#define IDE_BOTTOM_SELECTION_ROT_Z              40005
#define IDG_PROPERTIES_GROUP                    40005
#define IDS_EDIT_VECTOR_Z                       40005
#define IDS_MULTISETPARAM_Y                     40005
#define IMD_REDO                                40005
#define IDB_EDIT_ID_LIST_GO_TO_TARGET           40006
#define IDB_EDIT_VECTOR_LIST_FOCUS              40006
#define IDC_EDIT_VECTOR_EDITING                 40006
#define IDE_MULTISETPARAM_SPACING               40006
#define IDG_HELP_GROUP                          40006
#define IDL_MATERIAL_MATERIAL_LIST              40006
#define IDS_BOTTOM_SELECTION_POS_X              40006
#define IMD_CUT                                 40006
#define IDB_EDIT_VECTOR_FOCUS                   40007
#define IDB_MATERIAL_NEW_MATERIAL               40007
#define IDC_EDIT_ID_LIST_VALUE                  40007
#define IDC_MULTISETPARAM_SNAP_PATH_EDGES       40007
#define IDE_EDIT_VECTOR_LIST_X                  40007
#define IDS_BOTTOM_SELECTION_POS_Y              40007
#define IDT_HELP_DESCRIPTION                    40007
#define IMD_COPY                                40007
#define IDB_EDIT_ID_LIST_ADD_FROM_VIEWPORT      40008
#define IDB_MATERIAL_DELETE_MATERIAL            40008
#define IDB_MULTISETPARAM_CREATE                40008
#define IDL_EDIT_VECTOR_LIST_LIST               40008
#define IDS_BOTTOM_SELECTION_POS_Z              40008
#define IMD_PASTE                               40008
#define IDC_EDIT_VECTOR_LIST_EDITING            40009
#define IDE_MATERIAL_NAME                       40009
#define IDS_BOTTOM_SELECTION_ROT_X              40009
#define IDS_MULTISETPARAM_COUNT                 40009
#define IMD_DELETE                              40009
#define IDB_EDIT_VECTOR_LIST_DELETE             40010
#define IDC_MATERIAL_SHADER                     40010
#define IDR_MULTISETPARAM_CLONE                 40010
#define IDS_BOTTOM_SELECTION_ROT_Y              40010
#define IMD_SELECT_ALL                          40010
#define IDB_EDIT_VECTOR_LIST_MOVE_UP            40011
#define IDC_MATERIAL_MESH_SLOT                  40011
#define IDR_MULTISETPARAM_MSP                   40011
#define IDS_BOTTOM_SELECTION_ROT_Z              40011
#define IMD_CLEAN_TERRAIN                       40011
#define IDB_EDIT_VECTOR_LIST_MOVE_DOWN          40012
#define IDC_BOTTOM_CURRENT_OBJECT_SET           40012
#define IDC_MATERIAL_BACKFACE_CULLING           40012
#define IDR_MULTISETPARAM_MSP_ADD               40012
#define IMD_IMPORT_TERRAIN_FBX                  40012
#define IDB_BOTTOM_MANAGE_OBJECT_SETS           40013
#define IDB_MULTISETPARAM_CLEAR                 40013
#define IDC_MATERIAL_ADDITIVE                   40013
#define IMD_GENERATE_TERRAIN_GROUPS             40013
#define IDC_MATERIAL_UNKNOWN_FLAG               40014
#define IDC_MULTISETPARAM_SNAP_PATH_CENTERS     40014
#define IMD_RELOAD_TEMPLATES_DATABASE           40014
#define IDS_MATERIAL_TEXTURE_UNIT_LIST          40015
#define IDS_MULTISETPARAM_SPACING               40015
#define IMD_SAVE_TEMPLATES_DATABASE             40015
#define IDB_MULTISETPARAM_SPACING               40016
#define IDL_MATERIAL_TEXTURE_UNIT_LIST          40016
#define IMD_GAME_SHADERS                        40016
#define IDB_MATERIAL_NEW_TEXTURE_UNIT           40017
#define IMD_FRAMEBUFFER                         40017
#define IDB_MATERIAL_DELETE_TEXTURE_UNIT        40018
#define IMD_UV_ANIMATIONS                       40018
#define IDB_MATERIAL_CREATE_TEXTURE_UNITS       40019
#define IMD_SKYBOX                              40019
#define IDE_MATERIAL_TEXTURE_FILENAME           40020
#define IMD_SHOW_OBJECTS                        40020
#define IDE_MATERIAL_TEXTURE_UNIT               40021
#define IMD_SHOW_TERRAIN                        40021
#define IDC_MATERIAL_TEXTURE_UNIT_SLOT          40022
#define IMD_SHOW_COLLISION                      40022
#define IDB_MATERIAL_TEXTURE_UNIT_RESET         40023
#define IMD_SHOW_PATHS                          40023
#define IDC_MATERIAL_DEFAULTS                   40024
#define IMD_SHOW_GHOST                          40024
#define IDB_MATERIAL_OPEN_TEXTURE_FILENAME      40025
#define IMD_WORLD_TRANSFORM                     40025
#define IDB_MATERIAL_DEFAULTS                   40026
#define IMD_SHOW_TERRAIN_AUTODRAW               40026
#define IDE_MATERIAL_PARAMETER_1_N              40027
#define IMD_PLACEMENT_SNAP                      40027
#define IDE_MATERIAL_PARAMETER_2_N              40028
#define IMD_OPEN_MATERIAL_EDITOR                40028
#define IDE_MATERIAL_PARAMETER_3_N              40029
#define IMD_OPEN_PHYSICS_EDITOR                 40029
#define IDE_MATERIAL_PARAMETER_4_N              40030
#define IMD_OPEN_LOST_WORLD_LEVEL               40030
#define IDE_MATERIAL_PARAMETER_5_N              40031
#define IDE_MATERIAL_PARAMETER_6_N              40032
#define IDE_MATERIAL_PARAMETER_7_N              40033
#define IDE_MATERIAL_PARAMETER_8_N              40034
#define IMD_EXPORT_SCENE_FBX                    40034
#define IDE_MATERIAL_PARAMETER_9_N              40035
#define IDE_MATERIAL_PARAMETER_10_N             40036
#define IDE_MATERIAL_PARAMETER_1_R              40037
#define IDE_MATERIAL_PARAMETER_1_G              40038
#define IDE_MATERIAL_PARAMETER_1_B              40039
#define IDE_MATERIAL_PARAMETER_1_A              40040
#define IDE_MATERIAL_PARAMETER_2_R              40041
#define IDE_MATERIAL_PARAMETER_2_G              40042
#define IDE_MATERIAL_PARAMETER_2_B              40043
#define IDE_MATERIAL_PARAMETER_2_A              40044
#define IDE_MATERIAL_PARAMETER_3_A              40045
#define IDE_MATERIAL_PARAMETER_4_A              40046
#define IDE_MATERIAL_PARAMETER_5_A              40047
#define IDE_MATERIAL_PARAMETER_6_A              40048
#define IDE_MATERIAL_PARAMETER_7_A              40049
#define IDE_MATERIAL_PARAMETER_8_A              40050
#define IDE_MATERIAL_PARAMETER_9_A              40051
#define IDE_MATERIAL_PARAMETER_10_A             40052
#define IDE_MATERIAL_PARAMETER_10_B             40053
#define IDE_MATERIAL_PARAMETER_10_G             40054
#define IDE_MATERIAL_PARAMETER_10_R             40055
#define IDE_MATERIAL_PARAMETER_3_B              40056
#define IDE_MATERIAL_PARAMETER_4_B              40057
#define IDE_MATERIAL_PARAMETER_5_B              40058
#define IDE_MATERIAL_PARAMETER_6_B              40059
#define IDE_MATERIAL_PARAMETER_7_B              40060
#define IDE_MATERIAL_PARAMETER_8_B              40061
#define IDE_MATERIAL_PARAMETER_9_B              40062
#define IDE_MATERIAL_PARAMETER_3_G              40063
#define IDE_MATERIAL_PARAMETER_4_G              40064
#define IDE_MATERIAL_PARAMETER_5_G              40065
#define IDE_MATERIAL_PARAMETER_6_G              40066
#define IDE_MATERIAL_PARAMETER_7_G              40067
#define IDE_MATERIAL_PARAMETER_8_G              40068
#define IDE_MATERIAL_PARAMETER_9_G              40069
#define IDE_MATERIAL_PARAMETER_3_R              40070
#define IDE_MATERIAL_PARAMETER_4_R              40071
#define IDE_MATERIAL_PARAMETER_5_R              40072
#define IDE_MATERIAL_PARAMETER_6_R              40073
#define IDE_MATERIAL_PARAMETER_7_R              40074
#define IDE_MATERIAL_PARAMETER_8_R              40075
#define IDE_MATERIAL_PARAMETER_9_R              40076
#define IDG_MATERIAL_MATERIAL_LIST              40077
#define IDG_MATERIAL_PARAMETERS                 40078
#define IDT_MATERIAL_PARAMETER_NAME             40079
#define IDT_MATERIAL_PARAMETER_R                40080
#define IDT_MATERIAL_PARAMETER_A                40081
#define IDT_MATERIAL_PARAMETER_B                40082
#define IDT_MATERIAL_PARAMETER_G                40083
#define IDT_MATERIAL_TEXTURE_UNIT_SLOT          40084
#define IDT_MATERIAL_TEXTURE_UNIT_NAME          40085
#define IDT_MATERIAL_TEXTURE_FILENAME           40086
#define IDT_MATERIAL_NAME                       40087
#define IDT_MATERIAL_SHADER                     40088
#define IDT_MATERIAL_MESH_SLOT                  40089
#define IDT_MATERIAL_TEXTURE_UNITS              40090
#define IDB_MATERIAL_LOAD_SKELETON              40091
#define IDB_MATERIAL_LOAD_ANIMATION             40092
#define IDT_MATERIAL_ANIMATION_OPEN             40093
#define IDT_MATERIAL_SKELETON_OPEN              40094
#define IDC_BOTTOM_CURRENT_OBJECT_SET_VISIBLE   40095
#define IDB_MATERIAL_SAVE_MATERIAL				40096
