/* This file was generated by syncqt. */
#ifndef QT_QTWEBKIT_VERSION_H
#define QT_QTWEBKIT_VERSION_H

#define QTWEBKIT_VERSION_STR "5.5.0"

#define QTWEBKIT_VERSION 0x050500

#endif // QT_QTWEBKIT_VERSION_H
