//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   float4 g_GI0Scale;
//   float4 g_LightScatteringColor;
//   row_major float4x4 g_MtxView;
//   float4 g_PowerGlossLevel;
//   float4 g_ShadowMapParams;
//   sampler2D g_ShadowMapSampler;
//   float4 g_Specular;
//   sampler2D g_VerticalShadowMapSampler;
//   float4 g_aLightField[6];
//   float4 mrgEyeLight_Attribute;
//   float4 mrgEyeLight_Diffuse;
//   float4 mrgEyeLight_Range;
//   float4 mrgEyeLight_Specular;
//   float4 mrgGlobalLight_Diffuse;
//   float4 mrgGlobalLight_Direction;
//   float4 mrgGlobalLight_Specular;
//   float4 mrgInShadowScale;
//   float4 mrgLocalLight0_Color;
//   float4 mrgLocalLight0_Position;
//   float4 mrgLocalLight0_Range;
//   float4 mrgLocalLight1_Color;
//   float4 mrgLocalLight1_Position;
//   float4 mrgLocalLight1_Range;
//   float4 mrgLocalLight2_Color;
//   float4 mrgLocalLight2_Position;
//   float4 mrgLocalLight2_Range;
//   float4 mrgLocalLight3_Color;
//   float4 mrgLocalLight3_Position;
//   float4 mrgLocalLight3_Range;
//   float4 mrgLuminanceRange;
//   float4 mrgTexcoordIndex[4];
//   sampler2D sampBlend;
//   sampler2D sampDif0;
//   sampler2D sampDif1;
//   sampler2D sampEnv;
//   sampler2D sampNrm;
//   sampler2D sampSpc0;
//   sampler2D sampSpc1;
//
//
// Registers:
//
//   Name                       Reg   Size
//   -------------------------- ----- ----
//   mrgGlobalLight_Direction   c10      1
//   g_Diffuse                  c16      1
//   g_Ambient                  c17      1
//   g_Specular                 c18      1
//   g_PowerGlossLevel          c20      1
//   g_EyePosition              c22      1
//   g_EyeDirection             c23      1
//   mrgTexcoordIndex           c26      2
//   mrgGlobalLight_Diffuse     c36      1
//   mrgGlobalLight_Specular    c37      1
//   mrgLocalLight0_Position    c38      1
//   mrgLocalLight0_Color       c39      1
//   mrgLocalLight0_Range       c40      1
//   mrgLocalLight1_Position    c42      1
//   mrgLocalLight1_Color       c43      1
//   mrgLocalLight1_Range       c44      1
//   mrgLocalLight2_Position    c46      1
//   mrgLocalLight2_Color       c47      1
//   mrgLocalLight2_Range       c48      1
//   mrgLocalLight3_Position    c50      1
//   mrgLocalLight3_Color       c51      1
//   mrgLocalLight3_Range       c52      1
//   mrgEyeLight_Diffuse        c58      1
//   mrgEyeLight_Specular       c59      1
//   mrgEyeLight_Range          c60      1
//   mrgEyeLight_Attribute      c61      1
//   mrgLuminanceRange          c63      1
//   mrgInShadowScale           c64      1
//   g_ShadowMapParams          c65      1
//   g_GI0Scale                 c70      1
//   g_LightScatteringColor     c75      1
//   g_aLightField              c77      6
//   g_ForceAlphaColor          c89      1
//   g_MtxView                  c90      3
//   sampDif0                   s0       1
//   sampDif1                   s1       1
//   sampSpc0                   s2       1
//   sampSpc1                   s3       1
//   sampNrm                    s4       1
//   sampBlend                  s5       1
//   sampEnv                    s6       1
//   g_VerticalShadowMapSampler s7       1
//   g_ShadowMapSampler         s13      1
//

    ps_3_0
    def c0, 500, 5, 1024, 4
    def c1, 2, -1, 0.5, -3
    def c2, 0.5, -0.5, 0, 0
    def c3, 0, 1, 2, 3
    dcl_texcoord v0
    dcl_texcoord1 v1
    dcl_texcoord2 v2.xyz
    dcl_texcoord3_pp v3
    dcl_texcoord4 v4
    dcl_texcoord6 v5
    dcl_texcoord5_pp v6.xyz
    dcl_texcoord7 v7.xyz
    dcl_texcoord8 v8.xyz
    dcl_color_pp v9
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s5
    dcl_2d s6
    dcl_2d s7
    dcl_2d s13
    add_pp r0.x, -c61.z, c61.y
    rcp_pp r0.x, r0.x
    add r0.yzw, -c22.xxyz, v2.xxyz
    dp3 r1.x, r0.yzww, r0.yzww
    rsq r1.x, r1.x
    mul_pp r0.yzw, r0, r1.x
    rcp r1.x, r1.x
    add r1.x, r1.x, -c60.z
    dp3_pp r1.y, r0.yzww, c23
    add_pp r1.y, r1.y, -c61.z
    mul_sat_pp r0.x, r0.x, r1.y
    mad_pp r1.y, r0.x, -c1.x, -c1.w
    mul_pp r0.x, r0.x, r0.x
    mul_pp r0.x, r0.x, r1.y
    pow_sat_pp r1.y, r0.x, c61.w
    mov r2.xy, c3
    add r0.x, r2.y, -c61.x
    cmp_pp r0.x, r0.x, c3.y, r1.y
    add r1.y, -c60.z, c60.w
    rcp r1.y, r1.y
    mul_sat r1.x, r1.y, r1.x
    add_pp r1.x, -r1.x, c3.y
    cmp_pp r1.x, -c61.x, r2.y, r1.x
    mul_pp r0.x, r0.x, r1.x
    max r1.x, v4.z, c3.x
    add r1.y, r1.x, -v4.w
    cmp r1.z, r1.y, c3.x, r1.x
    mov r1.xyw, v4
    texldp_pp r1, r1, s13
    max r1.y, v5.z, c3.x
    add r1.z, r1.y, -v5.w
    cmp r3.z, r1.z, c3.x, r1.y
    mov r3.xyw, v5
    texldp_pp r3, r3, s7
    min_pp r2.y, r3.x, r1.x
    lrp_pp r1.x, v6.z, c3.y, r3.x
    lrp_pp r1.y, v6.z, c3.y, r2.y
    rcp r1.z, v4.w
    mul r1.zw, r1.z, v4.xyxy
    mad r1.zw, r1, c1.x, c1.y
    abs_sat r1.zw, r1
    add_sat r1.zw, r1, -c65.x
    mul r1.zw, r1, c65.y
    max r2.y, r1.z, r1.w
    lrp_pp r3.x, r2.y, c3.y, r1.y
    lrp_pp r3.y, r2.y, c3.y, r1.x
    mul_pp r1.x, r3.x, c77.w
    add r1.y, -c48.z, c48.w
    rcp r1.y, r1.y
    add r2.yzw, -c46.xxyz, v2.xxyz
    dp3 r1.z, r2.yzww, r2.yzww
    rsq r1.z, r1.z
    rcp r1.w, r1.z
    mul_pp r2.yzw, r1.z, r2
    add r1.z, r1.w, -c48.z
    mul_sat r1.y, r1.y, r1.z
    add r1.z, -c40.z, c40.w
    rcp r1.z, r1.z
    add r3.xzw, -c38.xyyz, v2.xyyz
    dp3 r1.w, r3.xzww, r3.xzww
    rsq r1.w, r1.w
    rcp r4.x, r1.w
    mul_pp r3.xzw, r1.w, r3
    add r1.w, r4.x, -c40.z
    mul_sat r1.z, r1.z, r1.w
    add r1.w, -c44.z, c44.w
    rcp r1.w, r1.w
    add r4.xyz, -c42, v2
    dp3 r4.w, r4, r4
    rsq r4.w, r4.w
    rcp r5.x, r4.w
    mul_pp r4.xyz, r4.w, r4
    add r4.w, r5.x, -c44.z
    mul_sat r1.w, r1.w, r4.w
    add_pp r1.yzw, -r1, c3.y
    frc r5.xy, c27
    cmp r5.zw, -r5.xyxy, c3.x, c3.y
    add r5.xy, -r5, c27
    cmp r5.zw, c27.xyxy, r2.x, r5
    add r5.xy, r5.zwzw, r5
    add r6, r5.y, -c3
    add r5, r5.x, -c3
    cmp r7.xy, -r6_abs.x, v0, c3.x
    cmp r6.xy, -r6_abs.y, v0.zwzw, r7
    cmp r6.xy, -r6_abs.z, v1, r6
    cmp r6.xy, -r6_abs.w, v1.zwzw, r6
    texld_pp r6, r6, s5
    frc r7, c26
    cmp r8, -r7, c3.x, c3.y
    add r7, -r7, c26
    cmp r8, c26, r2.x, r8
    add r7, r7, r8
    add r8, r7.z, -c3
    cmp r6.yz, -r8_abs.x, v0.xxyw, c3.x
    cmp r6.yz, -r8_abs.y, v0.xzww, r6
    cmp r6.yz, -r8_abs.z, v1.xxyw, r6
    cmp r6.yz, -r8_abs.w, v1.xzww, r6
    texld_pp r8, r6.yzzw, s2
    add r9, r7.w, -c3
    cmp r6.yz, -r9_abs.x, v0.xxyw, c3.x
    cmp r6.yz, -r9_abs.y, v0.xzww, r6
    cmp r6.yz, -r9_abs.z, v1.xxyw, r6
    cmp r6.yz, -r9_abs.w, v1.xzww, r6
    texld_pp r9, r6.yzzw, s3
    lrp_pp r10, r6.x, r9, r8
    mul_pp r6.yz, r10.w, c20
    mul_pp r6.yz, r6, c0.xxyw
    mul_pp r8.xyz, r6.z, c43
    max_pp r2.x, r6.y, c3.y
    min r4.w, r2.x, c0.z
    cmp r6.yw, -r5_abs.x, v0.xxzy, c3.x
    cmp r5.xy, -r5_abs.y, v0.zwzw, r6.ywzw
    cmp r5.xy, -r5_abs.z, v1, r5
    cmp r5.xy, -r5_abs.w, v1.zwzw, r5
    texld_pp r5, r5, s4
    mul_pp r5.x, r5.w, r5.x
    mad_pp r5.xy, r5, c1.x, c1.y
    nrm_pp r9.xyz, v8
    mul_pp r9.xyz, r5.y, r9
    nrm_pp r11.xyz, v7
    mad_pp r9.xyz, r5.x, r11, r9
    dp2add_pp r2.x, r5, -r5, c3.y
    rsq_pp r2.x, r2.x
    rcp_pp r2.x, r2.x
    nrm_pp r5.xyz, v3
    mad_pp r5.xyz, r2.x, r5, r9
    add_pp r9.xyz, c22, -v2
    dp3_pp r2.x, r9, r9
    rsq_pp r2.x, r2.x
    mad_pp r11.xyz, r9, r2.x, -r4
    dp3_pp r4.x, r5, -r4
    nrm_pp r12.xyz, r11
    dp3_sat_pp r4.y, r12, r5
    pow r5.w, r4.y, r4.w
    mul_pp r8.xyz, r5.w, r8
    mul_pp r8.xyz, r1.w, r8
    mul_pp r11.xyz, r6.z, c39
    mad_pp r12.xyz, r9, r2.x, -r3.xzww
    dp3_pp r3.x, r5, -r3.xzww
    nrm_pp r13.xyz, r12
    dp3_sat_pp r3.z, r13, r5
    pow r5.w, r3.z, r4.w
    mul_pp r11.xyz, r5.w, r11
    mad_pp r8.xyz, r1.z, r11, r8
    mul_pp r11.xyz, r6.z, c47
    mad_pp r12.xyz, r9, r2.x, -r2.yzww
    dp3_pp r2.y, r5, -r2.yzww
    nrm_pp r13.xyz, r12
    dp3_sat_pp r2.z, r13, r5
    pow r3.z, r2.z, r4.w
    mul_pp r11.xyz, r3.z, r11
    mad_pp r8.xyz, r1.y, r11, r8
    add r2.z, -c52.z, c52.w
    rcp r2.z, r2.z
    add r11.xyz, -c50, v2
    dp3 r2.w, r11, r11
    rsq r2.w, r2.w
    rcp r3.z, r2.w
    mul_pp r11.xyz, r2.w, r11
    add r2.w, r3.z, -c52.z
    mul_sat r2.z, r2.z, r2.w
    add_pp r2.z, -r2.z, c3.y
    mul_pp r12.xyz, r6.z, c51
    mad_pp r13.xyz, r9, r2.x, -r11
    dp3_pp r2.w, r5, -r11
    nrm_pp r11.xyz, r13
    dp3_sat_pp r3.z, r11, r5
    pow r5.w, r3.z, r4.w
    mul_pp r11.xyz, r5.w, r12
    mad_pp r8.xyz, r2.z, r11, r8
    mul_pp r11.xyz, r6.z, c37
    mad_pp r12.xyz, r9, r2.x, -c10
    mad_pp r9.xyz, r9, r2.x, -r0.yzww
    dp3_pp r0.y, r5, -r0.yzww
    nrm_pp r13.xyz, r9
    dp3_sat_pp r0.z, r13, r5
    pow r2.x, r0.z, r4.w
    nrm_pp r9.xyz, r12
    dp3_sat_pp r0.z, r9, r5
    pow r3.z, r0.z, r4.w
    mul_pp r4.yzw, r3.z, r11.xxyz
    mad_pp r4.yzw, r4, r1.x, r8.xxyz
    mul_pp r8.xyz, c59.w, c59
    mul_pp r6.yzw, r6.z, r8.xxyz
    mul_pp r6.yzw, r2.x, r6
    mad_pp r4.yzw, r0.x, r6, r4
    mul r0.z, c64.z, c64.x
    mov r8.xz, c64
    mad r0.w, r8.x, -r8.z, r8.z
    mad_pp r0.z, r1.x, r0.w, r0.z
    mul r8, r5.y, c91
    mad r8, r5.x, c90, r8
    mad r8, r5.z, c92, r8
    dp4 r0.w, r8, r8
    rsq r0.w, r0.w
    mul r3.zw, r0.w, r8.xyxy
    mad_pp r3.zw, r3, c2.xyxy, c2.x
    texld_pp r8, r3.zwzw, s6
    mul r6.yzw, r8.xxyz, c63.x
    mad_pp r6.yzw, r6, r8.w, r8.xxyz
    mul_pp r6.yzw, r10.w, r6
    mul_pp r6.yzw, r0.z, r6
    mad_pp r4.yzw, r4, c18.xxyz, r6
    mul_pp r4.yzw, r10.xxyz, r4
    mul_pp r4.yzw, r4, v3.w
    mul_pp r6.yzw, r4.x, c43.xxyz
    cmp_pp r6.yzw, r4.x, r6, c3.x
    mul_pp r6.yzw, r1.w, r6
    mul_pp r8.xyz, r3.x, c39
    cmp_pp r3.xzw, r3.x, r8.xyyz, c3.x
    mad_pp r3.xzw, r1.z, r3, r6.yyzw
    mul_pp r6.yzw, r2.y, c47.xxyz
    cmp_pp r6.yzw, r2.y, r6, c3.x
    mad_pp r1.yzw, r1.y, r6, r3.xxzw
    mul_pp r3.xzw, r2.w, c51.xyyz
    cmp_pp r2.xyw, r2.w, r3.xzzw, c3.x
    mad_pp r1.yzw, r2.z, r2.xxyw, r1
    dp3_pp r0.z, r5, -c10
    mul r2.xyz, r0.z, c36
    mul_pp r2.xyz, r1.x, r2
    cmp_pp r2.xyz, r0.z, r2, c3.x
    add_pp r1.xyz, r1.yzww, r2
    mul_pp r2.xyz, c58.w, c58
    mul_pp r2.xyz, r0.y, r2
    cmp_pp r0.yzw, r0.y, r2.xxyz, c3.x
    mad_pp r0.xyz, r0.x, r0.yzww, r1
    mad_pp r1.xyz, r5, c1.z, c1.z
    mul_pp r2.xyz, r5, r5
    mov r5.xyz, c79
    add r3.xzw, -r5.xyyz, c80.xyyz
    mad r3.xzw, r1.y, r3, c79.xyyz
    mul r3.xzw, r2.y, r3
    mov r5.xyz, c77
    add r5.xyz, -r5, c78
    mad r1.xyw, r1.x, r5.xyzz, c77.xyzz
    mad_pp r1.xyw, r2.x, r1, r3.xzzw
    mov r5.xyz, c81
    add r2.xyw, -r5.xyzz, c82.xyzz
    mad r2.xyw, r1.z, r2, c81.xyzz
    mad_pp r1.xyz, r2.z, r2.xyww, r1.xyww
    mul_pp r2.xyz, r1, c17
    mul r2.xyz, r2, c70.w
    mad r1.xyz, r1, c17, -r2
    mad_pp r1.xyz, r3.y, r1, r2
    add_pp r0.xyz, r0, r1
    mul_pp r0.xyz, r0, c16
    add r1, r7.x, -c3
    add r2, r7.y, -c3
    cmp r3.xy, -r1_abs.x, v0, c3.x
    cmp r1.xy, -r1_abs.y, v0.zwzw, r3
    cmp r1.xy, -r1_abs.z, v1, r1
    cmp r1.xy, -r1_abs.w, v1.zwzw, r1
    texld_pp r1, r1, s0
    cmp r3.xy, -r2_abs.x, v0, c3.x
    cmp r2.xy, -r2_abs.y, v0.zwzw, r3
    cmp r2.xy, -r2_abs.z, v1, r2
    cmp r2.xy, -r2_abs.w, v1.zwzw, r2
    texld_pp r2, r2, s1
    lrp_pp r3, r6.x, r2, r1
    mad_pp r0.xyz, r0, r3, r4.yzww
    mul_pp r0.w, r3.w, c16.w
    mul_pp r0, r0, v9
    mul_pp r0, r0, c89
    min_pp r1, r0, c0.w
    mul_pp r0.xyz, c75, v6.y
    mad_pp oC0.xyz, r1, v6.x, r0
    mov_pp oC0.w, r1.w

// approximately 300 instruction slots used (9 texture, 291 arithmetic)
