//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   float4 g_GI0Scale;
//   float4 g_GI1Scale;
//   sampler2D g_GISampler;
//   float4 g_LightScatteringColor;
//   float4 g_PowerGlossLevel;
//   float4 g_ShadowMapParams;
//   sampler2D g_ShadowMapSampler;
//   float4 g_Specular;
//   sampler2D g_VerticalShadowMapSampler;
//   float4 mrgEyeLight_Attribute;
//   float4 mrgEyeLight_Diffuse;
//   float4 mrgEyeLight_Range;
//   float4 mrgEyeLight_Specular;
//   float4 mrgGlobalLight_Diffuse;
//   float4 mrgGlobalLight_Direction;
//   float4 mrgGlobalLight_Specular;
//   float4 mrgLocalLight0_Color;
//   float4 mrgLocalLight0_Position;
//   float4 mrgLocalLight0_Range;
//   float4 mrgLocalLight1_Color;
//   float4 mrgLocalLight1_Position;
//   float4 mrgLocalLight1_Range;
//   float4 mrgLocalLight2_Color;
//   float4 mrgLocalLight2_Position;
//   float4 mrgLocalLight2_Range;
//   float4 mrgLocalLight3_Color;
//   float4 mrgLocalLight3_Position;
//   float4 mrgLocalLight3_Range;
//   float4 mrgTexcoordIndex[4];
//   sampler2D sampDif0;
//   sampler2D sampDif1;
//   sampler2D sampPower0;
//   sampler2D sampPower1;
//
//
// Registers:
//
//   Name                       Reg   Size
//   -------------------------- ----- ----
//   mrgGlobalLight_Direction   c10      1
//   g_Diffuse                  c16      1
//   g_Ambient                  c17      1
//   g_Specular                 c18      1
//   g_PowerGlossLevel          c20      1
//   g_EyePosition              c22      1
//   g_EyeDirection             c23      1
//   mrgTexcoordIndex           c26      1
//   mrgGlobalLight_Diffuse     c36      1
//   mrgGlobalLight_Specular    c37      1
//   mrgLocalLight0_Position    c38      1
//   mrgLocalLight0_Color       c39      1
//   mrgLocalLight0_Range       c40      1
//   mrgLocalLight1_Position    c42      1
//   mrgLocalLight1_Color       c43      1
//   mrgLocalLight1_Range       c44      1
//   mrgLocalLight2_Position    c46      1
//   mrgLocalLight2_Color       c47      1
//   mrgLocalLight2_Range       c48      1
//   mrgLocalLight3_Position    c50      1
//   mrgLocalLight3_Color       c51      1
//   mrgLocalLight3_Range       c52      1
//   mrgEyeLight_Diffuse        c58      1
//   mrgEyeLight_Specular       c59      1
//   mrgEyeLight_Range          c60      1
//   mrgEyeLight_Attribute      c61      1
//   g_ShadowMapParams          c65      1
//   g_GI0Scale                 c70      1
//   g_GI1Scale                 c71      1
//   g_LightScatteringColor     c75      1
//   g_ForceAlphaColor          c89      1
//   sampDif0                   s0       1
//   sampDif1                   s1       1
//   sampPower0                 s2       1
//   sampPower1                 s3       1
//   g_VerticalShadowMapSampler s7       1
//   g_GISampler                s10      1
//   g_ShadowMapSampler         s13      1
//

    ps_3_0
    def c0, 0.298900008, 0.586600006, 0.114399999, 1024
    def c1, 2, -1, -2, 3
    def c2, 500, 5, 4, 0
    def c3, 0, 1, 2, 3
    dcl_texcoord v0
    dcl_texcoord1 v1
    dcl_texcoord2 v2.xyz
    dcl_texcoord3_pp v3
    dcl_texcoord4 v4
    dcl_texcoord6 v5
    dcl_texcoord5_pp v6.xyz
    dcl_color_pp v7.xw
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s7
    dcl_2d s10
    dcl_2d s13
    rcp r0.x, v4.w
    mul r0.xy, r0.x, v4
    mad r0.xy, r0, c1.x, c1.y
    abs_sat r0.xy, r0
    add_sat r0.xy, r0, -c65.x
    mul r0.xy, r0, c65.y
    max r1.x, r0.x, r0.y
    max r0.x, v5.z, c3.x
    add r0.y, r0.x, -v5.w
    cmp r0.z, r0.y, c3.x, r0.x
    mov r0.xyw, v5
    texldp_pp r0, r0, s7
    lrp_pp r1.y, v6.z, c3.y, r0.x
    lrp_pp r0.y, r1.x, c3.y, r1.y
    texld_pp r2, v0.zwzw, s10
    mul_pp r1.yzw, r2.xxyz, r2.xxyz
    dp3_pp r0.z, r1.yzww, c0
    mad_pp r1.yzw, r2.xxyz, r2.xxyz, -r0.z
    mad_sat_pp r1.yzw, r1, c71.w, r0.z
    mul_pp r1.yzw, r1, c70.xxyz
    mul_pp r2.xyz, r1.yzww, c17
    mul r2.xyz, r2, c70.w
    mad r1.yzw, r1, c17.xxyz, -r2.xxyz
    mad_pp r0.yzw, r0.y, r1, r2.xxyz
    add r1.y, -c48.z, c48.w
    rcp r1.y, r1.y
    add r2.xyz, -c46, v2
    dp3 r1.z, r2, r2
    rsq r1.z, r1.z
    rcp r1.w, r1.z
    mul_pp r2.xyz, r1.z, r2
    add r1.z, r1.w, -c48.z
    mul_sat r1.y, r1.y, r1.z
    add r1.z, -c40.z, c40.w
    rcp r1.z, r1.z
    add r3.xyz, -c38, v2
    dp3 r1.w, r3, r3
    rsq r1.w, r1.w
    rcp r3.w, r1.w
    mul_pp r3.xyz, r1.w, r3
    add r1.w, r3.w, -c40.z
    mul_sat r1.z, r1.z, r1.w
    add r1.w, -c44.z, c44.w
    rcp r1.w, r1.w
    add r4.xyz, -c42, v2
    dp3 r3.w, r4, r4
    rsq r3.w, r3.w
    rcp r4.w, r3.w
    mul_pp r4.xyz, r3.w, r4
    add r3.w, r4.w, -c44.z
    mul_sat r1.w, r1.w, r3.w
    add_pp r1.yzw, -r1, c3.y
    nrm_pp r5.xyz, v3
    dp3_pp r3.w, r5, -r4
    mul_pp r6.xyz, r3.w, c43
    cmp_pp r6.xyz, r3.w, r6, c3.x
    mul_pp r6.xyz, r1.w, r6
    dp3_pp r3.w, r5, -r3
    mul_pp r7.xyz, r3.w, c39
    cmp_pp r7.xyz, r3.w, r7, c3.x
    mad_pp r6.xyz, r1.z, r7, r6
    dp3_pp r3.w, r5, -r2
    mul_pp r7.xyz, r3.w, c47
    cmp_pp r7.xyz, r3.w, r7, c3.x
    mad_pp r6.xyz, r1.y, r7, r6
    add r3.w, -c52.z, c52.w
    rcp r3.w, r3.w
    add r7.xyz, -c50, v2
    dp3 r4.w, r7, r7
    rsq r4.w, r4.w
    rcp r5.w, r4.w
    mul_pp r7.xyz, r4.w, r7
    add r4.w, r5.w, -c52.z
    mul_sat r3.w, r3.w, r4.w
    add_pp r3.w, -r3.w, c3.y
    dp3_pp r4.w, r5, -r7
    mul_pp r8.xyz, r4.w, c51
    cmp_pp r8.xyz, r4.w, r8, c3.x
    mad_pp r6.xyz, r3.w, r8, r6
    max r4.w, v4.z, c3.x
    add r5.w, r4.w, -v4.w
    cmp r8.z, r5.w, c3.x, r4.w
    mov r8.xyw, v4
    texldp_pp r8, r8, s13
    min_pp r4.w, r0.x, r8.x
    lrp_pp r0.x, v6.z, c3.y, r4.w
    lrp_pp r4.w, r1.x, c3.y, r0.x
    mul_pp r0.x, r2.w, r4.w
    dp3_pp r1.x, r5, -c10
    mul r8.xyz, r1.x, c36
    mul_pp r8.xyz, r0.x, r8
    cmp_pp r8.xyz, r1.x, r8, c3.x
    add_pp r6.xyz, r6, r8
    add_pp r1.x, -c61.z, c61.y
    rcp_pp r1.x, r1.x
    add r8.xyz, -c22, v2
    dp3 r2.w, r8, r8
    rsq r2.w, r2.w
    mul_pp r8.xyz, r2.w, r8
    rcp r2.w, r2.w
    add r2.w, r2.w, -c60.z
    dp3_pp r4.w, r8, c23
    add_pp r4.w, r4.w, -c61.z
    mul_sat_pp r1.x, r1.x, r4.w
    mad_pp r4.w, r1.x, c1.z, c1.w
    mul_pp r1.x, r1.x, r1.x
    mul_pp r1.x, r1.x, r4.w
    pow_sat_pp r4.w, r1.x, c61.w
    mov r9.xy, c3
    add r1.x, r9.y, -c61.x
    cmp_pp r1.x, r1.x, c3.y, r4.w
    add r4.w, -c60.z, c60.w
    rcp r4.w, r4.w
    mul_sat r2.w, r2.w, r4.w
    add_pp r2.w, -r2.w, c3.y
    cmp_pp r2.w, -c61.x, r9.y, r2.w
    mul_pp r1.x, r1.x, r2.w
    mul_pp r9.yzw, c58.w, c58.xxyz
    dp3_pp r2.w, r5, -r8
    mul_pp r9.yzw, r2.w, r9
    cmp_pp r9.yzw, r2.w, r9, c3.x
    mad_pp r6.xyz, r1.x, r9.yzww, r6
    add_pp r0.yzw, r0, r6.xxyz
    mul_pp r0.yzw, r0, c16.xxyz
    frc r6, c26
    cmp r10, -r6, c3.x, c3.y
    add r6, -r6, c26
    cmp r9, c26, r9.x, r10
    add r6, r6, r9
    add r9, r6.z, -c3
    cmp r10.xy, -r9_abs.x, v0, c3.x
    cmp r9.xy, -r9_abs.y, v0.zwzw, r10
    cmp r9.xy, -r9_abs.z, v1, r9
    cmp r9.xy, -r9_abs.w, v1.zwzw, r9
    texld_pp r9, r9, s2
    add r10, r6.w, -c3
    cmp r6.zw, -r10_abs.x, v0.xyxy, c3.x
    cmp r6.zw, -r10_abs.y, v0, r6
    cmp r6.zw, -r10_abs.z, v1.xyxy, r6
    cmp r6.zw, -r10_abs.w, v1, r6
    texld_pp r10, r6.zwzw, s3
    lrp_pp r2.w, v7.x, r10.x, r9.x
    mul_pp r6.zw, r2.w, c20.xyyz
    mul_pp r6.zw, r6, c2.xyxy
    mul_pp r9.xyz, r6.w, c43
    max_pp r2.w, r6.z, c3.y
    min r4.w, r2.w, c0.w
    add_pp r10.xyz, c22, -v2
    dp3_pp r2.w, r10, r10
    rsq_pp r2.w, r2.w
    mad_pp r4.xyz, r10, r2.w, -r4
    nrm_pp r11.xyz, r4
    dp3_sat_pp r4.x, r11, r5
    pow r5.w, r4.x, r4.w
    mul_pp r4.xyz, r5.w, r9
    mul_pp r4.xyz, r1.w, r4
    mul_pp r9.xyz, r6.w, c39
    mad_pp r3.xyz, r10, r2.w, -r3
    nrm_pp r11.xyz, r3
    dp3_sat_pp r1.w, r11, r5
    pow r3.x, r1.w, r4.w
    mul_pp r3.xyz, r3.x, r9
    mad_pp r3.xyz, r1.z, r3, r4
    mul_pp r4.xyz, r6.w, c47
    mad_pp r2.xyz, r10, r2.w, -r2
    nrm_pp r9.xyz, r2
    dp3_sat_pp r1.z, r9, r5
    pow r2.x, r1.z, r4.w
    mul_pp r2.xyz, r2.x, r4
    mad_pp r1.yzw, r1.y, r2.xxyz, r3.xxyz
    mul_pp r2.xyz, r6.w, c51
    mad_pp r3.xyz, r10, r2.w, -r7
    nrm_pp r4.xyz, r3
    dp3_sat_pp r3.x, r4, r5
    pow r5.w, r3.x, r4.w
    mul_pp r2.xyz, r2, r5.w
    mad_pp r1.yzw, r3.w, r2.xxyz, r1
    mul_pp r2.xyz, r6.w, c37
    mad_pp r3.xyz, r10, r2.w, -c10
    mad_pp r4.xyz, r10, r2.w, -r8
    nrm_pp r7.xyz, r4
    dp3_sat_pp r2.w, r7, r5
    pow r3.w, r2.w, r4.w
    nrm_pp r4.xyz, r3
    dp3_sat_pp r2.w, r4, r5
    pow r3.x, r2.w, r4.w
    mul_pp r2.xyz, r2, r3.x
    mad_pp r1.yzw, r2.xxyz, r0.x, r1
    mul_pp r2.xyz, c59.w, c59
    mul_pp r2.xyz, r6.w, r2
    mul_pp r2.xyz, r3.w, r2
    mad_pp r1.xyz, r1.x, r2, r1.yzww
    mul_pp r1.xyz, r1, c18
    mul_pp r1.xyz, r1, v3.w
    add r2, r6.x, -c3
    add r3, r6.y, -c3
    cmp r4.xy, -r2_abs.x, v0, c3.x
    cmp r2.xy, -r2_abs.y, v0.zwzw, r4
    cmp r2.xy, -r2_abs.z, v1, r2
    cmp r2.xy, -r2_abs.w, v1.zwzw, r2
    texld_pp r2, r2, s0
    cmp r4.xy, -r3_abs.x, v0, c3.x
    cmp r3.xy, -r3_abs.y, v0.zwzw, r4
    cmp r3.xy, -r3_abs.z, v1, r3
    cmp r3.xy, -r3_abs.w, v1.zwzw, r3
    texld_pp r3, r3, s1
    lrp_pp r4, v7.x, r3, r2
    mad_pp r0.xyz, r0.yzww, r4, r1
    mul_pp r1.x, r4.w, c16.w
    mul_pp r0.w, r1.x, v7.w
    mul_pp r0, r0, c89
    min_pp r1, r0, c2.z
    mul_pp r0.xyz, c75, v6.y
    mad_pp oC0.xyz, r1, v6.x, r0
    mov_pp oC0.w, r1.w

// approximately 243 instruction slots used (7 texture, 236 arithmetic)
