//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float3 g_BloomStar_Param1;
//   sampler2D sampDif0;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   g_BloomStar_Param1 c151     1
//   sampDif0           s0       1
//

    ps_3_0
    def c0, 0, 1, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    texld r0, v0, s0
    add r0.xyz, r0, -c151.x
    max r1.xyz, r0, c0.x
    add r0.xyz, r1, c151.y
    rcp r2.x, r0.x
    rcp r2.y, r0.y
    rcp r2.z, r0.z
    mul_pp oC0.xyz, r1, r2
    mov_pp oC0.w, c0.y

// approximately 9 instruction slots used (1 texture, 8 arithmetic)
