//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   float4 g_GI0Scale;
//   float4 g_GI1Scale;
//   sampler2D g_GISampler;
//   float4 g_LightScatteringColor;
//   float4 g_PowerGlossLevel;
//   float4 g_ShadowMapParams;
//   sampler2D g_ShadowMapSampler;
//   float4 g_Specular;
//   float4 g_TransColorMask;
//   sampler2D g_VerticalShadowMapSampler;
//   float4 mrgEyeLight_Attribute;
//   float4 mrgEyeLight_Diffuse;
//   float4 mrgEyeLight_Range;
//   float4 mrgEyeLight_Specular;
//   float4 mrgGlobalLight_Diffuse;
//   float4 mrgGlobalLight_Direction;
//   float4 mrgGlobalLight_Specular;
//   sampler2D sampDif;
//   sampler2D sampNrm;
//   sampler2D sampSpec;
//   sampler2D sampTrans;
//
//
// Registers:
//
//   Name                       Reg   Size
//   -------------------------- ----- ----
//   mrgGlobalLight_Direction   c10      1
//   g_Diffuse                  c16      1
//   g_Ambient                  c17      1
//   g_Specular                 c18      1
//   g_PowerGlossLevel          c20      1
//   g_EyePosition              c22      1
//   g_EyeDirection             c23      1
//   mrgGlobalLight_Diffuse     c36      1
//   mrgGlobalLight_Specular    c37      1
//   mrgEyeLight_Diffuse        c58      1
//   mrgEyeLight_Specular       c59      1
//   mrgEyeLight_Range          c60      1
//   mrgEyeLight_Attribute      c61      1
//   g_ShadowMapParams          c65      1
//   g_GI0Scale                 c70      1
//   g_GI1Scale                 c71      1
//   g_LightScatteringColor     c75      1
//   g_ForceAlphaColor          c89      1
//   g_TransColorMask           c150     1
//   sampDif                    s0       1
//   sampSpec                   s1       1
//   sampNrm                    s3       1
//   sampTrans                  s4       1
//   g_VerticalShadowMapSampler s7       1
//   g_GISampler                s10      1
//   g_ShadowMapSampler         s13      1
//

    ps_3_0
    def c0, 0.298900008, 0.586600006, 0.114399999, 1024
    def c1, 2, -1, 1, 0
    def c2, 500, 5, 0.5, 4
    def c3, -2, 3, 0.800000012, 0.0500000007
    dcl_texcoord v0
    dcl_texcoord2 v1.xyz
    dcl_texcoord3_pp v2.xyz
    dcl_texcoord4 v3
    dcl_texcoord6 v4
    dcl_texcoord5_pp v5
    dcl_texcoord7 v6.xyz
    dcl_texcoord8 v7.xyz
    dcl vFace
    dcl_2d s0
    dcl_2d s1
    dcl_2d s3
    dcl_2d s4
    dcl_2d s7
    dcl_2d s10
    dcl_2d s13
    add_pp r0.x, -c61.z, c61.y
    rcp_pp r0.x, r0.x
    add r0.yzw, -c22.xxyz, v1.xxyz
    dp3 r1.x, r0.yzww, r0.yzww
    rsq r1.x, r1.x
    mul_pp r0.yzw, r0, r1.x
    rcp r1.x, r1.x
    add r1.x, r1.x, -c60.z
    dp3_pp r1.y, r0.yzww, c23
    add_pp r1.y, r1.y, -c61.z
    mul_sat_pp r0.x, r0.x, r1.y
    mad_pp r1.y, r0.x, c3.x, c3.y
    mul_pp r0.x, r0.x, r0.x
    mul_pp r0.x, r0.x, r1.y
    pow_sat_pp r1.y, r0.x, c61.w
    mov_pp r1.z, c1.z
    add r0.x, r1.z, -c61.x
    cmp_pp r0.x, r0.x, c1.z, r1.y
    add r1.y, -c60.z, c60.w
    rcp r1.y, r1.y
    mul_sat r1.x, r1.y, r1.x
    add_pp r1.x, -r1.x, c1.z
    cmp_pp r1.x, -c61.x, r1.z, r1.x
    mul_pp r0.x, r0.x, r1.x
    mul_pp r1.xyz, c59.w, c59
    mul_pp r1.xyz, r0.x, r1
    nrm_pp r2.xyz, v7
    texld_pp r3, v0, s3
    mul_pp r3.x, r3.w, r3.x
    mad_pp r3.xy, r3, c1.x, c1.y
    mul_pp r2.xyz, r2, r3.y
    nrm_pp r4.xyz, v6
    mad_pp r2.xyz, r3.x, r4, r2
    dp2add_pp r1.w, r3, -r3, c1.z
    rsq_pp r1.w, r1.w
    rcp_pp r1.w, r1.w
    cmp r3.xyz, vFace, v2, -v2
    nrm_pp r4.xyz, r3
    mad_pp r2.xyz, r1.w, r4, r2
    add_pp r3.xyz, c22, -v1
    dp3_pp r1.w, r3, r3
    rsq_pp r1.w, r1.w
    mad_pp r4.xyz, r3, r1.w, -r0.yzww
    dp3_pp r0.y, r2, -r0.yzww
    nrm_pp r5.xyz, r4
    dp3_sat_pp r0.z, r5, r2
    mov r4.xy, c2
    mul_pp r4.xy, r4, c20.yzzw
    max_pp r0.w, r4.x, c1.z
    min r2.w, r0.w, c0.w
    pow_pp r3.w, r0.z, r2.w
    mul_pp r1.xyz, r1, r3.w
    mov_sat r0.z, r0.y
    mul r1.xyz, r0.z, r1
    mul r1.xyz, r4.y, r1
    mad_pp r4.xzw, r3.xyyz, r1.w, -c10.xyyz
    mul_pp r3.xyz, r1.w, r3
    dp3_sat_pp r0.z, r3, c10
    nrm_pp r3.xyz, r4.xzww
    dp3_sat_pp r0.w, r3, r2
    dp3_pp r1.w, r2, -c10
    pow_pp r3.x, r0.w, r2.w
    max r0.w, v3.z, c1.w
    add r2.x, r0.w, -v3.w
    cmp r5.z, r2.x, c1.w, r0.w
    mov r5.xyw, v3
    texldp_pp r5, r5, s13
    max r0.w, v4.z, c1.w
    add r2.x, r0.w, -v4.w
    cmp r6.z, r2.x, c1.w, r0.w
    mov r6.xyw, v4
    texldp_pp r6, r6, s7
    min_pp r0.w, r6.x, r5.x
    lrp_pp r2.x, v5.z, c1.z, r0.w
    rcp r0.w, v3.w
    mul r2.yz, r0.w, v3.xxyw
    mad r2.yz, r2, c1.x, c1.y
    abs_sat r2.yz, r2
    add_sat r2.yz, r2, -c65.x
    mul r2.yz, r2, c65.y
    max r0.w, r2.y, r2.z
    lrp_pp r3.y, r0.w, c1.z, r2.x
    texld_pp r5, v0.zwzw, s10
    mul r0.w, r3.y, r5.w
    mul_pp r2.xyz, r0.w, c37
    mul_pp r2.xyz, r3.x, r2
    mov_sat r3.x, r1.w
    mul r2.xyz, r2, r3.x
    mad_pp r1.xyz, r2, r4.y, r1
    mul_pp r2.xyz, r4.y, c18
    mul_pp r0.z, r0.z, r0.w
    mul_pp r3.xyz, r0.w, c36
    pow r3.w, r0.z, r2.w
    mad_pp r0.z, r0.z, c3.z, c3.w
    mul_pp r4.xyz, r0.z, c36
    mul_pp r4.xyz, r4, c16
    mad r0.z, r3.w, c3.z, c3.w
    mul_pp r6.xyz, r0.z, c37
    mul_pp r2.xyz, r2, r6
    mul_pp r0.z, v5.w, v5.w
    mul_pp r0.w, r0.z, r0.z
    mul_pp r4.xyz, r0.z, r4
    mul_pp r2.xyz, r0.w, r2
    texld_pp r6, v0, s4
    mul_pp r2.xyz, r2, r6.w
    mad_pp r1.xyz, r1, c18, r2
    mul_pp r2.xyz, r5, r5
    dp3_pp r0.z, r2, c0
    mad_pp r2.xyz, r5, r5, -r0.z
    mad_sat_pp r2.xyz, r2, c71.w, r0.z
    mul_pp r2.xyz, r2, c70
    mul_pp r4.xyz, r4, r6.w
    mul_pp r5.xyz, c58.w, c58
    mul_pp r0.xzw, r0.x, r5.xyyz
    mad_pp r2.w, r0.y, c2.z, c2.z
    mad_pp r0.y, r0.y, -c2.z, c2.z
    mul_pp r0.y, r0.y, r0.y
    mul_pp r5.xyz, r0.xzww, r0.y
    mul_pp r0.y, r2.w, r2.w
    mul_pp r0.xyz, r0.xzww, r0.y
    mad_pp r0.w, r1.w, c2.z, c2.z
    mad_pp r1.w, r1.w, -c2.z, c2.z
    mul_pp r1.w, r1.w, r1.w
    mad_pp r5.xyz, r1.w, r3, r5
    mul_pp r5.xyz, r5, c16
    mul_pp r5.xyz, r6, r5
    mul_pp r5.xyz, r5, c150
    mul_pp r0.w, r0.w, r0.w
    mad_pp r0.xyz, r0.w, r3, r0
    mad_pp r0.xyz, r0, c16, r4
    mad_pp r0.xyz, r2, c17, r0
    texld_pp r2, v0, s0
    mad_pp r0.xyz, r0, r2, r5
    mul_pp r2.w, r2.w, c16.w
    texld_pp r3, v0, s1
    mad_pp r2.xyz, r1, r3, r0
    mul_pp r0, r2, c89
    min_pp r1, r0, c2.w
    mul_pp r0.xyz, c75, v5.y
    mad_pp oC0.xyz, r1, v5.x, r0
    mov_pp oC0.w, r1.w

// approximately 160 instruction slots used (7 texture, 153 arithmetic)
