//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_InstanceTypes[32];
//   row_major float4x4 g_MtxInvView;
//   row_major float4x4 g_MtxProjection;
//   row_major float4x4 g_MtxView;
//
//
// Registers:
//
//   Name            Reg   Size
//   --------------- ----- ----
//   g_MtxProjection c0       4
//   g_MtxView       c4       4
//   g_InstanceTypes c28     32
//   g_MtxInvView    c247     3
//

    vs_3_0
    def c8, 0.5, 1, 0, 0.00100000005
    dcl_position v0
    dcl_texcoord v1
    dcl_texcoord1 v2
    dcl_texcoord2 v3
    dcl_color1 v4
    dcl_position o0
    dcl_texcoord o1
    dcl_texcoord1 o2
    dcl_texcoord2 o3
    dcl_color o4
    add r0.x, c8.x, v3.x
    frc r0.y, r0.x
    add r0.x, -r0.y, r0.x
    add r0.x, r0.x, r0.x
    mova a0.x, r0.x
    add r0.xy, -c29[a0.x], c29[a0.x].zwzw
    mad o1.xy, v1, r0, c29[a0.x]
    mul r0.xyz, v0, c28[a0.x]
    dp3 r1.x, r0, c247
    dp3 r1.y, r0, c248
    dp3 r1.z, r0, c249
    add r0.xyz, r1, v2
    mul r1, r0.y, c5
    mad r1, r0.x, c4, r1
    mad r1, r0.z, c6, r1
    mov o3.xyz, r0
    add r0, r1, c7
    mul r1, r0.y, c1
    mad r1, r0.x, c0, r1
    mad r1, r0.z, c2, r1
    mad r1, r0.w, c3, r1
    mov o3.w, r0.z
    mov o0, r1
    mov o2, r1
    mad o1.zw, v3.y, c8.xyyz, c8.xywz
    mad o4, v4.xyzx, c8.yyyz, c8.zzzy

// approximately 26 instruction slots used
