//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   float4 g_GI0Scale;
//   float4 g_LightScatteringColor;
//   float4 g_OpacityReflectionRefractionSpectype;
//   float4 g_ShadowMapParams;
//   sampler2D g_ShadowMapSampler;
//   sampler2D g_VerticalShadowMapSampler;
//   float4 g_ViewportSize;
//   float4 g_aLightField[6];
//   float4 mrgEyeLight_Attribute;
//   float4 mrgEyeLight_Diffuse;
//   float4 mrgEyeLight_Range;
//   float4 mrgGlobalLight_Diffuse;
//   float4 mrgGlobalLight_Direction;
//   float4 mrgInShadowScale;
//   float4 mrgLocalLight0_Color;
//   float4 mrgLocalLight0_Position;
//   float4 mrgLocalLight0_Range;
//   float4 mrgLocalLight1_Color;
//   float4 mrgLocalLight1_Position;
//   float4 mrgLocalLight1_Range;
//   float4 mrgLocalLight2_Color;
//   float4 mrgLocalLight2_Position;
//   float4 mrgLocalLight2_Range;
//   float4 mrgLocalLight3_Color;
//   float4 mrgLocalLight3_Position;
//   float4 mrgLocalLight3_Range;
//   float4 mrgLuminanceRange;
//   float4 mrgPlayableParam;
//   float4 mrgTexcoordIndex[4];
//   sampler2D sampDif;
//   sampler2D sampEnv;
//   sampler2D sampNrm;
//
//
// Registers:
//
//   Name                                  Reg   Size
//   ------------------------------------- ----- ----
//   mrgGlobalLight_Direction              c10      1
//   g_Diffuse                             c16      1
//   g_Ambient                             c17      1
//   g_OpacityReflectionRefractionSpectype c21      1
//   g_EyePosition                         c22      1
//   g_EyeDirection                        c23      1
//   g_ViewportSize                        c24      1
//   mrgTexcoordIndex                      c26      2
//   mrgGlobalLight_Diffuse                c36      1
//   mrgLocalLight0_Position               c38      1
//   mrgLocalLight0_Color                  c39      1
//   mrgLocalLight0_Range                  c40      1
//   mrgLocalLight1_Position               c42      1
//   mrgLocalLight1_Color                  c43      1
//   mrgLocalLight1_Range                  c44      1
//   mrgLocalLight2_Position               c46      1
//   mrgLocalLight2_Color                  c47      1
//   mrgLocalLight2_Range                  c48      1
//   mrgLocalLight3_Position               c50      1
//   mrgLocalLight3_Color                  c51      1
//   mrgLocalLight3_Range                  c52      1
//   mrgEyeLight_Diffuse                   c58      1
//   mrgEyeLight_Range                     c60      1
//   mrgEyeLight_Attribute                 c61      1
//   mrgLuminanceRange                     c63      1
//   mrgInShadowScale                      c64      1
//   g_ShadowMapParams                     c65      1
//   g_GI0Scale                            c70      1
//   g_LightScatteringColor                c75      1
//   g_aLightField                         c77      6
//   mrgPlayableParam                      c86      1
//   g_ForceAlphaColor                     c89      1
//   sampDif                               s0       1
//   sampNrm                               s3       1
//   sampEnv                               s5       1
//   g_VerticalShadowMapSampler            s7       1
//   g_ShadowMapSampler                    s13      1
//

    ps_3_0
    def c0, 0.25, 4, 0, 0
    def c1, 0.5, 2, -1, -3
    def c2, 0, 1, 2, 3
    def c3, -1, 1, 0, 0.5
    dcl_texcoord v0
    dcl_texcoord1 v1
    dcl_texcoord2 v2.xyz
    dcl_texcoord3_pp v3
    dcl_texcoord4 v4
    dcl_texcoord6 v5
    dcl_texcoord5_pp v6.xyz
    dcl_texcoord7 v7.xyz
    dcl_texcoord8 v8.xyz
    dcl_color_pp v9
    dcl vPos.y
    dcl_2d s0
    dcl_2d s3
    dcl_2d s5
    dcl_2d s7
    dcl_2d s13
    add_pp r0.x, -c61.z, c61.y
    rcp_pp r0.x, r0.x
    add r0.yzw, -c22.xxyz, v2.xxyz
    dp3 r1.x, r0.yzww, r0.yzww
    rsq r1.x, r1.x
    mul_pp r0.yzw, r0, r1.x
    rcp r1.x, r1.x
    add r1.x, r1.x, -c60.z
    dp3_pp r1.y, r0.yzww, c23
    add_pp r1.y, r1.y, -c61.z
    mul_sat_pp r0.x, r0.x, r1.y
    mad_pp r1.y, r0.x, -c1.y, -c1.w
    mul_pp r0.x, r0.x, r0.x
    mul_pp r0.x, r0.x, r1.y
    pow_sat_pp r1.y, r0.x, c61.w
    mov r2.xy, c2
    add r0.x, r2.y, -c61.x
    cmp_pp r0.x, r0.x, c2.y, r1.y
    add r1.y, -c60.z, c60.w
    rcp r1.y, r1.y
    mul_sat r1.x, r1.y, r1.x
    add_pp r1.x, -r1.x, c2.y
    cmp_pp r1.x, -c61.x, r2.y, r1.x
    mul_pp r0.x, r0.x, r1.x
    add r1.x, -c44.z, c44.w
    rcp r1.x, r1.x
    add r1.yzw, -c42.xxyz, v2.xxyz
    dp3 r2.y, r1.yzww, r1.yzww
    rsq r2.y, r2.y
    rcp r2.z, r2.y
    mul_pp r1.yzw, r1, r2.y
    add r2.y, r2.z, -c44.z
    mul_sat r1.x, r1.x, r2.y
    add_pp r1.x, -r1.x, c2.y
    frc r2.y, c27.x
    cmp r2.z, -r2.y, c2.x, c2.y
    add r2.y, -r2.y, c27.x
    cmp r2.z, c27.x, r2.x, r2.z
    add r2.y, r2.z, r2.y
    add r3, r2.y, -c2
    cmp r2.yz, -r3_abs.x, v0.xxyw, c2.x
    cmp r2.yz, -r3_abs.y, v0.xzww, r2
    cmp r2.yz, -r3_abs.z, v1.xxyw, r2
    cmp r2.yz, -r3_abs.w, v1.xzww, r2
    texld_pp r3, r2.yzzw, s3
    mul_pp r3.x, r3.w, r3.x
    mad_pp r2.yz, r3.xxyw, c1.y, c1.z
    nrm_pp r3, v8.xyzx
    mul_pp r3, r2.z, r3
    nrm_pp r4, v7.xyzx
    mad_pp r3, r2.y, r4, r3
    dp2add_pp r2.y, r2.yzzw, -r2.yzzw, c2.y
    rsq_pp r2.y, r2.y
    rcp_pp r2.y, r2.y
    nrm_pp r4, v3.xyzx
    mad r3, r2.y, r4, r3
    dp3_pp r1.y, r3.wyzw, -r1.yzww
    mul_pp r2.yzw, r1.y, c43.xxyz
    cmp_pp r1.yzw, r1.y, r2, c2.x
    mul_pp r1.xyz, r1.yzww, r1.x
    add r1.w, -c40.z, c40.w
    rcp r1.w, r1.w
    add r2.yzw, -c38.xxyz, v2.xxyz
    dp3 r4.x, r2.yzww, r2.yzww
    rsq r4.x, r4.x
    rcp r4.y, r4.x
    mul_pp r2.yzw, r2, r4.x
    dp3_pp r2.y, r3.wyzw, -r2.yzww
    add r2.z, r4.y, -c40.z
    mul_sat r1.w, r1.w, r2.z
    add_pp r1.w, -r1.w, c2.y
    mul_pp r4.xyz, r2.y, c39
    cmp_pp r2.yzw, r2.y, r4.xxyz, c2.x
    mad_pp r1.xyz, r1.w, r2.yzww, r1
    add r1.w, -c48.z, c48.w
    rcp r1.w, r1.w
    add r2.yzw, -c46.xxyz, v2.xxyz
    dp3 r4.x, r2.yzww, r2.yzww
    rsq r4.x, r4.x
    rcp r4.y, r4.x
    mul_pp r2.yzw, r2, r4.x
    dp3_pp r2.y, r3.wyzw, -r2.yzww
    add r2.z, r4.y, -c48.z
    mul_sat r1.w, r1.w, r2.z
    add_pp r1.w, -r1.w, c2.y
    mul_pp r4.xyz, r2.y, c47
    cmp_pp r2.yzw, r2.y, r4.xxyz, c2.x
    mad_pp r1.xyz, r1.w, r2.yzww, r1
    add r1.w, -c52.z, c52.w
    rcp r1.w, r1.w
    add r2.yzw, -c50.xxyz, v2.xxyz
    dp3 r4.x, r2.yzww, r2.yzww
    rsq r4.x, r4.x
    rcp r4.y, r4.x
    mul_pp r2.yzw, r2, r4.x
    dp3_pp r2.y, r3.wyzw, -r2.yzww
    add r2.z, r4.y, -c52.z
    mul_sat r1.w, r1.w, r2.z
    add_pp r1.w, -r1.w, c2.y
    mul_pp r4.xyz, r2.y, c51
    cmp_pp r2.yzw, r2.y, r4.xxyz, c2.x
    mad_pp r1.xyz, r1.w, r2.yzww, r1
    max r1.w, v4.z, c2.x
    add r2.y, r1.w, -v4.w
    cmp r4.z, r2.y, c2.x, r1.w
    mov r4.xyw, v4
    texldp_pp r4, r4, s13
    max r1.w, v5.z, c2.x
    add r2.y, r1.w, -v5.w
    cmp r5.z, r2.y, c2.x, r1.w
    mov r5.xyw, v5
    texldp_pp r5, r5, s7
    min_pp r1.w, r5.x, r4.x
    lrp_pp r2.y, v6.z, c2.y, r5.x
    lrp_pp r2.z, v6.z, c2.y, r1.w
    rcp r1.w, v4.w
    mul r4.xy, r1.w, v4
    mad r4.xy, r4, c1.y, c1.z
    abs_sat r4.xy, r4
    add_sat r4.xy, r4, -c65.x
    mul r4.xy, r4, c65.y
    max r1.w, r4.x, r4.y
    lrp_pp r4.x, r1.w, c2.y, r2.z
    lrp_pp r4.y, r1.w, c2.y, r2.y
    mul r1.w, r4.x, c77.w
    dp3_pp r2.y, r3.wyzw, -c10
    mul r4.xzw, r2.y, c36.xyyz
    mul_pp r4.xzw, r1.w, r4
    cmp_pp r2.yzw, r2.y, r4.xxzw, c2.x
    add_pp r1.xyz, r1, r2.yzww
    dp3_pp r0.y, r3.wyzw, -r0.yzww
    mul_pp r2.yzw, c58.w, c58.xxyz
    mul_pp r2.yzw, r0.y, r2
    cmp_pp r0.yzw, r0.y, r2, c2.x
    mad_pp r0.xyz, r0.x, r0.yzww, r1
    mad_pp r1.xyz, r3.wyzw, c1.x, c1.x
    mov r5.xyz, c79
    add r2.yzw, -r5.xxyz, c80.xxyz
    mad r2.yzw, r1.y, r2, c79.xxyz
    mul_pp r4.xzw, r3.wyyz, r3.wyyz
    mul r2.yzw, r2, r4.z
    mov r5.xyz, c77
    add r5.xyz, -r5, c78
    mad r5.xyz, r1.x, r5, c77
    mad_pp r2.yzw, r4.x, r5.xxyz, r2
    mov r5.xyz, c81
    add r5.xyz, -r5, c82
    mad r1.xyz, r1.z, r5, c81
    mad_pp r1.xyz, r4.w, r1, r2.yzww
    mul_pp r2.yzw, r1.xxyz, c17.xxyz
    mul r2.yzw, r2, c70.w
    mad r1.xyz, r1, c17, -r2.yzww
    mad_pp r1.xyz, r4.y, r1, r2.yzww
    add_pp r0.xyz, r0, r1
    mul_pp r0.xyz, r0, c16
    frc r0.w, c26.x
    cmp r1.x, -r0.w, c2.x, c2.y
    add r0.w, -r0.w, c26.x
    cmp r1.x, c26.x, r2.x, r1.x
    add r0.w, r0.w, r1.x
    add r2, r0.w, -c2
    cmp r1.xy, -r2_abs.x, v0, c2.x
    cmp r1.xy, -r2_abs.y, v0.zwzw, r1
    cmp r1.xy, -r2_abs.z, v1, r1
    cmp r1.xy, -r2_abs.w, v1.zwzw, r1
    texld_pp r2, r1, s0
    mul_pp r0.w, r2.w, c16.w
    mul_pp r0.w, r0.w, v9.w
    mul_pp r4.w, r0.w, c21.x
    add r0.w, c1.x, vPos.y
    mov r1.x, c86.x
    mad r0.w, r0.w, c24.w, -r1.x
    mul_sat_pp r0.w, r0.w, c86.y
    lrp_pp r1.xyz, r0.w, r2, c2.y
    add_pp r2, c22.xyzx, -v2.xyzx
    dp3_pp r0.w, r2.yzww, r2.yzww
    rsq_pp r0.w, r0.w
    mul r2, r0.w, r2
    dp3 r0.w, r2.yzww, r3.yzww
    add r0.w, r0.w, r0.w
    mad r2, r0.w, r3, -r2
    mad r3, r2.wyzw, c3.xxyz, c3.zzzw
    mul r5, r2, c3.yxxz
    cmp r2, r2.z, r3, r5
    add r0.w, r2.z, c2.y
    rcp r0.w, r0.w
    mad r2.xy, r2.yxzw, r0.w, c2.y
    mad_pp r3.x, r2.y, c0.x, r2.w
    mul_pp r3.y, r2.x, c1.x
    texld_pp r2, r3, s5
    mul r3.xyz, r2, c63.x
    mad_pp r2.xyz, r3, r2.w, r2
    mul r0.w, c64.z, c64.x
    mov r3.xz, c64
    mad r2.w, r3.x, -r3.z, r3.z
    mad_pp r0.w, r1.w, r2.w, r0.w
    mul_pp r2.xyz, r0.w, r2
    mul_pp r2.xyz, r2, v3.w
    mad_pp r0.xyz, r0, r1, r2
    mul_pp r4.xyz, r0, v9
    mul_pp r0, r4, c89
    min_pp r1, r0, c0.y
    mul_pp r0.xyz, c75, v6.y
    mad_pp oC0.xyz, r1, v6.x, r0
    mov_pp oC0.w, r1.w

// approximately 214 instruction slots used (5 texture, 209 arithmetic)
