//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Diffuse;
//   float4 g_ForceAlphaColor;
//   float4 g_LightScatteringColor;
//   row_major float4x4 g_MtxView;
//   float4 g_OpacityReflectionRefractionSpectype;
//   float4 mrgTexcoordIndex[4];
//   sampler2D sampDif;
//   sampler2D sampEmi;
//
//
// Registers:
//
//   Name                                  Reg   Size
//   ------------------------------------- ----- ----
//   g_Diffuse                             c16      1
//   g_OpacityReflectionRefractionSpectype c21      1
//   mrgTexcoordIndex                      c26      1
//   g_LightScatteringColor                c75      1
//   g_ForceAlphaColor                     c89      1
//   g_MtxView                             c90      3
//   sampDif                               s0       1
//   sampEmi                               s3       1
//

    ps_3_0
    def c0, 0.5, -0.5, 4, 0
    def c1, 0, 1, 2, 3
    dcl_texcoord v0
    dcl_texcoord1 v1
    dcl_texcoord3 v2.xyz
    dcl_texcoord5_pp v3.xy
    dcl_color_pp v4
    dcl_2d s0
    dcl_2d s3
    nrm_pp r0.xyz, v2
    mul r1, r0.y, c91
    mad r1, r0.x, c90, r1
    mad r0, r0.z, c92, r1
    dp4 r0.z, r0, r0
    rsq r0.z, r0.z
    mul r0.xy, r0.z, r0
    mad_pp r0.xy, r0, c0, c0.x
    texld_pp r0, r0, s3
    frc r0.w, c26.x
    cmp r1.x, -r0.w, c1.x, c1.y
    add r0.w, -r0.w, c26.x
    mov r2.x, c1.x
    cmp r1.x, c26.x, r2.x, r1.x
    add r0.w, r0.w, r1.x
    add r1, r0.w, -c1
    cmp r2.xy, -r1_abs.x, v0, c1.x
    cmp r1.xy, -r1_abs.y, v0.zwzw, r2
    cmp r1.xy, -r1_abs.z, v1, r1
    cmp r1.xy, -r1_abs.w, v1.zwzw, r1
    texld_pp r1, r1, s0
    mul_pp r1, r1, c16
    mad_pp r0.xyz, r1, v4, r0
    mul_pp r1.x, r1.w, v4.w
    mul_pp r0.w, r1.x, c21.x
    mul_pp r0, r0, c89
    min_pp r1, r0, c0.z
    mul_pp r0.xyz, c75, v3.y
    mad_pp oC0.xyz, r1, v3.x, r0
    mov_pp oC0.w, r1.w

// approximately 32 instruction slots used (2 texture, 30 arithmetic)
