//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   float4 g_GI0Scale;
//   float4 g_LightScatteringColor;
//   float4 g_OpacityReflectionRefractionSpectype;
//   float4 g_ShadowMapParams;
//   sampler2D g_ShadowMapSampler;
//   sampler2D g_VerticalShadowMapSampler;
//   float4 g_aLightField[6];
//   float4 mrgChrEmissionParam;
//   float4 mrgEyeLight_Attribute;
//   float4 mrgEyeLight_Diffuse;
//   float4 mrgEyeLight_Range;
//   float4 mrgGlobalLight_Diffuse;
//   float4 mrgGlobalLight_Direction;
//   sampler2D sampDif;
//
//
// Registers:
//
//   Name                                  Reg   Size
//   ------------------------------------- ----- ----
//   mrgGlobalLight_Direction              c10      1
//   g_Diffuse                             c16      1
//   g_Ambient                             c17      1
//   g_OpacityReflectionRefractionSpectype c21      1
//   g_EyePosition                         c22      1
//   g_EyeDirection                        c23      1
//   mrgGlobalLight_Diffuse                c36      1
//   mrgEyeLight_Diffuse                   c58      1
//   mrgEyeLight_Range                     c60      1
//   mrgEyeLight_Attribute                 c61      1
//   g_ShadowMapParams                     c65      1
//   g_GI0Scale                            c70      1
//   g_LightScatteringColor                c75      1
//   g_aLightField                         c77      6
//   g_ForceAlphaColor                     c89      1
//   mrgChrEmissionParam                   c150     1
//   sampDif                               s0       1
//   g_VerticalShadowMapSampler            s7       1
//   g_ShadowMapSampler                    s13      1
//

    ps_3_0
    def c0, 0.5, 0, 1, -2
    def c1, -0.0500000007, 1.05263162, -2, 3
    def c2, 4, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_texcoord2 v1.xyz
    dcl_texcoord3_pp v2.xyz
    dcl_texcoord4 v3
    dcl_texcoord6 v4
    dcl_texcoord5_pp v5.xyz
    dcl_color_pp v6
    dcl_2d s0
    dcl_2d s7
    dcl_2d s13
    add_pp r0.x, -c61.z, c61.y
    rcp_pp r0.x, r0.x
    add r0.yzw, -c22.xxyz, v1.xxyz
    dp3 r1.x, r0.yzww, r0.yzww
    rsq r1.x, r1.x
    mul_pp r0.yzw, r0, r1.x
    rcp r1.x, r1.x
    add r1.x, r1.x, -c60.z
    dp3_pp r1.y, r0.yzww, c23
    add_pp r1.y, r1.y, -c61.z
    mul_sat_pp r0.x, r0.x, r1.y
    mad_pp r1.y, r0.x, c1.z, c1.w
    mul_pp r0.x, r0.x, r0.x
    mul_pp r0.x, r0.x, r1.y
    pow_sat_pp r1.y, r0.x, c61.w
    mov_pp r1.z, c0.z
    add r0.x, r1.z, -c61.x
    cmp_pp r0.x, r0.x, c0.z, r1.y
    add r1.y, -c60.z, c60.w
    rcp r1.y, r1.y
    mul_sat r1.x, r1.y, r1.x
    add_pp r1.x, -r1.x, c0.z
    cmp_pp r1.x, -c61.x, r1.z, r1.x
    mul_pp r0.x, r0.x, r1.x
    nrm_pp r1.xyz, v2
    dp3_pp r0.y, r1, -r0.yzww
    add_pp r0.y, r0.y, c1.x
    mul_sat_pp r0.y, r0.y, c1.y
    mul r2.xyz, c58.w, c58
    mul_pp r0.yzw, r0.y, r2.xxyz
    mul_pp r0.xyz, r0.yzww, r0.x
    max r0.w, v3.z, c0.y
    add r1.w, r0.w, -v3.w
    cmp r2.z, r1.w, c0.y, r0.w
    mov r2.xyw, v3
    texldp_pp r2, r2, s13
    max r0.w, v4.z, c0.y
    add r1.w, r0.w, -v4.w
    cmp r3.z, r1.w, c0.y, r0.w
    mov r3.xyw, v4
    texldp_pp r3, r3, s7
    min_pp r0.w, r3.x, r2.x
    lrp_pp r1.w, v5.z, c0.z, r3.x
    lrp_pp r2.x, v5.z, c0.z, r0.w
    rcp r0.w, v3.w
    mul r2.yz, r0.w, v3.xxyw
    mad r2.yz, r2, -c0.w, -c0.z
    abs_sat r2.yz, r2
    add_sat r2.yz, r2, -c65.x
    mul r2.yz, r2, c65.y
    max r0.w, r2.y, r2.z
    lrp_pp r3.x, r0.w, c0.z, r2.x
    lrp_pp r2.x, r0.w, c0.z, r1.w
    mul_pp r0.w, r3.x, c77.w
    dp3_pp r1.w, r1, -c10
    add_pp r1.w, r1.w, c1.x
    mul_sat_pp r1.w, r1.w, c1.y
    mul_pp r2.yzw, r1.w, c36.xxyz
    mad_pp r0.xyz, r2.yzww, r0.w, r0
    mov r3.xyz, c79
    add r2.yzw, -r3.xxyz, c80.xxyz
    mad_pp r3.xyz, r1, c0.x, c0.x
    mul_pp r1.xyz, r1, r1
    mad r2.yzw, r3.y, r2, c79.xxyz
    mul r2.yzw, r1.y, r2
    mov r4.xyz, c77
    add r4.xyz, -r4, c78
    mad r3.xyw, r3.x, r4.xyzz, c77.xyzz
    mad_pp r1.xyw, r1.x, r3, r2.yzzw
    mov r4.xyz, c81
    add r2.yzw, -r4.xxyz, c82.xxyz
    mad r2.yzw, r3.z, r2, c81.xxyz
    mad_pp r1.xyz, r1.z, r2.yzww, r1.xyww
    mul r2.yzw, r1.xxyz, c70.w
    mad r1.xyz, r1, -c70.w, r1
    mad_pp r1.xyz, r2.x, r1, r2.yzww
    add_pp r0.xyz, r0, r1
    mul_pp r0.xyz, r0, c16
    mov r1.xyz, c150
    mul_pp r1.xyz, r1, c17
    mul r1.xyz, r1, c150.w
    texld_pp r2, v0, s0
    mad_pp r0.xyz, r0, r2, r1
    mul_pp r0.w, r2.w, c16.w
    mul_pp r0, r0, v6
    mul_pp r0.w, r0.w, c21.x
    mul_pp r0, r0, c89
    min_pp r1, r0, c2.x
    mul_pp r0.xyz, c75, v5.y
    mad_pp oC0.xyz, r1, v5.x, r0
    mov_pp oC0.w, r1.w

// approximately 95 instruction slots used (3 texture, 92 arithmetic)
