//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   float4 g_GI0Scale;
//   float4 g_LightScatteringColor;
//   row_major float4x4 g_MtxView;
//   float4 g_OpacityReflectionRefractionSpectype;
//   float4 g_PowerGlossLevel;
//   float4 g_ShadowMapParams;
//   sampler2D g_ShadowMapSampler;
//   float4 g_SonicSkinFalloffParam;
//   float4 g_Specular;
//   sampler2D g_VerticalShadowMapSampler;
//   float4 g_aLightField[6];
//   float4 mrgEyeLight_Attribute;
//   float4 mrgEyeLight_Diffuse;
//   float4 mrgEyeLight_Range;
//   float4 mrgEyeLight_Specular;
//   float4 mrgGlobalLight_Diffuse;
//   float4 mrgGlobalLight_Direction;
//   float4 mrgGlobalLight_Specular;
//   float4 mrgInShadowScale;
//   float4 mrgLuminanceRange;
//   float4 mrgTexcoordIndex[4];
//   sampler2D sampDif;
//   sampler2D sampEnv;
//   sampler2D sampSpec;
//
//
// Registers:
//
//   Name                                  Reg   Size
//   ------------------------------------- ----- ----
//   mrgGlobalLight_Direction              c10      1
//   g_Diffuse                             c16      1
//   g_Ambient                             c17      1
//   g_Specular                            c18      1
//   g_PowerGlossLevel                     c20      1
//   g_OpacityReflectionRefractionSpectype c21      1
//   g_EyePosition                         c22      1
//   g_EyeDirection                        c23      1
//   mrgTexcoordIndex                      c26      1
//   mrgGlobalLight_Diffuse                c36      1
//   mrgGlobalLight_Specular               c37      1
//   mrgEyeLight_Diffuse                   c58      1
//   mrgEyeLight_Specular                  c59      1
//   mrgEyeLight_Range                     c60      1
//   mrgEyeLight_Attribute                 c61      1
//   mrgLuminanceRange                     c63      1
//   mrgInShadowScale                      c64      1
//   g_ShadowMapParams                     c65      1
//   g_GI0Scale                            c70      1
//   g_LightScatteringColor                c75      1
//   g_aLightField                         c77      6
//   g_ForceAlphaColor                     c89      1
//   g_MtxView                             c90      3
//   g_SonicSkinFalloffParam               c150     1
//   sampDif                               s0       1
//   sampSpec                              s1       1
//   sampEnv                               s4       1
//   g_VerticalShadowMapSampler            s7       1
//   g_ShadowMapSampler                    s13      1
//

    ps_3_0
    def c0, 1.05263162, -2, 3, 1024
    def c1, 0.5, 2, -1, -0.0500000007
    def c2, 500, 5, 0.5, -0.5
    def c3, 4, 0, 0, 0
    def c4, 0, 1, 2, 3
    dcl_texcoord v0
    dcl_texcoord1 v1
    dcl_texcoord2 v2.xyz
    dcl_texcoord3_pp v3
    dcl_texcoord4 v4
    dcl_texcoord6 v5
    dcl_texcoord5_pp v6.xyz
    dcl_color_pp v7
    dcl_2d s0
    dcl_2d s1
    dcl_2d s4
    dcl_2d s7
    dcl_2d s13
    frc r0.xy, c26.xzzw
    cmp r0.zw, -r0.xyxy, c4.x, c4.y
    add r0.xy, -r0, c26.xzzw
    mov r1.xy, c4
    cmp r0.zw, c26.xyxz, r1.x, r0
    add r0.xy, r0.zwzw, r0
    add r2, r0.y, -c4
    add r0, r0.x, -c4
    cmp r1.xz, -r2_abs.x, v0.xyyw, c4.x
    cmp r1.xz, -r2_abs.y, v0.zyww, r1
    cmp r1.xz, -r2_abs.z, v1.xyyw, r1
    cmp r1.xz, -r2_abs.w, v1.zyww, r1
    texld_pp r2, r1.xzzw, s1
    max r1.x, v4.z, c4.x
    add r1.z, r1.x, -v4.w
    cmp r3.z, r1.z, c4.x, r1.x
    mov r3.xyw, v4
    texldp_pp r3, r3, s13
    max r1.x, v5.z, c4.x
    add r1.z, r1.x, -v5.w
    cmp r4.z, r1.z, c4.x, r1.x
    mov r4.xyw, v5
    texldp_pp r4, r4, s7
    min_pp r1.x, r4.x, r3.x
    lrp_pp r1.z, v6.z, c4.y, r4.x
    lrp_pp r3.x, v6.z, c4.y, r1.x
    rcp r1.x, v4.w
    mul r1.xw, r1.x, v4.xyzy
    mad r1.xw, r1, c1.y, c1.z
    abs_sat r1.xw, r1
    add_sat r1.xw, r1, -c65.x
    mul r1.xw, r1, c65.y
    max r3.y, r1.x, r1.w
    lrp_pp r1.x, r3.y, c4.y, r3.x
    lrp_pp r4.x, r3.y, c4.y, r1.z
    mul r1.x, r1.x, c77.w
    add_pp r1.z, -c61.z, c61.y
    rcp_pp r1.z, r1.z
    add r3.xyz, -c22, v2
    dp3 r1.w, r3, r3
    rsq r1.w, r1.w
    mul_pp r3.xyz, r1.w, r3
    rcp r1.w, r1.w
    add r1.w, r1.w, -c60.z
    dp3_pp r3.w, r3, c23
    add_pp r3.w, r3.w, -c61.z
    mul_sat_pp r1.z, r1.z, r3.w
    mad_pp r3.w, r1.z, c0.y, c0.z
    mul_pp r1.z, r1.z, r1.z
    mul_pp r1.z, r1.z, r3.w
    pow_sat_pp r3.w, r1.z, c61.w
    add r1.z, r1.y, -c61.x
    cmp_pp r1.z, r1.z, c4.y, r3.w
    add r3.w, -c60.z, c60.w
    rcp r3.w, r3.w
    mul_sat r1.w, r1.w, r3.w
    add_pp r1.w, -r1.w, c4.y
    cmp_pp r1.y, -c61.x, r1.y, r1.w
    mul_pp r1.y, r1.z, r1.y
    mul_pp r4.yzw, c59.w, c59.xxyz
    mov_pp r5.xy, c2
    mul_pp r1.zw, r5.xyxy, c20.xyyz
    mul_pp r4.yzw, r1.w, r4
    max_pp r3.w, r1.z, c4.y
    mul_pp r5.xyz, r1.w, c37
    min r1.z, r3.w, c0.w
    add_pp r6.xyz, c22, -v2
    dp3_pp r1.w, r6, r6
    rsq_pp r1.w, r1.w
    mad_pp r7.xyz, r6, r1.w, -r3
    nrm_pp r8.xyz, r7
    nrm_pp r7.xyz, v3
    dp3_sat_pp r3.w, r8, r7
    pow r5.w, r3.w, r1.z
    mul_pp r4.yzw, r4, r5.w
    mul_pp r4.yzw, r1.y, r4
    mad_pp r8.xyz, r6, r1.w, -c10
    mul_pp r6.xyz, r1.w, r6
    nrm_pp r9.xyz, r8
    dp3_sat_pp r1.w, r9, r7
    pow r3.w, r1.w, r1.z
    mul_pp r5.xyz, r3.w, r5
    mad_pp r4.yzw, r5.xxyz, r1.x, r4
    mul_pp r4.yzw, r4, c18.xxyz
    mul r1.z, c64.z, c64.x
    mov r5.xz, c64
    mad r1.w, r5.x, -r5.z, r5.z
    mad_pp r1.z, r1.x, r1.w, r1.z
    mul r5, r7.y, c91
    mad r5, r7.x, c90, r5
    mad r5, r7.z, c92, r5
    dp4 r1.w, r5, r5
    rsq r1.w, r1.w
    mul r5.xy, r1.w, r5
    mad_pp r5.xy, r5, c2.zwzw, c2.z
    texld_pp r5, r5, s4
    mul r8.xyz, r5, c63.x
    mad_pp r5.xyz, r8, r5.w, r5
    mul_pp r5.xyz, r2.w, r5
    mul_pp r5.xyz, r1.z, r5
    mad_pp r2.xyz, r4.yzww, r2, r5
    mul_pp r2.xyz, r2, v3.w
    dp3_pp r1.z, r7, -r3
    add_pp r1.z, r1.z, c1.w
    mul_sat_pp r1.z, r1.z, c0.x
    mul r3.xyz, c58.w, c58
    mul_pp r3.xyz, r1.z, r3
    mul_pp r1.yzw, r1.y, r3.xxyz
    dp3_pp r2.w, r7, -c10
    add_pp r2.w, r2.w, c1.w
    mul_sat_pp r2.w, r2.w, c0.x
    mul_pp r3.xyz, r2.w, c36
    mad_pp r1.yzw, r3.xxyz, r1.x, r1
    mad r1.x, r1.x, c1.x, c1.x
    mov r3.xyz, c79
    add r3.xyz, -r3, c80
    mad_pp r4.yzw, r7.xxyz, c1.x, c1.x
    mad r5.xyz, r4.z, r3, c79
    mul_pp r8.xyz, r7, r7
    mul r5.xyz, r5, r8.y
    mov r9.xyz, c77
    add r9.xyz, -r9, c78
    mad r10.xyz, r4.y, r9, c77
    mad_pp r5.xyz, r8.x, r10, r5
    mov r10.xyz, c81
    add r8.xyw, -r10.xyzz, c82.xyzz
    mad r4.yzw, r4.w, r8.xxyw, c81.xxyz
    mad_pp r4.yzw, r8.z, r4, r5.xxyz
    mul_pp r5.xyz, r4.yzww, c17
    mul r5.xyz, r5, c70.w
    mad r4.yzw, r4, c17.xxyz, -r5.xxyz
    mad_pp r4.xyz, r4.x, r4.yzww, r5
    add_pp r1.yzw, r1, r4.xxyz
    mul_pp r1.yzw, r1, c16.xxyz
    cmp r4.xy, -r0_abs.x, v0, c4.x
    cmp r0.xy, -r0_abs.y, v0.zwzw, r4
    cmp r0.xy, -r0_abs.z, v1, r0
    cmp r0.xy, -r0_abs.w, v1.zwzw, r0
    texld_pp r0, r0, s0
    mad_pp r0.xyz, r1.yzww, r0, r2
    mul_pp r2.w, r0.w, c16.w
    dp3_pp r0.w, r6, r7
    add_sat_pp r1.y, -r0.w, c4.y
    add_pp r0.w, r0.w, r0.w
    mad_pp r4.xyz, r0.w, r7, -r6
    pow_pp r0.w, r1.y, c150.z
    mul r0.w, r0.w, c150.y
    mad_pp r0.w, r0.w, r1.x, c150.x
    mad_pp r1.xyz, r4, c1.x, c1.x
    mul_pp r4.xyz, r4, r4
    mad r3.xyz, r1.y, r3, c79
    mul r3.xyz, r3, r4.y
    mad r1.xyw, r1.x, r9.xyzz, c77.xyzz
    mad r5.xyz, r1.z, r8.xyww, c81
    mad_pp r1.xyz, r4.x, r1.xyww, r3
    mad_pp r1.xyz, r4.z, r5, r1
    mad_pp r2.xyz, r1, r0.w, r0
    mul_pp r0, r2, v7
    mul_pp r0.w, r0.w, c21.x
    mul_pp r0, r0, c89
    min_pp r1, r0, c3.x
    mul_pp r0.xyz, c75, v6.y
    mad_pp oC0.xyz, r1, v6.x, r0
    mov_pp oC0.w, r1.w

// approximately 178 instruction slots used (5 texture, 173 arithmetic)
