//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   float4 g_GI0Scale;
//   float4 g_GI1Scale;
//   sampler2D g_GISampler;
//   float4 g_LightScatteringColor;
//   float4 g_PowerGlossLevel;
//   float4 g_ShadowMapParams;
//   sampler2D g_ShadowMapSampler;
//   float4 g_Specular;
//   sampler2D g_VerticalShadowMapSampler;
//   float4 mrgEyeLight_Attribute;
//   float4 mrgEyeLight_Diffuse;
//   float4 mrgEyeLight_Range;
//   float4 mrgEyeLight_Specular;
//   float4 mrgGlobalLight_Diffuse;
//   float4 mrgGlobalLight_Direction;
//   float4 mrgGlobalLight_Specular;
//   float4 mrgLocalLight0_Color;
//   float4 mrgLocalLight0_Position;
//   float4 mrgLocalLight0_Range;
//   float4 mrgLocalLight1_Color;
//   float4 mrgLocalLight1_Position;
//   float4 mrgLocalLight1_Range;
//   float4 mrgLocalLight2_Color;
//   float4 mrgLocalLight2_Position;
//   float4 mrgLocalLight2_Range;
//   float4 mrgLocalLight3_Color;
//   float4 mrgLocalLight3_Position;
//   float4 mrgLocalLight3_Range;
//   float4 mrgTexcoordIndex[4];
//   sampler2D sampDif;
//   sampler2D sampNrm;
//
//
// Registers:
//
//   Name                       Reg   Size
//   -------------------------- ----- ----
//   mrgGlobalLight_Direction   c10      1
//   g_Diffuse                  c16      1
//   g_Ambient                  c17      1
//   g_Specular                 c18      1
//   g_PowerGlossLevel          c20      1
//   g_EyePosition              c22      1
//   g_EyeDirection             c23      1
//   mrgTexcoordIndex           c26      1
//   mrgGlobalLight_Diffuse     c36      1
//   mrgGlobalLight_Specular    c37      1
//   mrgLocalLight0_Position    c38      1
//   mrgLocalLight0_Color       c39      1
//   mrgLocalLight0_Range       c40      1
//   mrgLocalLight1_Position    c42      1
//   mrgLocalLight1_Color       c43      1
//   mrgLocalLight1_Range       c44      1
//   mrgLocalLight2_Position    c46      1
//   mrgLocalLight2_Color       c47      1
//   mrgLocalLight2_Range       c48      1
//   mrgLocalLight3_Position    c50      1
//   mrgLocalLight3_Color       c51      1
//   mrgLocalLight3_Range       c52      1
//   mrgEyeLight_Diffuse        c58      1
//   mrgEyeLight_Specular       c59      1
//   mrgEyeLight_Range          c60      1
//   mrgEyeLight_Attribute      c61      1
//   g_ShadowMapParams          c65      1
//   g_GI0Scale                 c70      1
//   g_GI1Scale                 c71      1
//   g_LightScatteringColor     c75      1
//   g_ForceAlphaColor          c89      1
//   sampDif                    s0       1
//   sampNrm                    s2       1
//   g_VerticalShadowMapSampler s7       1
//   g_GISampler                s10      1
//   g_ShadowMapSampler         s13      1
//

    ps_3_0
    def c0, 0.298900008, 0.586600006, 0.114399999, 1024
    def c1, 2, -1, -2, 3
    def c2, 500, 5, 4, 0
    def c3, 0, 1, 2, 3
    dcl_texcoord v0
    dcl_texcoord1 v1
    dcl_texcoord2 v2.xyz
    dcl_texcoord3_pp v3
    dcl_texcoord4 v4
    dcl_texcoord6 v5
    dcl_texcoord5_pp v6.xyz
    dcl_texcoord7 v7.xyz
    dcl_texcoord8 v8.xyz
    dcl_color_pp v9.x
    dcl_2d s0
    dcl_2d s2
    dcl_2d s7
    dcl_2d s10
    dcl_2d s13
    add_pp r0.x, -c61.z, c61.y
    rcp_pp r0.x, r0.x
    add r0.yzw, -c22.xxyz, v2.xxyz
    dp3 r1.x, r0.yzww, r0.yzww
    rsq r1.x, r1.x
    mul_pp r0.yzw, r0, r1.x
    rcp r1.x, r1.x
    add r1.x, r1.x, -c60.z
    dp3_pp r1.y, r0.yzww, c23
    add_pp r1.y, r1.y, -c61.z
    mul_sat_pp r0.x, r0.x, r1.y
    mad_pp r1.y, r0.x, c1.z, c1.w
    mul_pp r0.x, r0.x, r0.x
    mul_pp r0.x, r0.x, r1.y
    pow_sat_pp r1.y, r0.x, c61.w
    mov r2.xy, c3
    add r0.x, r2.y, -c61.x
    cmp_pp r0.x, r0.x, c3.y, r1.y
    add r1.y, -c60.z, c60.w
    rcp r1.y, r1.y
    mul_sat r1.x, r1.y, r1.x
    add_pp r1.x, -r1.x, c3.y
    cmp_pp r1.x, -c61.x, r2.y, r1.x
    mul_pp r0.x, r0.x, r1.x
    max r1.x, v4.z, c3.x
    add r1.y, r1.x, -v4.w
    cmp r1.z, r1.y, c3.x, r1.x
    mov r1.xyw, v4
    texldp_pp r1, r1, s13
    max r1.y, v5.z, c3.x
    add r1.z, r1.y, -v5.w
    cmp r3.z, r1.z, c3.x, r1.y
    mov r3.xyw, v5
    texldp_pp r3, r3, s7
    min_pp r2.y, r3.x, r1.x
    lrp_pp r1.x, v6.z, c3.y, r2.y
    rcp r1.y, v4.w
    mul r1.yz, r1.y, v4.xxyw
    mad r1.yz, r1, c1.x, c1.y
    abs_sat r1.yz, r1
    add_sat r1.yz, r1, -c65.x
    mul r1.yz, r1, c65.y
    max r2.y, r1.y, r1.z
    lrp_pp r3.x, r2.y, c3.y, r1.x
    texld_pp r1, v0.zwzw, s10
    mul_pp r1.w, r3.x, r1.w
    add r2.y, -c48.z, c48.w
    rcp r2.y, r2.y
    add r3.xyz, -c46, v2
    dp3 r2.z, r3, r3
    rsq r2.z, r2.z
    rcp r2.w, r2.z
    mul_pp r3.xyz, r2.z, r3
    add r2.z, r2.w, -c48.z
    mul_sat r2.y, r2.y, r2.z
    add r2.z, -c40.z, c40.w
    rcp r2.z, r2.z
    add r4.xyz, -c38, v2
    dp3 r2.w, r4, r4
    rsq r2.w, r2.w
    rcp r3.w, r2.w
    mul_pp r4.xyz, r2.w, r4
    add r2.w, r3.w, -c40.z
    mul_sat r2.z, r2.z, r2.w
    add r2.w, -c44.z, c44.w
    rcp r2.w, r2.w
    add r5.xyz, -c42, v2
    dp3 r3.w, r5, r5
    rsq r3.w, r3.w
    rcp r4.w, r3.w
    mul_pp r5.xyz, r3.w, r5
    add r3.w, r4.w, -c44.z
    mul_sat r2.w, r2.w, r3.w
    add_pp r2.yzw, -r2, c3.y
    frc r6.xy, c26.wxzw
    cmp r6.zw, -r6.xyxy, c3.x, c3.y
    add r6.xy, -r6, c26.wxzw
    cmp r6.zw, c26.xywx, r2.x, r6
    add r6.xy, r6.zwzw, r6
    add r7, r6.x, -c3
    add r6, r6.y, -c3
    cmp r8.xy, -r7_abs.x, v0, c3.x
    cmp r7.xy, -r7_abs.y, v0.zwzw, r8
    cmp r7.xy, -r7_abs.z, v1, r7
    cmp r7.xy, -r7_abs.w, v1.zwzw, r7
    texld_pp r7, r7, s2
    mul_pp r7.x, r7.w, r7.x
    mad_pp r7.xy, r7, c1.x, c1.y
    nrm_pp r8.xyz, v8
    mul_pp r8.xyz, r7.y, r8
    nrm_pp r9.xyz, v7
    mad_pp r8.xyz, r7.x, r9, r8
    dp2add_pp r2.x, r7, -r7, c3.y
    rsq_pp r2.x, r2.x
    rcp_pp r2.x, r2.x
    dp3 r3.w, v3, v3
    rsq r3.w, r3.w
    mul r7.xyz, r3.w, v3
    mad_pp r7.xyz, r2.x, r7, r8
    mad r8.xyz, v3, r3.w, -r7
    mad r7.xyz, v9.x, r8, r7
    nrm_pp r8.xyz, r7
    add_pp r7.xyz, c22, -v2
    dp3_pp r2.x, r7, r7
    rsq_pp r2.x, r2.x
    mad_pp r9.xyz, r7, r2.x, -r5
    dp3_pp r3.w, r8, -r5
    nrm_pp r5.xyz, r9
    dp3_sat_pp r4.w, r5, r8
    mov_pp r5.xy, c2
    mul_pp r5.xy, r5, c20.yzzw
    max_pp r7.w, r5.x, c3.y
    min r5.x, r7.w, c0.w
    pow r7.w, r4.w, r5.x
    mul_pp r9.xyz, r5.y, c43
    mul_pp r9.xyz, r7.w, r9
    mul_pp r9.xyz, r2.w, r9
    mad_pp r10.xyz, r7, r2.x, -r4
    dp3_pp r4.x, r8, -r4
    nrm_pp r11.xyz, r10
    dp3_sat_pp r4.y, r11, r8
    pow r7.w, r4.y, r5.x
    mul_pp r4.yzw, r5.y, c39.xxyz
    mul_pp r4.yzw, r7.w, r4
    mad_pp r4.yzw, r2.z, r4, r9.xxyz
    mad_pp r9.xyz, r7, r2.x, -r3
    dp3_pp r3.x, r8, -r3
    nrm_pp r10.xyz, r9
    dp3_sat_pp r3.y, r10, r8
    pow r7.w, r3.y, r5.x
    mul_pp r9.xyz, r5.y, c47
    mul_pp r9.xyz, r7.w, r9
    mad_pp r4.yzw, r2.y, r9.xxyz, r4
    add r3.y, -c52.z, c52.w
    rcp r3.y, r3.y
    add r9.xyz, -c50, v2
    dp3 r3.z, r9, r9
    rsq r3.z, r3.z
    rcp r5.z, r3.z
    mul_pp r9.xyz, r3.z, r9
    add r3.z, r5.z, -c52.z
    mul_sat r3.y, r3.y, r3.z
    add_pp r3.y, -r3.y, c3.y
    mad_pp r10.xyz, r7, r2.x, -r9
    dp3_pp r3.z, r8, -r9
    nrm_pp r9.xyz, r10
    dp3_sat_pp r5.z, r9, r8
    pow r7.w, r5.z, r5.x
    mul_pp r9.xyz, r5.y, c51
    mul_pp r9.xyz, r7.w, r9
    mad_pp r4.yzw, r3.y, r9.xxyz, r4
    mad_pp r9.xyz, r7, r2.x, -c10
    mad_pp r7.xyz, r7, r2.x, -r0.yzww
    dp3_pp r0.y, r8, -r0.yzww
    nrm_pp r10.xyz, r7
    dp3_sat_pp r0.z, r10, r8
    pow r2.x, r0.z, r5.x
    nrm_pp r7.xyz, r9
    dp3_sat_pp r0.z, r7, r8
    dp3_pp r0.w, r8, -c10
    pow r7.x, r0.z, r5.x
    mul_pp r5.xzw, r5.y, c37.xyyz
    mul_pp r5.xzw, r7.x, r5
    mad_pp r4.yzw, r5.xxzw, r1.w, r4
    mul_pp r5.xzw, c59.w, c59.xyyz
    mul_pp r5.xyz, r5.y, r5.xzww
    mul_pp r5.xyz, r2.x, r5
    mad_pp r4.yzw, r0.x, r5.xxyz, r4
    mul_pp r4.yzw, r4, c18.xxyz
    mul_pp r4.yzw, r4, v3.w
    mul_pp r5.xyz, r1, r1
    dp3_pp r0.z, r5, c0
    mad_pp r1.xyz, r1, r1, -r0.z
    mad_sat_pp r1.xyz, r1, c71.w, r0.z
    mul_pp r1.xyz, r1, c70
    mul_pp r5.xyz, r3.w, c43
    cmp_pp r5.xyz, r3.w, r5, c3.x
    mul_pp r5.xyz, r2.w, r5
    mul_pp r7.xyz, r4.x, c39
    cmp_pp r7.xyz, r4.x, r7, c3.x
    mad_pp r2.xzw, r2.z, r7.xyyz, r5.xyyz
    mul_pp r5.xyz, r3.x, c47
    cmp_pp r5.xyz, r3.x, r5, c3.x
    mad_pp r2.xyz, r2.y, r5, r2.xzww
    mul_pp r5.xyz, r3.z, c51
    cmp_pp r3.xzw, r3.z, r5.xyyz, c3.x
    mad_pp r2.xyz, r3.y, r3.xzww, r2
    mul r3.xyz, r0.w, c36
    mul_pp r3.xyz, r1.w, r3
    cmp_pp r3.xyz, r0.w, r3, c3.x
    add_pp r2.xyz, r2, r3
    mul_pp r3.xyz, c58.w, c58
    mul_pp r3.xyz, r0.y, r3
    cmp_pp r0.yzw, r0.y, r3.xxyz, c3.x
    mad_pp r0.xyz, r0.x, r0.yzww, r2
    mad_pp r0.xyz, r1, c17, r0
    mul_pp r0.xyz, r0, c16
    cmp r1.xy, -r6_abs.x, v0, c3.x
    cmp r1.xy, -r6_abs.y, v0.zwzw, r1
    cmp r1.xy, -r6_abs.z, v1, r1
    cmp r1.xy, -r6_abs.w, v1.zwzw, r1
    texld_pp r1, r1, s0
    mad_pp r0.xyz, r0, r1, r4.yzww
    mul_pp r0.w, r1.w, c16.w
    mul_pp r0, r0, c89
    min_pp r1, r0, c2.z
    mul_pp r0.xyz, c75, v6.y
    mad_pp oC0.xyz, r1, v6.x, r0
    mov_pp oC0.w, r1.w

// approximately 242 instruction slots used (5 texture, 237 arithmetic)
