//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   float4 g_GI0Scale;
//   float4 g_GI1Scale;
//   sampler2D g_GISampler;
//   float4 g_LightScatteringColor;
//   float4 g_PowerGlossLevel;
//   float4 g_ShadowMapParams;
//   sampler2D g_ShadowMapSampler;
//   float4 g_Specular;
//   sampler2D g_VerticalShadowMapSampler;
//   float4 mrgEyeLight_Attribute;
//   float4 mrgEyeLight_Diffuse;
//   float4 mrgEyeLight_Range;
//   float4 mrgEyeLight_Specular;
//   float4 mrgGlobalLight_Diffuse;
//   float4 mrgGlobalLight_Direction;
//   float4 mrgGlobalLight_Specular;
//   float4 mrgTexcoordIndex[4];
//   sampler2D sampDif;
//   sampler2D sampNrm;
//
//
// Registers:
//
//   Name                       Reg   Size
//   -------------------------- ----- ----
//   mrgGlobalLight_Direction   c10      1
//   g_Diffuse                  c16      1
//   g_Ambient                  c17      1
//   g_Specular                 c18      1
//   g_PowerGlossLevel          c20      1
//   g_EyePosition              c22      1
//   g_EyeDirection             c23      1
//   mrgTexcoordIndex           c26      1
//   mrgGlobalLight_Diffuse     c36      1
//   mrgGlobalLight_Specular    c37      1
//   mrgEyeLight_Diffuse        c58      1
//   mrgEyeLight_Specular       c59      1
//   mrgEyeLight_Range          c60      1
//   mrgEyeLight_Attribute      c61      1
//   g_ShadowMapParams          c65      1
//   g_GI0Scale                 c70      1
//   g_GI1Scale                 c71      1
//   g_LightScatteringColor     c75      1
//   g_ForceAlphaColor          c89      1
//   sampDif                    s0       1
//   sampNrm                    s2       1
//   g_VerticalShadowMapSampler s7       1
//   g_GISampler                s10      1
//   g_ShadowMapSampler         s13      1
//

    ps_3_0
    def c0, 0.298900008, 0.586600006, 0.114399999, 1024
    def c1, 500, 5, 4, 0
    def c2, 2, -1, -2, 3
    def c3, 0, 1, 2, 3
    dcl_texcoord v0
    dcl_texcoord1 v1
    dcl_texcoord2 v2.xyz
    dcl_texcoord3_pp v3
    dcl_texcoord4 v4
    dcl_texcoord6 v5
    dcl_texcoord5_pp v6.xyz
    dcl_texcoord7 v7.xyz
    dcl_texcoord8 v8.xyz
    dcl_color_pp v9.x
    dcl_2d s0
    dcl_2d s2
    dcl_2d s7
    dcl_2d s10
    dcl_2d s13
    max r0.x, v4.z, c3.x
    add r0.y, r0.x, -v4.w
    cmp r0.z, r0.y, c3.x, r0.x
    mov r0.xyw, v4
    texldp_pp r0, r0, s13
    max r0.y, v5.z, c3.x
    add r0.z, r0.y, -v5.w
    cmp r1.z, r0.z, c3.x, r0.y
    mov r1.xyw, v5
    texldp_pp r1, r1, s7
    min_pp r2.x, r1.x, r0.x
    lrp_pp r0.x, v6.z, c3.y, r2.x
    rcp r0.y, v4.w
    mul r0.yz, r0.y, v4.xxyw
    mad r0.yz, r0, c2.x, c2.y
    abs_sat r0.yz, r0
    add_sat r0.yz, r0, -c65.x
    mul r0.yz, r0, c65.y
    max r1.x, r0.y, r0.z
    lrp_pp r2.x, r1.x, c3.y, r0.x
    texld_pp r0, v0.zwzw, s10
    mul_pp r0.w, r2.x, r0.w
    frc r1.xy, c26.wxzw
    cmp r1.zw, -r1.xyxy, c3.x, c3.y
    add r1.xy, -r1, c26.wxzw
    mov r2.xy, c3
    cmp r1.zw, c26.xywx, r2.x, r1
    add r1.xy, r1.zwzw, r1
    add r3, r1.x, -c3
    add r1, r1.y, -c3
    cmp r2.xz, -r3_abs.x, v0.xyyw, c3.x
    cmp r2.xz, -r3_abs.y, v0.zyww, r2
    cmp r2.xz, -r3_abs.z, v1.xyyw, r2
    cmp r2.xz, -r3_abs.w, v1.zyww, r2
    texld_pp r3, r2.xzzw, s2
    mul_pp r3.x, r3.w, r3.x
    mad_pp r2.xz, r3.xyyw, c2.x, c2.y
    nrm_pp r3.xyz, v8
    mul_pp r3.xyz, r2.z, r3
    nrm_pp r4.xyz, v7
    mad_pp r3.xyz, r2.x, r4, r3
    dp2add_pp r2.x, r2.xzzw, -r2.xzzw, c3.y
    rsq_pp r2.x, r2.x
    rcp_pp r2.x, r2.x
    dp3 r2.z, v3, v3
    rsq r2.z, r2.z
    mul r4.xyz, r2.z, v3
    mad_pp r3.xyz, r2.x, r4, r3
    mad r2.xzw, v3.xyyz, r2.z, -r3.xyyz
    mad r2.xzw, v9.x, r2, r3.xyyz
    nrm_pp r3.xyz, r2.xzww
    dp3_pp r2.x, r3, -c10
    mul r4.xyz, r2.x, c36
    mul_pp r4.xyz, r0.w, r4
    cmp_pp r2.xzw, r2.x, r4.xyyz, c3.x
    add_pp r3.w, -c61.z, c61.y
    rcp_pp r3.w, r3.w
    add r4.xyz, -c22, v2
    dp3 r4.w, r4, r4
    rsq r4.w, r4.w
    mul_pp r4.xyz, r4.w, r4
    rcp r4.w, r4.w
    add r4.w, r4.w, -c60.z
    dp3_pp r5.x, r4, c23
    add_pp r5.x, r5.x, -c61.z
    mul_sat_pp r3.w, r3.w, r5.x
    mad_pp r5.x, r3.w, c2.z, c2.w
    mul_pp r3.w, r3.w, r3.w
    mul_pp r3.w, r3.w, r5.x
    pow_sat_pp r5.x, r3.w, c61.w
    add r3.w, r2.y, -c61.x
    cmp_pp r3.w, r3.w, c3.y, r5.x
    add r5.x, -c60.z, c60.w
    rcp r5.x, r5.x
    mul_sat r4.w, r4.w, r5.x
    add_pp r4.w, -r4.w, c3.y
    cmp_pp r2.y, -c61.x, r2.y, r4.w
    mul_pp r2.y, r3.w, r2.y
    dp3_pp r3.w, r3, -r4
    mul_pp r5.xyz, c58.w, c58
    mul_pp r5.xyz, r3.w, r5
    cmp_pp r5.xyz, r3.w, r5, c3.x
    mad_pp r2.xzw, r2.y, r5.xyyz, r2
    mul_pp r5.xyz, r0, r0
    dp3_pp r3.w, r5, c0
    mad_pp r0.xyz, r0, r0, -r3.w
    mad_sat_pp r0.xyz, r0, c71.w, r3.w
    mul_pp r0.xyz, r0, c70
    mad_pp r0.xyz, r0, c17, r2.xzww
    mul_pp r0.xyz, r0, c16
    add_pp r2.xzw, c22.xyyz, -v2.xyyz
    dp3_pp r3.w, r2.xzww, r2.xzww
    rsq_pp r3.w, r3.w
    mad_pp r4.xyz, r2.xzww, r3.w, -r4
    mad_pp r2.xzw, r2, r3.w, -c10.xyyz
    nrm_pp r5.xyz, r2.xzww
    dp3_sat_pp r2.x, r5, r3
    nrm_pp r5.xyz, r4
    dp3_sat_pp r2.z, r5, r3
    mov_pp r3.xy, c1
    mul_pp r3.xy, r3, c20.yzzw
    max_pp r2.w, r3.x, c3.y
    min r3.x, r2.w, c0.w
    pow r4.x, r2.z, r3.x
    pow r4.y, r2.x, r3.x
    mul_pp r2.xzw, c59.w, c59.xyyz
    mul_pp r2.xzw, r3.y, r2
    mul_pp r3.xyz, r3.y, c37
    mul_pp r3.xyz, r4.y, r3
    mul_pp r2.xzw, r4.x, r2
    mul_pp r2.xyz, r2.xzww, r2.y
    mad_pp r2.xyz, r3, r0.w, r2
    mul_pp r2.xyz, r2, c18
    mul_pp r2.xyz, r2, v3.w
    cmp r3.xy, -r1_abs.x, v0, c3.x
    cmp r1.xy, -r1_abs.y, v0.zwzw, r3
    cmp r1.xy, -r1_abs.z, v1, r1
    cmp r1.xy, -r1_abs.w, v1.zwzw, r1
    texld_pp r1, r1, s0
    mad_pp r0.xyz, r0, r1, r2
    mul_pp r0.w, r1.w, c16.w
    mul_pp r0, r0, c89
    min_pp r1, r0, c1.z
    mul_pp r0.xyz, c75, v6.y
    mad_pp oC0.xyz, r1, v6.x, r0
    mov_pp oC0.w, r1.w

// approximately 143 instruction slots used (5 texture, 138 arithmetic)
