//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   float4 g_GI0Scale;
//   float4 g_LightScatteringColor;
//   float4 g_PowerGlossLevel;
//   float4 g_ShadowMapParams;
//   sampler2D g_ShadowMapSampler;
//   float4 g_Specular;
//   sampler2D g_VerticalShadowMapSampler;
//   float4 g_aLightField[6];
//   float4 mrgEyeLight_Attribute;
//   float4 mrgEyeLight_Diffuse;
//   float4 mrgEyeLight_Range;
//   float4 mrgEyeLight_Specular;
//   float4 mrgGlobalLight_Diffuse;
//   float4 mrgGlobalLight_Direction;
//   float4 mrgGlobalLight_Specular;
//   float4 mrgLocalLight0_Color;
//   float4 mrgLocalLight0_Position;
//   float4 mrgLocalLight0_Range;
//   float4 mrgLocalLight1_Color;
//   float4 mrgLocalLight1_Position;
//   float4 mrgLocalLight1_Range;
//   float4 mrgLocalLight2_Color;
//   float4 mrgLocalLight2_Position;
//   float4 mrgLocalLight2_Range;
//   float4 mrgLocalLight3_Color;
//   float4 mrgLocalLight3_Position;
//   float4 mrgLocalLight3_Range;
//   sampler2D sampDif0;
//   sampler2D sampDif1;
//   sampler2D sampNrm0;
//   sampler2D sampNrm1;
//   sampler2D sampPower0;
//   sampler2D sampPower1;
//
//
// Registers:
//
//   Name                       Reg   Size
//   -------------------------- ----- ----
//   mrgGlobalLight_Direction   c10      1
//   g_Diffuse                  c16      1
//   g_Ambient                  c17      1
//   g_Specular                 c18      1
//   g_PowerGlossLevel          c20      1
//   g_EyePosition              c22      1
//   g_EyeDirection             c23      1
//   mrgGlobalLight_Diffuse     c36      1
//   mrgGlobalLight_Specular    c37      1
//   mrgLocalLight0_Position    c38      1
//   mrgLocalLight0_Color       c39      1
//   mrgLocalLight0_Range       c40      1
//   mrgLocalLight1_Position    c42      1
//   mrgLocalLight1_Color       c43      1
//   mrgLocalLight1_Range       c44      1
//   mrgLocalLight2_Position    c46      1
//   mrgLocalLight2_Color       c47      1
//   mrgLocalLight2_Range       c48      1
//   mrgLocalLight3_Position    c50      1
//   mrgLocalLight3_Color       c51      1
//   mrgLocalLight3_Range       c52      1
//   mrgEyeLight_Diffuse        c58      1
//   mrgEyeLight_Specular       c59      1
//   mrgEyeLight_Range          c60      1
//   mrgEyeLight_Attribute      c61      1
//   g_ShadowMapParams          c65      1
//   g_GI0Scale                 c70      1
//   g_LightScatteringColor     c75      1
//   g_aLightField              c77      6
//   g_ForceAlphaColor          c89      1
//   sampDif0                   s0       1
//   sampDif1                   s1       1
//   sampPower0                 s2       1
//   sampPower1                 s3       1
//   sampNrm0                   s4       1
//   sampNrm1                   s5       1
//   g_VerticalShadowMapSampler s7       1
//   g_ShadowMapSampler         s13      1
//

    ps_3_0
    def c0, 2, -1, 1, 0.5
    def c1, 0, -2, 3, 1024
    def c2, 500, 5, 4, 0
    dcl_texcoord v0.xy
    dcl_texcoord2 v1.xyz
    dcl_texcoord3_pp v2
    dcl_texcoord4 v3
    dcl_texcoord6 v4
    dcl_texcoord5_pp v5.xyz
    dcl_texcoord7 v6.xyz
    dcl_texcoord8 v7.xyz
    dcl_color_pp v8.xw
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s5
    dcl_2d s7
    dcl_2d s13
    add_pp r0.x, -c61.z, c61.y
    rcp_pp r0.x, r0.x
    add r0.yzw, -c22.xxyz, v1.xxyz
    dp3 r1.x, r0.yzww, r0.yzww
    rsq r1.x, r1.x
    mul_pp r0.yzw, r0, r1.x
    rcp r1.x, r1.x
    add r1.x, r1.x, -c60.z
    dp3_pp r1.y, r0.yzww, c23
    add_pp r1.y, r1.y, -c61.z
    mul_sat_pp r0.x, r0.x, r1.y
    mad_pp r1.y, r0.x, c1.y, c1.z
    mul_pp r0.x, r0.x, r0.x
    mul_pp r0.x, r0.x, r1.y
    pow_sat_pp r1.y, r0.x, c61.w
    mov_pp r1.z, c0.z
    add r0.x, r1.z, -c61.x
    cmp_pp r0.x, r0.x, c0.z, r1.y
    add r1.y, -c60.z, c60.w
    rcp r1.y, r1.y
    mul_sat r1.x, r1.y, r1.x
    add_pp r1.x, -r1.x, c0.z
    cmp_pp r1.x, -c61.x, r1.z, r1.x
    mul_pp r0.x, r0.x, r1.x
    add r1.x, -c40.z, c40.w
    rcp r1.x, r1.x
    add r1.yzw, -c38.xxyz, v1.xxyz
    dp3 r2.x, r1.yzww, r1.yzww
    rsq r2.x, r2.x
    rcp r2.y, r2.x
    mul_pp r1.yzw, r1, r2.x
    add r2.x, r2.y, -c40.z
    mul_sat r1.x, r1.x, r2.x
    add_pp r1.x, -r1.x, c0.z
    add r2.x, -c44.z, c44.w
    rcp r2.x, r2.x
    add r2.yzw, -c42.xxyz, v1.xxyz
    dp3 r3.x, r2.yzww, r2.yzww
    rsq r3.x, r3.x
    rcp r3.y, r3.x
    mul_pp r2.yzw, r2, r3.x
    add r3.x, r3.y, -c44.z
    mul_sat r2.x, r2.x, r3.x
    add_pp r2.x, -r2.x, c0.z
    nrm_pp r3.xyz, v7
    texld_pp r4, v0, s4
    texld_pp r5, v0, s5
    lrp_pp r6.yzw, v8.x, r5.xxyw, r4.xxyw
    mul_pp r6.x, r6.w, r6.y
    mad_pp r4.xy, r6.xzzw, c0.x, c0.y
    mul_pp r3.xyz, r3, r4.y
    nrm_pp r5.xyz, v6
    mad_pp r3.xyz, r4.x, r5, r3
    dp2add_pp r3.w, r4, -r4, c0.z
    rsq_pp r3.w, r3.w
    rcp_pp r3.w, r3.w
    nrm_pp r4.xyz, v2
    mad_pp r3.xyz, r3.w, r4, r3
    dp3_pp r3.w, r3, -r2.yzww
    mul_pp r4.xyz, r3.w, c43
    cmp_pp r4.xyz, r3.w, r4, c1.x
    mul_pp r4.xyz, r2.x, r4
    dp3_pp r3.w, r3, -r1.yzww
    mul_pp r5.xyz, r3.w, c39
    cmp_pp r5.xyz, r3.w, r5, c1.x
    mad_pp r4.xyz, r1.x, r5, r4
    add r3.w, -c48.z, c48.w
    rcp r3.w, r3.w
    add r5.xyz, -c46, v1
    dp3 r4.w, r5, r5
    rsq r4.w, r4.w
    rcp r5.w, r4.w
    mul_pp r5.xyz, r4.w, r5
    add r4.w, r5.w, -c48.z
    mul_sat r3.w, r3.w, r4.w
    add_pp r3.w, -r3.w, c0.z
    dp3_pp r4.w, r3, -r5
    mul_pp r6.xyz, r4.w, c47
    cmp_pp r6.xyz, r4.w, r6, c1.x
    mad_pp r4.xyz, r3.w, r6, r4
    add r4.w, -c52.z, c52.w
    rcp r4.w, r4.w
    add r6.xyz, -c50, v1
    dp3 r5.w, r6, r6
    rsq r5.w, r5.w
    rcp r6.w, r5.w
    mul_pp r6.xyz, r5.w, r6
    add r5.w, r6.w, -c52.z
    mul_sat r4.w, r4.w, r5.w
    add_pp r4.w, -r4.w, c0.z
    dp3_pp r5.w, r3, -r6
    mul_pp r7.xyz, r5.w, c51
    cmp_pp r7.xyz, r5.w, r7, c1.x
    mad_pp r4.xyz, r4.w, r7, r4
    max r5.w, v3.z, c1.x
    add r6.w, r5.w, -v3.w
    cmp r7.z, r6.w, c1.x, r5.w
    mov r7.xyw, v3
    texldp_pp r7, r7, s13
    max r5.w, v4.z, c1.x
    add r6.w, r5.w, -v4.w
    cmp r8.z, r6.w, c1.x, r5.w
    mov r8.xyw, v4
    texldp_pp r8, r8, s7
    min_pp r5.w, r8.x, r7.x
    lrp_pp r6.w, v5.z, c0.z, r8.x
    lrp_pp r7.x, v5.z, c0.z, r5.w
    rcp r5.w, v3.w
    mul r7.yz, r5.w, v3.xxyw
    mad r7.yz, r7, c0.x, c0.y
    abs_sat r7.yz, r7
    add_sat r7.yz, r7, -c65.x
    mul r7.yz, r7, c65.y
    max r5.w, r7.y, r7.z
    lrp_pp r8.x, r5.w, c0.z, r7.x
    lrp_pp r7.x, r5.w, c0.z, r6.w
    mul_pp r5.w, r8.x, c77.w
    dp3_pp r6.w, r3, -c10
    mul r7.yzw, r6.w, c36.xxyz
    mul_pp r7.yzw, r5.w, r7
    cmp_pp r7.yzw, r6.w, r7, c1.x
    add_pp r4.xyz, r4, r7.yzww
    dp3_pp r6.w, r3, -r0.yzww
    mul_pp r7.yzw, c58.w, c58.xxyz
    mul_pp r7.yzw, r6.w, r7
    cmp_pp r7.yzw, r6.w, r7, c1.x
    mad_pp r4.xyz, r0.x, r7.yzww, r4
    mov r8.xyz, c79
    add r7.yzw, -r8.xxyz, c80.xxyz
    mad_pp r8.xyz, r3, c0.w, c0.w
    mad r7.yzw, r8.y, r7, c79.xxyz
    mul_pp r9.xyz, r3, r3
    mul r7.yzw, r7, r9.y
    mov r10.xyz, c77
    add r10.xyz, -r10, c78
    mad r8.xyw, r8.x, r10.xyzz, c77.xyzz
    mad_pp r7.yzw, r9.x, r8.xxyw, r7
    mov r10.xyz, c81
    add r8.xyw, -r10.xyzz, c82.xyzz
    mad r8.xyz, r8.z, r8.xyww, c81
    mad_pp r7.yzw, r9.z, r8.xxyz, r7
    mul_pp r8.xyz, r7.yzww, c17
    mul r8.xyz, r8, c70.w
    mad r7.yzw, r7, c17.xxyz, -r8.xxyz
    mad_pp r7.xyz, r7.x, r7.yzww, r8
    add_pp r4.xyz, r4, r7
    mul_pp r4.xyz, r4, c16
    add_pp r7.xyz, c22, -v1
    dp3_pp r6.w, r7, r7
    rsq_pp r6.w, r6.w
    mad_pp r2.yzw, r7.xxyz, r6.w, -r2
    nrm_pp r8.xyz, r2.yzww
    dp3_sat_pp r2.y, r8, r3
    texld_pp r8, v0, s2
    texld_pp r9, v0, s3
    lrp_pp r2.z, v8.x, r9.x, r8.x
    mul_pp r2.zw, r2.z, c20.xyyz
    mul_pp r2.zw, r2, c2.xyxy
    max_pp r7.w, r2.z, c0.z
    min r2.z, r7.w, c1.w
    pow r7.w, r2.y, r2.z
    mul_pp r8.xyz, r2.w, c43
    mul_pp r8.xyz, r7.w, r8
    mul_pp r8.xyz, r2.x, r8
    mad_pp r1.yzw, r7.xxyz, r6.w, -r1
    nrm_pp r9.xyz, r1.yzww
    dp3_sat_pp r1.y, r9, r3
    pow r7.w, r1.y, r2.z
    mul_pp r1.yzw, r2.w, c39.xxyz
    mul_pp r1.yzw, r7.w, r1
    mad_pp r1.xyz, r1.x, r1.yzww, r8
    mad_pp r5.xyz, r7, r6.w, -r5
    nrm_pp r8.xyz, r5
    dp3_sat_pp r1.w, r8, r3
    pow r5.x, r1.w, r2.z
    mul_pp r8.xyz, r2.w, c47
    mul_pp r5.xyz, r5.x, r8
    mad_pp r1.xyz, r3.w, r5, r1
    mad_pp r5.xyz, r7, r6.w, -r6
    nrm_pp r6.xyz, r5
    dp3_sat_pp r1.w, r6, r3
    pow r3.w, r1.w, r2.z
    mul_pp r5.xyz, r2.w, c51
    mul_pp r5.xyz, r3.w, r5
    mad_pp r1.xyz, r4.w, r5, r1
    mad_pp r5.xyz, r7, r6.w, -c10
    mad_pp r0.yzw, r7.xxyz, r6.w, -r0
    nrm_pp r6.xyz, r0.yzww
    dp3_sat_pp r0.y, r6, r3
    pow r1.w, r0.y, r2.z
    nrm_pp r6.xyz, r5
    dp3_sat_pp r0.y, r6, r3
    pow r3.x, r0.y, r2.z
    mul_pp r0.yzw, r2.w, c37.xxyz
    mul_pp r0.yzw, r3.x, r0
    mad_pp r0.yzw, r0, r5.w, r1.xxyz
    mul_pp r1.xyz, c59.w, c59
    mul_pp r1.xyz, r2.w, r1
    mul_pp r1.xyz, r1.w, r1
    mad_pp r0.xyz, r0.x, r1, r0.yzww
    mul_pp r0.xyz, r0, c18
    mul_pp r0.xyz, r0, v2.w
    texld_pp r1, v0, s0
    texld_pp r2, v0, s1
    lrp_pp r3, v8.x, r2, r1
    mad_pp r0.xyz, r4, r3, r0
    mul_pp r1.x, r3.w, c16.w
    mul_pp r0.w, r1.x, v8.w
    mul_pp r0, r0, c89
    min_pp r1, r0, c2.z
    mul_pp r0.xyz, c75, v5.y
    mad_pp oC0.xyz, r1, v5.x, r0
    mov_pp oC0.w, r1.w

// approximately 246 instruction slots used (8 texture, 238 arithmetic)
