//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   float4 g_GI0Scale;
//   float4 g_LightScatteringColor;
//   float4 g_PowerGlossLevel;
//   float4 g_ShadowMapParams;
//   sampler2D g_ShadowMapSampler;
//   float4 g_Specular;
//   sampler2D g_VerticalShadowMapSampler;
//   float4 g_aLightField[6];
//   float4 mrgEyeLight_Attribute;
//   float4 mrgEyeLight_Diffuse;
//   float4 mrgEyeLight_Range;
//   float4 mrgEyeLight_Specular;
//   float4 mrgGlobalLight_Diffuse;
//   float4 mrgGlobalLight_Direction;
//   float4 mrgGlobalLight_Specular;
//   float4 mrgLocalLight0_Color;
//   float4 mrgLocalLight0_Position;
//   float4 mrgLocalLight0_Range;
//   float4 mrgLocalLight1_Color;
//   float4 mrgLocalLight1_Position;
//   float4 mrgLocalLight1_Range;
//   float4 mrgLocalLight2_Color;
//   float4 mrgLocalLight2_Position;
//   float4 mrgLocalLight2_Range;
//   float4 mrgLocalLight3_Color;
//   float4 mrgLocalLight3_Position;
//   float4 mrgLocalLight3_Range;
//   float4 mrgTexcoordIndex[4];
//   sampler2D sampDif0;
//   sampler2D sampDif1;
//   sampler2D sampNrm0;
//   sampler2D sampNrm1;
//   sampler2D sampPower0;
//   sampler2D sampPower1;
//
//
// Registers:
//
//   Name                       Reg   Size
//   -------------------------- ----- ----
//   mrgGlobalLight_Direction   c10      1
//   g_Diffuse                  c16      1
//   g_Ambient                  c17      1
//   g_Specular                 c18      1
//   g_PowerGlossLevel          c20      1
//   g_EyePosition              c22      1
//   g_EyeDirection             c23      1
//   mrgTexcoordIndex           c26      2
//   mrgGlobalLight_Diffuse     c36      1
//   mrgGlobalLight_Specular    c37      1
//   mrgLocalLight0_Position    c38      1
//   mrgLocalLight0_Color       c39      1
//   mrgLocalLight0_Range       c40      1
//   mrgLocalLight1_Position    c42      1
//   mrgLocalLight1_Color       c43      1
//   mrgLocalLight1_Range       c44      1
//   mrgLocalLight2_Position    c46      1
//   mrgLocalLight2_Color       c47      1
//   mrgLocalLight2_Range       c48      1
//   mrgLocalLight3_Position    c50      1
//   mrgLocalLight3_Color       c51      1
//   mrgLocalLight3_Range       c52      1
//   mrgEyeLight_Diffuse        c58      1
//   mrgEyeLight_Specular       c59      1
//   mrgEyeLight_Range          c60      1
//   mrgEyeLight_Attribute      c61      1
//   g_ShadowMapParams          c65      1
//   g_GI0Scale                 c70      1
//   g_LightScatteringColor     c75      1
//   g_aLightField              c77      6
//   g_ForceAlphaColor          c89      1
//   sampDif0                   s0       1
//   sampDif1                   s1       1
//   sampPower0                 s2       1
//   sampPower1                 s3       1
//   sampNrm0                   s4       1
//   sampNrm1                   s5       1
//   g_VerticalShadowMapSampler s7       1
//   g_ShadowMapSampler         s13      1
//

    ps_3_0
    def c0, 2, -1, 0.5, -3
    def c1, 500, 5, 1024, 4
    def c2, 0, 1, 2, 3
    dcl_texcoord v0
    dcl_texcoord1 v1
    dcl_texcoord2 v2.xyz
    dcl_texcoord3_pp v3
    dcl_texcoord4 v4
    dcl_texcoord6 v5
    dcl_texcoord5_pp v6.xyz
    dcl_texcoord7 v7.xyz
    dcl_texcoord8 v8.xyz
    dcl_color_pp v9.xw
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s5
    dcl_2d s7
    dcl_2d s13
    add_pp r0.x, -c61.z, c61.y
    rcp_pp r0.x, r0.x
    add r0.yzw, -c22.xxyz, v2.xxyz
    dp3 r1.x, r0.yzww, r0.yzww
    rsq r1.x, r1.x
    mul_pp r0.yzw, r0, r1.x
    rcp r1.x, r1.x
    add r1.x, r1.x, -c60.z
    dp3_pp r1.y, r0.yzww, c23
    add_pp r1.y, r1.y, -c61.z
    mul_sat_pp r0.x, r0.x, r1.y
    mad_pp r1.y, r0.x, -c0.x, -c0.w
    mul_pp r0.x, r0.x, r0.x
    mul_pp r0.x, r0.x, r1.y
    pow_sat_pp r1.y, r0.x, c61.w
    mov r2.xy, c2
    add r0.x, r2.y, -c61.x
    cmp_pp r0.x, r0.x, c2.y, r1.y
    add r1.y, -c60.z, c60.w
    rcp r1.y, r1.y
    mul_sat r1.x, r1.y, r1.x
    add_pp r1.x, -r1.x, c2.y
    cmp_pp r1.x, -c61.x, r2.y, r1.x
    mul_pp r0.x, r0.x, r1.x
    add r1.x, -c44.z, c44.w
    rcp r1.x, r1.x
    add r1.yzw, -c42.xxyz, v2.xxyz
    dp3 r2.y, r1.yzww, r1.yzww
    rsq r2.y, r2.y
    rcp r2.z, r2.y
    mul_pp r1.yzw, r1, r2.y
    add r2.y, r2.z, -c44.z
    mul_sat r1.x, r1.x, r2.y
    add_pp r1.x, -r1.x, c2.y
    frc r2.yz, c27.xxyw
    cmp r3.xy, -r2.yzzw, c2.x, c2.y
    add r2.yz, -r2, c27.xxyw
    cmp r3.xy, c27, r2.x, r3
    add r2.yz, r2, r3.xxyw
    add r3, r2.y, -c2
    add r4, r2.z, -c2
    cmp r2.yz, -r3_abs.x, v0.xxyw, c2.x
    cmp r2.yz, -r3_abs.y, v0.xzww, r2
    cmp r2.yz, -r3_abs.z, v1.xxyw, r2
    cmp r2.yz, -r3_abs.w, v1.xzww, r2
    texld_pp r3, r2.yzzw, s4
    cmp r2.yz, -r4_abs.x, v0.xxyw, c2.x
    cmp r2.yz, -r4_abs.y, v0.xzww, r2
    cmp r2.yz, -r4_abs.z, v1.xxyw, r2
    cmp r2.yz, -r4_abs.w, v1.xzww, r2
    texld_pp r4, r2.yzzw, s5
    lrp_pp r5.yzw, v9.x, r4.xxyw, r3.xxyw
    mul_pp r5.x, r5.w, r5.y
    mad_pp r2.yz, r5.xxzw, c0.x, c0.y
    nrm_pp r3.xyz, v8
    mul_pp r3.xyz, r2.z, r3
    nrm_pp r4.xyz, v7
    mad_pp r3.xyz, r2.y, r4, r3
    dp2add_pp r2.y, r2.yzzw, -r2.yzzw, c2.y
    rsq_pp r2.y, r2.y
    rcp_pp r2.y, r2.y
    nrm_pp r4.xyz, v3
    mad_pp r2.yzw, r2.y, r4.xxyz, r3.xxyz
    dp3_pp r3.x, r2.yzww, -r1.yzww
    mul_pp r3.yzw, r3.x, c43.xxyz
    cmp_pp r3.xyz, r3.x, r3.yzww, c2.x
    mul_pp r3.xyz, r1.x, r3
    add r3.w, -c40.z, c40.w
    rcp r3.w, r3.w
    add r4.xyz, -c38, v2
    dp3 r4.w, r4, r4
    rsq r4.w, r4.w
    rcp r5.x, r4.w
    mul_pp r4.xyz, r4.w, r4
    add r4.w, r5.x, -c40.z
    mul_sat r3.w, r3.w, r4.w
    add_pp r3.w, -r3.w, c2.y
    dp3_pp r4.w, r2.yzww, -r4
    mul_pp r5.xyz, r4.w, c39
    cmp_pp r5.xyz, r4.w, r5, c2.x
    mad_pp r3.xyz, r3.w, r5, r3
    add r4.w, -c48.z, c48.w
    rcp r4.w, r4.w
    add r5.xyz, -c46, v2
    dp3 r5.w, r5, r5
    rsq r5.w, r5.w
    rcp r6.x, r5.w
    mul_pp r5.xyz, r5.w, r5
    add r5.w, r6.x, -c48.z
    mul_sat r4.w, r4.w, r5.w
    add_pp r4.w, -r4.w, c2.y
    dp3_pp r5.w, r2.yzww, -r5
    mul_pp r6.xyz, r5.w, c47
    cmp_pp r6.xyz, r5.w, r6, c2.x
    mad_pp r3.xyz, r4.w, r6, r3
    add r5.w, -c52.z, c52.w
    rcp r5.w, r5.w
    add r6.xyz, -c50, v2
    dp3 r6.w, r6, r6
    rsq r6.w, r6.w
    rcp r7.x, r6.w
    mul_pp r6.xyz, r6.w, r6
    add r6.w, r7.x, -c52.z
    mul_sat r5.w, r5.w, r6.w
    add_pp r5.w, -r5.w, c2.y
    dp3_pp r6.w, r2.yzww, -r6
    mul_pp r7.xyz, r6.w, c51
    cmp_pp r7.xyz, r6.w, r7, c2.x
    mad_pp r3.xyz, r5.w, r7, r3
    max r6.w, v4.z, c2.x
    add r7.x, r6.w, -v4.w
    cmp r7.z, r7.x, c2.x, r6.w
    mov r7.xyw, v4
    texldp_pp r7, r7, s13
    max r6.w, v5.z, c2.x
    add r7.y, r6.w, -v5.w
    cmp r8.z, r7.y, c2.x, r6.w
    mov r8.xyw, v5
    texldp_pp r8, r8, s7
    min_pp r6.w, r8.x, r7.x
    lrp_pp r7.x, v6.z, c2.y, r8.x
    lrp_pp r7.y, v6.z, c2.y, r6.w
    rcp r6.w, v4.w
    mul r7.zw, r6.w, v4.xyxy
    mad r7.zw, r7, c0.x, c0.y
    abs_sat r7.zw, r7
    add_sat r7.zw, r7, -c65.x
    mul r7.zw, r7, c65.y
    max r6.w, r7.z, r7.w
    lrp_pp r8.x, r6.w, c2.y, r7.y
    lrp_pp r8.y, r6.w, c2.y, r7.x
    mul_pp r6.w, r8.x, c77.w
    dp3_pp r7.x, r2.yzww, -c10
    mul r7.yzw, r7.x, c36.xxyz
    mul_pp r7.yzw, r6.w, r7
    cmp_pp r7.xyz, r7.x, r7.yzww, c2.x
    add_pp r3.xyz, r3, r7
    dp3_pp r7.x, r2.yzww, -r0.yzww
    mul_pp r7.yzw, c58.w, c58.xxyz
    mul_pp r7.yzw, r7.x, r7
    cmp_pp r7.xyz, r7.x, r7.yzww, c2.x
    mad_pp r3.xyz, r0.x, r7, r3
    mad_pp r7.xyz, r2.yzww, c0.z, c0.z
    mov r9.xyz, c79
    add r8.xzw, -r9.xyyz, c80.xyyz
    mad r8.xzw, r7.y, r8, c79.xyyz
    mul_pp r9.xyz, r2.yzww, r2.yzww
    mul r8.xzw, r8, r9.y
    mov r10.xyz, c77
    add r10.xyz, -r10, c78
    mad r7.xyw, r7.x, r10.xyzz, c77.xyzz
    mad_pp r7.xyw, r9.x, r7, r8.xzzw
    mov r10.xyz, c81
    add r8.xzw, -r10.xyyz, c82.xyyz
    mad r8.xzw, r7.z, r8, c81.xyyz
    mad_pp r7.xyz, r9.z, r8.xzww, r7.xyww
    mul_pp r8.xzw, r7.xyyz, c17.xyyz
    mul r8.xzw, r8, c70.w
    mad r7.xyz, r7, c17, -r8.xzww
    mad_pp r7.xyz, r8.y, r7, r8.xzww
    add_pp r3.xyz, r3, r7
    mul_pp r3.xyz, r3, c16
    frc r7, c26
    cmp r8, -r7, c2.x, c2.y
    add r7, -r7, c26
    cmp r8, c26, r2.x, r8
    add r7, r7, r8
    add r8, r7.z, -c2
    cmp r9.xy, -r8_abs.x, v0, c2.x
    cmp r8.xy, -r8_abs.y, v0.zwzw, r9
    cmp r8.xy, -r8_abs.z, v1, r8
    cmp r8.xy, -r8_abs.w, v1.zwzw, r8
    texld_pp r8, r8, s2
    add r9, r7.w, -c2
    cmp r7.zw, -r9_abs.x, v0.xyxy, c2.x
    cmp r7.zw, -r9_abs.y, v0, r7
    cmp r7.zw, -r9_abs.z, v1.xyxy, r7
    cmp r7.zw, -r9_abs.w, v1, r7
    texld_pp r9, r7.zwzw, s3
    lrp_pp r2.x, v9.x, r9.x, r8.x
    mul_pp r7.zw, r2.x, c20.xyyz
    mul_pp r7.zw, r7, c1.xyxy
    mul_pp r8.xyz, r7.w, c43
    add_pp r9.xyz, c22, -v2
    dp3_pp r2.x, r9, r9
    rsq_pp r2.x, r2.x
    mad_pp r1.yzw, r9.xxyz, r2.x, -r1
    nrm_pp r10.xyz, r1.yzww
    dp3_sat_pp r1.y, r10, r2.yzww
    max_pp r1.z, r7.z, c2.y
    min r7.z, r1.z, c1.z
    pow r8.w, r1.y, r7.z
    mul_pp r1.yzw, r8.w, r8.xxyz
    mul_pp r1.xyz, r1.yzww, r1.x
    mul_pp r8.xyz, r7.w, c39
    mad_pp r4.xyz, r9, r2.x, -r4
    nrm_pp r10.xyz, r4
    dp3_sat_pp r1.w, r10, r2.yzww
    pow r4.x, r1.w, r7.z
    mul_pp r4.xyz, r4.x, r8
    mad_pp r1.xyz, r3.w, r4, r1
    mad_pp r4.xyz, r9, r2.x, -r5
    nrm_pp r5.xyz, r4
    dp3_sat_pp r1.w, r5, r2.yzww
    pow r3.w, r1.w, r7.z
    mul_pp r4.xyz, r7.w, c47
    mul_pp r4.xyz, r3.w, r4
    mad_pp r1.xyz, r4.w, r4, r1
    mad_pp r4.xyz, r9, r2.x, -r6
    nrm_pp r5.xyz, r4
    dp3_sat_pp r1.w, r5, r2.yzww
    pow r3.w, r1.w, r7.z
    mul_pp r4.xyz, r7.w, c51
    mul_pp r4.xyz, r3.w, r4
    mad_pp r1.xyz, r5.w, r4, r1
    mad_pp r4.xyz, r9, r2.x, -c10
    mad_pp r0.yzw, r9.xxyz, r2.x, -r0
    nrm_pp r5.xyz, r0.yzww
    dp3_sat_pp r0.y, r5, r2.yzww
    pow r1.w, r0.y, r7.z
    nrm_pp r5.xyz, r4
    dp3_sat_pp r0.y, r5, r2.yzww
    pow r2.x, r0.y, r7.z
    mul_pp r0.yzw, r7.w, c37.xxyz
    mul_pp r0.yzw, r2.x, r0
    mad_pp r0.yzw, r0, r6.w, r1.xxyz
    mul_pp r1.xyz, c59.w, c59
    mul_pp r1.xyz, r7.w, r1
    mul_pp r1.xyz, r1.w, r1
    mad_pp r0.xyz, r0.x, r1, r0.yzww
    mul_pp r0.xyz, r0, c18
    mul_pp r0.xyz, r0, v3.w
    add r1, r7.x, -c2
    add r2, r7.y, -c2
    cmp r4.xy, -r1_abs.x, v0, c2.x
    cmp r1.xy, -r1_abs.y, v0.zwzw, r4
    cmp r1.xy, -r1_abs.z, v1, r1
    cmp r1.xy, -r1_abs.w, v1.zwzw, r1
    texld_pp r1, r1, s0
    cmp r4.xy, -r2_abs.x, v0, c2.x
    cmp r2.xy, -r2_abs.y, v0.zwzw, r4
    cmp r2.xy, -r2_abs.z, v1, r2
    cmp r2.xy, -r2_abs.w, v1.zwzw, r2
    texld_pp r2, r2, s1
    lrp_pp r4, v9.x, r2, r1
    mad_pp r0.xyz, r3, r4, r0
    mul_pp r1.x, r4.w, c16.w
    mul_pp r0.w, r1.x, v9.w
    mul_pp r0, r0, c89
    min_pp r1, r0, c1.w
    mul_pp r0.xyz, c75, v6.y
    mad_pp oC0.xyz, r1, v6.x, r0
    mov_pp oC0.w, r1.w

// approximately 286 instruction slots used (8 texture, 278 arithmetic)
