//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   float4 g_GI0Scale;
//   float4 g_GI1Scale;
//   sampler2D g_GISampler;
//   float4 g_LightScatteringColor;
//   row_major float4x4 g_MtxView;
//   float4 g_OpacityReflectionRefractionSpectype;
//   float4 g_PowerGlossLevel;
//   float4 g_ShadowMapParams;
//   sampler2D g_ShadowMapSampler;
//   float4 g_Specular;
//   float4 g_ViewportSize;
//   float4 mrgEyeLight_Attribute;
//   float4 mrgEyeLight_Diffuse;
//   float4 mrgEyeLight_Range;
//   float4 mrgEyeLight_Specular;
//   float4 mrgGlobalLight_Diffuse;
//   float4 mrgGlobalLight_Direction;
//   float4 mrgGlobalLight_Specular;
//   float4 mrgInShadowScale;
//   float4 mrgLuminanceRange;
//   float4 mrgPlayableParam;
//   float4 mrgTexcoordIndex[4];
//   sampler2D sampDif;
//   sampler2D sampEnv;
//   sampler2D sampSpe;
//
//
// Registers:
//
//   Name                                  Reg   Size
//   ------------------------------------- ----- ----
//   mrgGlobalLight_Direction              c10      1
//   g_Diffuse                             c16      1
//   g_Ambient                             c17      1
//   g_Specular                            c18      1
//   g_PowerGlossLevel                     c20      1
//   g_OpacityReflectionRefractionSpectype c21      1
//   g_EyePosition                         c22      1
//   g_EyeDirection                        c23      1
//   g_ViewportSize                        c24      1
//   mrgTexcoordIndex                      c26      1
//   mrgGlobalLight_Diffuse                c36      1
//   mrgGlobalLight_Specular               c37      1
//   mrgEyeLight_Diffuse                   c58      1
//   mrgEyeLight_Specular                  c59      1
//   mrgEyeLight_Range                     c60      1
//   mrgEyeLight_Attribute                 c61      1
//   mrgLuminanceRange                     c63      1
//   mrgInShadowScale                      c64      1
//   g_ShadowMapParams                     c65      1
//   g_GI0Scale                            c70      1
//   g_GI1Scale                            c71      1
//   g_LightScatteringColor                c75      1
//   mrgPlayableParam                      c86      1
//   g_ForceAlphaColor                     c89      1
//   g_MtxView                             c90      3
//   sampDif                               s0       1
//   sampSpe                               s1       1
//   sampEnv                               s5       1
//   g_GISampler                           s10      1
//   g_ShadowMapSampler                    s13      1
//

    ps_3_0
    def c0, 0.5, 0.298900008, 0.586600006, 0.114399999
    def c1, 2, -1, -2, 3
    def c2, 500, 5, 1024, 4
    def c3, 0, 1, 2, 3
    def c4, 0.5, -0.5, 0, 0
    dcl_texcoord v0
    dcl_texcoord1 v1
    dcl_texcoord2 v2.xyz
    dcl_texcoord3_pp v3
    dcl_texcoord4 v4
    dcl_texcoord5_pp v5.xyz
    dcl_color_pp v6
    dcl vPos.y
    dcl_2d s0
    dcl_2d s1
    dcl_2d s5
    dcl_2d s10
    dcl_2d s13
    add_pp r0.x, -c61.z, c61.y
    rcp_pp r0.x, r0.x
    add r0.yzw, -c22.xxyz, v2.xxyz
    dp3 r1.x, r0.yzww, r0.yzww
    rsq r1.x, r1.x
    mul_pp r0.yzw, r0, r1.x
    rcp r1.x, r1.x
    add r1.x, r1.x, -c60.z
    dp3_pp r1.y, r0.yzww, c23
    add_pp r1.y, r1.y, -c61.z
    mul_sat_pp r0.x, r0.x, r1.y
    mad_pp r1.y, r0.x, c1.z, c1.w
    mul_pp r0.x, r0.x, r0.x
    mul_pp r0.x, r0.x, r1.y
    pow_sat_pp r1.y, r0.x, c61.w
    mov r2.xy, c3
    add r0.x, r2.y, -c61.x
    cmp_pp r0.x, r0.x, c3.y, r1.y
    add r1.y, -c60.z, c60.w
    rcp r1.y, r1.y
    mul_sat r1.x, r1.y, r1.x
    add_pp r1.x, -r1.x, c3.y
    cmp_pp r1.x, -c61.x, r2.y, r1.x
    mul_pp r0.x, r0.x, r1.x
    mul_pp r1.xyz, c59.w, c59
    mov_pp r3.xy, c2
    mul_pp r2.yz, r3.xxyw, c20
    mul_pp r1.xyz, r1, r2.z
    max_pp r1.w, r2.y, c3.y
    mul_pp r2.yzw, r2.z, c37.xxyz
    min r3.x, r1.w, c2.z
    add_pp r3.yzw, c22.xxyz, -v2.xxyz
    dp3_pp r1.w, r3.yzww, r3.yzww
    rsq_pp r1.w, r1.w
    mad_pp r4.xyz, r3.yzww, r1.w, -r0.yzww
    mad_pp r3.yzw, r3, r1.w, -c10.xxyz
    nrm_pp r5.xyz, r3.yzww
    nrm_pp r6.xyz, r4
    nrm_pp r4.xyz, v3
    dp3_sat_pp r1.w, r6, r4
    pow r4.w, r1.w, r3.x
    mul_pp r1.xyz, r1, r4.w
    mul_pp r1.xyz, r0.x, r1
    rcp r1.w, v4.w
    mul r3.yz, r1.w, v4.xxyw
    mad r3.yz, r3, c1.x, c1.y
    abs_sat r3.yz, r3
    add_sat r3.yz, r3, -c65.x
    mul r3.yz, r3, c65.y
    max r1.w, r3.y, r3.z
    max r3.y, v4.z, c3.x
    add r3.z, r3.y, -v4.w
    cmp r6.z, r3.z, c3.x, r3.y
    mov r6.xyw, v4
    texldp_pp r6, r6, s13
    lrp_pp r3.y, v5.z, c3.y, r6.x
    lrp_pp r4.w, r1.w, c3.y, r3.y
    texld_pp r6, v0.zwzw, s10
    mul r1.w, r4.w, r6.w
    dp3_sat_pp r3.y, r5, r4
    pow r5.x, r3.y, r3.x
    mul_pp r2.yzw, r2, r5.x
    mad_pp r1.xyz, r2.yzww, r1.w, r1
    mul r3, r4.y, c91
    mad r3, r4.x, c90, r3
    mad r3, r4.z, c92, r3
    dp4 r2.y, r3, r3
    rsq r2.y, r2.y
    mul r2.yz, r2.y, r3.xxyw
    mad_pp r2.yz, r2, c4.xxyw, c4.x
    texld_pp r3, r2.yzzw, s5
    mul r2.yzw, r3.xxyz, c63.x
    mad_pp r2.yzw, r2, r3.w, r3.xxyz
    frc r3.xy, c26.xzzw
    cmp r3.zw, -r3.xyxy, c3.x, c3.y
    add r3.xy, -r3, c26.xzzw
    cmp r3.zw, c26.xyxz, r2.x, r3
    add r3.xy, r3.zwzw, r3
    add r5, r3.y, -c3
    add r3, r3.x, -c3
    cmp r7.xy, -r5_abs.x, v0, c3.x
    cmp r5.xy, -r5_abs.y, v0.zwzw, r7
    cmp r5.xy, -r5_abs.z, v1, r5
    cmp r5.xy, -r5_abs.w, v1.zwzw, r5
    texld_pp r5, r5, s1
    mul_pp r2.xyz, r2.yzww, r5.w
    mul r2.w, c64.z, c64.x
    mov r7.xz, c64
    mad r5.w, r7.x, -r7.z, r7.z
    mad_pp r2.w, r1.w, r5.w, r2.w
    mul_pp r2.xyz, r2.w, r2
    mad_pp r1.xyz, r1, c18, r2
    mul_pp r1.xyz, r5, r1
    mul_pp r1.xyz, r1, v3.w
    mul_pp r2.xyz, r6, r6
    dp3_pp r2.x, r2, c0.yzww
    mad_pp r2.yzw, r6.xxyz, r6.xxyz, -r2.x
    mad_sat_pp r2.xyz, r2.yzww, c71.w, r2.x
    mul_pp r2.xyz, r2, c70
    mul_pp r5.xyz, r2, c17
    mul r5.xyz, r5, c70.w
    mad r2.xyz, r2, c17, -r5
    mad_pp r2.xyz, r4.w, r2, r5
    dp3_pp r2.w, r4, -c10
    dp3_pp r0.y, r4, -r0.yzww
    mul r4.xyz, r2.w, c36
    mul_pp r4.xyz, r1.w, r4
    cmp_pp r4.xyz, r2.w, r4, c3.x
    mul_pp r5.xyz, c58.w, c58
    mul_pp r5.xyz, r0.y, r5
    cmp_pp r0.yzw, r0.y, r5.xxyz, c3.x
    mad_pp r0.xyz, r0.x, r0.yzww, r4
    add_pp r0.xyz, r0, r2
    mul_pp r0.xyz, r0, c16
    cmp r2.xy, -r3_abs.x, v0, c3.x
    cmp r2.xy, -r3_abs.y, v0.zwzw, r2
    cmp r2.xy, -r3_abs.z, v1, r2
    cmp r2.xy, -r3_abs.w, v1.zwzw, r2
    texld_pp r2, r2, s0
    mul_pp r0.w, r2.w, c16.w
    mul_pp r0.w, r0.w, v6.w
    mul_pp r3.w, r0.w, c21.x
    add r0.w, c0.x, vPos.y
    mov r4.x, c86.x
    mad r0.w, r0.w, c24.w, -r4.x
    mul_sat_pp r0.w, r0.w, c86.y
    lrp_pp r4.xyz, r0.w, r2, c3.y
    mad_pp r0.xyz, r0, r4, r1
    mul_pp r3.xyz, r0, v6
    mul_pp r0, r3, c89
    min_pp r1, r0, c2.w
    mul_pp r0.xyz, c75, v5.y
    mad_pp oC0.xyz, r1, v5.x, r0
    mov_pp oC0.w, r1.w

// approximately 146 instruction slots used (5 texture, 141 arithmetic)
