//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   sampler2D s0;
//   sampler2D s1;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   s0           s0       1
//   s1           s1       1
//

    ps_3_0
    dcl_texcoord v0.xy
    dcl_2d s0
    dcl_2d s1
    texld_pp oC0, v0, s0
    texld r0, v0, s1
    mov oDepth, r0.x

// approximately 3 instruction slots used (2 texture, 1 arithmetic)
