//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_ViewportSize;
//   sampler2D s0;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   g_ViewportSize c24      1
//   s0             s0       1
//

    ps_3_0
    def c0, -1, 0, 1, 0.5
    def c1, 0.25, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    texld r0, v0, s0
    mul r0, r0, c0.w
    mov r1.xyz, c0
    mad r1, c24.zwzw, -r1.xyzy, v0.xyxy
    texld r2, r1, s0
    texld r1, r1.zwzw, s0
    mad r0, r2, c1.x, r0
    mad_pp oC0, r1, c1.x, r0

// approximately 8 instruction slots used (3 texture, 5 arithmetic)
