//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   float4 g_GI0Scale;
//   float4 g_GI1Scale;
//   sampler2D g_GISampler;
//   float4 g_LightScatteringColor;
//   float4 g_OpacityReflectionRefractionSpectype;
//   float4 g_PowerGlossLevel;
//   float4 g_ShadowMapParams;
//   sampler2D g_ShadowMapSampler;
//   float4 g_Specular;
//   float4 mrgEyeLight_Attribute;
//   float4 mrgEyeLight_Diffuse;
//   float4 mrgEyeLight_Range;
//   float4 mrgEyeLight_Specular;
//   float2 mrgFresnelParam;
//   float4 mrgGlobalLight_Diffuse;
//   float4 mrgGlobalLight_Direction;
//   float4 mrgGlobalLight_Specular;
//   float4 mrgInShadowScale;
//   float4 mrgLuminanceRange;
//   float4 mrgTexcoordIndex[4];
//   sampler2D sampDif;
//   sampler2D sampEnv;
//   sampler2D sampPow;
//   sampler2D sampSpe;
//
//
// Registers:
//
//   Name                                  Reg   Size
//   ------------------------------------- ----- ----
//   mrgGlobalLight_Direction              c10      1
//   g_Diffuse                             c16      1
//   g_Ambient                             c17      1
//   g_Specular                            c18      1
//   g_PowerGlossLevel                     c20      1
//   g_OpacityReflectionRefractionSpectype c21      1
//   g_EyePosition                         c22      1
//   g_EyeDirection                        c23      1
//   mrgTexcoordIndex                      c26      1
//   mrgGlobalLight_Diffuse                c36      1
//   mrgGlobalLight_Specular               c37      1
//   mrgEyeLight_Diffuse                   c58      1
//   mrgEyeLight_Specular                  c59      1
//   mrgEyeLight_Range                     c60      1
//   mrgEyeLight_Attribute                 c61      1
//   mrgFresnelParam                       c62      1
//   mrgLuminanceRange                     c63      1
//   mrgInShadowScale                      c64      1
//   g_ShadowMapParams                     c65      1
//   g_GI0Scale                            c70      1
//   g_GI1Scale                            c71      1
//   g_LightScatteringColor                c75      1
//   g_ForceAlphaColor                     c89      1
//   sampDif                               s0       1
//   sampSpe                               s1       1
//   sampPow                               s2       1
//   sampEnv                               s5       1
//   g_GISampler                           s10      1
//   g_ShadowMapSampler                    s13      1
//

    ps_3_0
    def c0, 0.298900008, 0.586600006, 0.114399999, 1024
    def c1, 2, -1, -2, 3
    def c2, -1, 1, 0, 0.5
    def c3, 4, 0, 0, 0
    def c4, 0, 1, 2, 3
    def c5, 500, 5, 0.5, 0.25
    dcl_texcoord v0
    dcl_texcoord1 v1
    dcl_texcoord2 v2.xyz
    dcl_texcoord3 v3.xyz
    dcl_texcoord4 v4
    dcl_texcoord5_pp v5.xyz
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s5
    dcl_2d s10
    dcl_2d s13
    add_pp r0.x, -c61.z, c61.y
    rcp_pp r0.x, r0.x
    add r0.yzw, -c22.xxyz, v2.xxyz
    dp3 r1.x, r0.yzww, r0.yzww
    rsq r1.x, r1.x
    mul_pp r0.yzw, r0, r1.x
    rcp r1.x, r1.x
    add r1.x, r1.x, -c60.z
    dp3_pp r1.y, r0.yzww, c23
    add_pp r1.y, r1.y, -c61.z
    mul_sat_pp r0.x, r0.x, r1.y
    mad_pp r1.y, r0.x, c1.z, c1.w
    mul_pp r0.x, r0.x, r0.x
    mul_pp r0.x, r0.x, r1.y
    pow_sat_pp r1.y, r0.x, c61.w
    mov r2.xy, c4
    add r0.x, r2.y, -c61.x
    cmp_pp r0.x, r0.x, c4.y, r1.y
    add r1.y, -c60.z, c60.w
    rcp r1.y, r1.y
    mul_sat r1.x, r1.y, r1.x
    add_pp r1.x, -r1.x, c4.y
    cmp_pp r1.x, -c61.x, r2.y, r1.x
    mul_pp r0.x, r0.x, r1.x
    frc r1.xyz, c26.xzww
    cmp r3.xyz, -r1, c4.x, c4.y
    add r1.xyz, -r1, c26.xzww
    cmp r2.xzw, c26, r2.x, r3.xyyz
    add r1.xyz, r1, r2.xzww
    add r3, r1.z, -c4
    cmp r1.zw, -r3_abs.x, v0.xyxy, c4.x
    cmp r1.zw, -r3_abs.y, v0, r1
    cmp r1.zw, -r3_abs.z, v1.xyxy, r1
    cmp r1.zw, -r3_abs.w, v1, r1
    texld_pp r3, r1.zwzw, s2
    mul_pp r1.zw, r3.x, c20.xyyz
    mul_pp r1.zw, r1, c5.xyxy
    mul_pp r2.xzw, c59.w, c59.xyyz
    mul_pp r2.xzw, r1.w, r2
    max_pp r3.y, r1.z, c4.y
    mul_pp r4.xyz, r1.w, c37
    min r1.z, r3.y, c0.w
    add_pp r5, c22.xyzx, -v2.xyzx
    dp3_pp r1.w, r5.yzww, r5.yzww
    rsq_pp r1.w, r1.w
    mad_pp r3.yzw, r5.xxyz, r1.w, -r0
    nrm_pp r6.xyz, r3.yzww
    nrm r7, v3.xyzx
    dp3_sat_pp r3.y, r6, r7
    pow r4.w, r3.y, r1.z
    mul_pp r2.xzw, r2, r4.w
    mul_pp r2.xzw, r0.x, r2
    rcp r3.y, v4.w
    mul r3.yz, r3.y, v4.xxyw
    mad r3.yz, r3, c1.x, c1.y
    abs_sat r3.yz, r3
    add_sat r3.yz, r3, -c65.x
    mul r3.yz, r3, c65.y
    max r4.w, r3.y, r3.z
    max r3.y, v4.z, c4.x
    add r3.z, r3.y, -v4.w
    cmp r6.z, r3.z, c4.x, r3.y
    mov r6.xyw, v4
    texldp_pp r6, r6, s13
    lrp_pp r3.y, v5.z, c4.y, r6.x
    lrp_pp r6.x, r4.w, c4.y, r3.y
    texld_pp r8, v0.zwzw, s10
    mul r3.y, r6.x, r8.w
    mad_pp r6.yzw, r5.xxyz, r1.w, -c10.xxyz
    mul r5, r1.w, r5
    nrm_pp r9.xyz, r6.yzww
    dp3_sat_pp r1.w, r9, r7
    pow r3.z, r1.w, r1.z
    mul_pp r4.xyz, r3.z, r4
    mad_pp r2.xzw, r4.xyyz, r3.y, r2
    dp3 r1.z, r5.yzww, r7.yzww
    add r1.w, r1.z, r1.z
    mov_sat_pp r1.z, r1.z
    add_pp r1.z, -r1.z, c4.y
    mad r4, r1.w, r7, -r5
    mad r5, r4.wyzw, c2.xxyz, c2.zzzw
    mul r9, r4, c2.yxxz
    cmp r4, r4.z, r5, r9
    add r1.w, r4.z, c4.y
    rcp r1.w, r1.w
    mad r3.zw, r4.xyyx, r1.w, c4.y
    mad_pp r4.x, r3.w, c5.w, r4.w
    mul_pp r4.y, r3.z, c5.z
    texld_pp r4, r4, s5
    mul r5.xyz, r4, c63.x
    mad_pp r4.xyz, r5, r4.w, r4
    mul_pp r3.xzw, r3.x, r4.xyyz
    mul r1.w, c64.z, c64.x
    mov r4.xz, c64
    mad r4.x, r4.x, -r4.z, r4.z
    mad_pp r1.w, r3.y, r4.x, r1.w
    mul_pp r3.xzw, r1.w, r3
    mad_pp r2.xzw, r2, c18.xyyz, r3
    add r4, r1.y, -c4
    add r5, r1.x, -c4
    cmp r1.xy, -r4_abs.x, v0, c4.x
    cmp r1.xy, -r4_abs.y, v0.zwzw, r1
    cmp r1.xy, -r4_abs.z, v1, r1
    cmp r1.xy, -r4_abs.w, v1.zwzw, r1
    texld_pp r4, r1, s1
    mul_pp r1.xyw, r2.xzzw, r4.xyzz
    mul_pp r2.x, r1.z, r1.z
    mul_pp r2.x, r2.x, r2.x
    mul_pp r1.z, r1.z, r2.x
    lrp_pp r3.x, r1.z, r2.y, c62.x
    mul_pp r1.z, r3.x, c62.y
    mul_pp r1.xyz, r1.z, r1.xyww
    mul_pp r2.xyz, r8, r8
    dp3_pp r1.w, r2, c0
    mad_pp r2.xyz, r8, r8, -r1.w
    mad_sat_pp r2.xyz, r2, c71.w, r1.w
    mul_pp r2.xyz, r2, c70
    mul_pp r3.xzw, r2.xyyz, c17.xyyz
    mul r3.xzw, r3, c70.w
    mad r2.xyz, r2, c17, -r3.xzww
    mad_pp r2.xyz, r6.x, r2, r3.xzww
    dp3_pp r1.w, r7.wyzw, -c10
    dp3_pp r0.y, r7.wyzw, -r0.yzww
    mul r3.xzw, r1.w, c36.xyyz
    mul_pp r3.xyz, r3.y, r3.xzww
    cmp_pp r3.xyz, r1.w, r3, c4.x
    mul_pp r4.xyz, c58.w, c58
    mul_pp r4.xyz, r0.y, r4
    cmp_pp r0.yzw, r0.y, r4.xxyz, c4.x
    mad_pp r0.xyz, r0.x, r0.yzww, r3
    add_pp r0.xyz, r0, r2
    mul_pp r0.xyz, r0, c16
    cmp r2.xy, -r5_abs.x, v0, c4.x
    cmp r2.xy, -r5_abs.y, v0.zwzw, r2
    cmp r2.xy, -r5_abs.z, v1, r2
    cmp r2.xy, -r5_abs.w, v1.zwzw, r2
    texld_pp r2, r2, s0
    mad_pp r0.xyz, r0, r2, r1
    dp3_pp r1.x, r1, r1
    mul_pp r1.y, r2.w, c16.w
    mul_pp r1.y, r1.y, r1.y
    max_pp r2.x, r1.y, r1.x
    rsq_pp r1.x, r2.x
    rcp_pp r1.x, r1.x
    mul_pp r0.w, r1.x, c21.x
    mul_pp r0, r0, c89
    min_pp r1, r0, c3.x
    mul_pp r0.xyz, c75, v5.y
    mad_pp oC0.xyz, r1, v5.x, r0
    mov_pp oC0.w, r1.w

// approximately 162 instruction slots used (6 texture, 156 arithmetic)
