//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   float4 g_GI0Scale;
//   float4 g_LightScatteringColor;
//   float4 g_OpacityReflectionRefractionSpectype;
//   float4 g_ShadowMapParams;
//   sampler2D g_ShadowMapSampler;
//   sampler2D g_VerticalShadowMapSampler;
//   float4 g_aLightField[6];
//   float4 mrgEyeLight_Attribute;
//   float4 mrgEyeLight_Diffuse;
//   float4 mrgEyeLight_Range;
//   float2 mrgFresnelParam;
//   float4 mrgGlobalLight_Diffuse;
//   float4 mrgGlobalLight_Direction;
//   float4 mrgInShadowScale;
//   float4 mrgLuminanceRange;
//   float4 mrgTexcoordIndex[4];
//   sampler2D sampDif;
//   sampler2D sampEnv;
//
//
// Registers:
//
//   Name                                  Reg   Size
//   ------------------------------------- ----- ----
//   mrgGlobalLight_Direction              c10      1
//   g_Diffuse                             c16      1
//   g_Ambient                             c17      1
//   g_OpacityReflectionRefractionSpectype c21      1
//   g_EyePosition                         c22      1
//   g_EyeDirection                        c23      1
//   mrgTexcoordIndex                      c26      1
//   mrgGlobalLight_Diffuse                c36      1
//   mrgEyeLight_Diffuse                   c58      1
//   mrgEyeLight_Range                     c60      1
//   mrgEyeLight_Attribute                 c61      1
//   mrgFresnelParam                       c62      1
//   mrgLuminanceRange                     c63      1
//   mrgInShadowScale                      c64      1
//   g_ShadowMapParams                     c65      1
//   g_GI0Scale                            c70      1
//   g_LightScatteringColor                c75      1
//   g_aLightField                         c77      6
//   g_ForceAlphaColor                     c89      1
//   sampDif                               s0       1
//   sampEnv                               s5       1
//   g_VerticalShadowMapSampler            s7       1
//   g_ShadowMapSampler                    s13      1
//

    ps_3_0
    def c0, 0.25, 4, 0, 0
    def c1, 0.5, 2, -1, -3
    def c2, 0, 1, 2, 3
    def c3, -1, 1, 0, 0.5
    dcl_texcoord v0
    dcl_texcoord1 v1
    dcl_texcoord2 v2.xyz
    dcl_texcoord3 v3.xyz
    dcl_texcoord4 v4
    dcl_texcoord6 v5
    dcl_texcoord5_pp v6.xyz
    dcl_2d s0
    dcl_2d s5
    dcl_2d s7
    dcl_2d s13
    add_pp r0.x, -c61.z, c61.y
    rcp_pp r0.x, r0.x
    add r0.yzw, -c22.xxyz, v2.xxyz
    dp3 r1.x, r0.yzww, r0.yzww
    rsq r1.x, r1.x
    mul_pp r0.yzw, r0, r1.x
    rcp r1.x, r1.x
    add r1.x, r1.x, -c60.z
    dp3_pp r1.y, r0.yzww, c23
    add_pp r1.y, r1.y, -c61.z
    mul_sat_pp r0.x, r0.x, r1.y
    mad_pp r1.y, r0.x, -c1.y, -c1.w
    mul_pp r0.x, r0.x, r0.x
    mul_pp r0.x, r0.x, r1.y
    pow_sat_pp r1.y, r0.x, c61.w
    mov r2.xy, c2
    add r0.x, r2.y, -c61.x
    cmp_pp r0.x, r0.x, c2.y, r1.y
    add r1.y, -c60.z, c60.w
    rcp r1.y, r1.y
    mul_sat r1.x, r1.y, r1.x
    add_pp r1.x, -r1.x, c2.y
    cmp_pp r1.x, -c61.x, r2.y, r1.x
    mul_pp r0.x, r0.x, r1.x
    max r1.x, v4.z, c2.x
    add r1.y, r1.x, -v4.w
    cmp r1.z, r1.y, c2.x, r1.x
    mov r1.xyw, v4
    texldp_pp r1, r1, s13
    max r1.y, v5.z, c2.x
    add r1.z, r1.y, -v5.w
    cmp r3.z, r1.z, c2.x, r1.y
    mov r3.xyw, v5
    texldp_pp r3, r3, s7
    min_pp r2.z, r3.x, r1.x
    lrp_pp r1.x, v6.z, c2.y, r3.x
    lrp_pp r1.y, v6.z, c2.y, r2.z
    rcp r1.z, v4.w
    mul r1.zw, r1.z, v4.xyxy
    mad r1.zw, r1, c1.y, c1.z
    abs_sat r1.zw, r1
    add_sat r1.zw, r1, -c65.x
    mul r1.zw, r1, c65.y
    max r2.z, r1.z, r1.w
    lrp_pp r3.x, r2.z, c2.y, r1.y
    lrp_pp r3.y, r2.z, c2.y, r1.x
    mul r1.x, r3.x, c77.w
    nrm r4, v3.xyzx
    dp3_pp r1.y, r4.wyzw, -c10
    mul r3.xzw, r1.y, c36.xyyz
    mul_pp r3.xzw, r1.x, r3
    cmp_pp r1.yzw, r1.y, r3.xxzw, c2.x
    mul_pp r3.xzw, c58.w, c58.xyyz
    dp3_pp r0.y, r4.wyzw, -r0.yzww
    mul_pp r3.xzw, r0.y, r3
    cmp_pp r0.yzw, r0.y, r3.xxzw, c2.x
    mad_pp r0.xyz, r0.x, r0.yzww, r1.yzww
    mov r5.xyz, c79
    add r1.yzw, -r5.xxyz, c80.xxyz
    mad_pp r3.xzw, r4.wyyz, c1.x, c1.x
    mad r1.yzw, r3.z, r1, c79.xxyz
    mul_pp r5.xyz, r4.wyzw, r4.wyzw
    mul r1.yzw, r1, r5.y
    mov r6.xyz, c77
    add r6.xyz, -r6, c78
    mad r6.xyz, r3.x, r6, c77
    mad_pp r1.yzw, r5.x, r6.xxyz, r1
    mov r6.xyz, c81
    add r5.xyw, -r6.xyzz, c82.xyzz
    mad r3.xzw, r3.w, r5.xyyw, c81.xyyz
    mad_pp r1.yzw, r5.z, r3.xxzw, r1
    mul_pp r3.xzw, r1.yyzw, c17.xyyz
    mul r3.xzw, r3, c70.w
    mad r1.yzw, r1, c17.xxyz, -r3.xxzw
    mad_pp r1.yzw, r3.y, r1, r3.xxzw
    add_pp r0.xyz, r0, r1.yzww
    mul_pp r0.xyz, r0, c16
    frc r0.w, c26.x
    cmp r1.y, -r0.w, c2.x, c2.y
    add r0.w, -r0.w, c26.x
    cmp r1.y, c26.x, r2.x, r1.y
    add r0.w, r0.w, r1.y
    add r3, r0.w, -c2
    cmp r1.yz, -r3_abs.x, v0.xxyw, c2.x
    cmp r1.yz, -r3_abs.y, v0.xzww, r1
    cmp r1.yz, -r3_abs.z, v1.xxyw, r1
    cmp r1.yz, -r3_abs.w, v1.xzww, r1
    texld_pp r3, r1.yzzw, s0
    add_pp r5, c22.xyzx, -v2.xyzx
    dp3_pp r0.w, r5.yzww, r5.yzww
    rsq_pp r0.w, r0.w
    mul r5, r0.w, r5
    dp3 r0.w, r5.yzww, r4.yzww
    add r1.y, r0.w, r0.w
    mov_sat_pp r0.w, r0.w
    add_pp r0.w, -r0.w, c2.y
    mad r4, r1.y, r4, -r5
    mad r5, r4.wyzw, c3.xxyz, c3.zzzw
    mul r6, r4, c3.yxxz
    cmp r4, r4.z, r5, r6
    add r1.y, r4.z, c2.y
    rcp r1.y, r1.y
    mad r1.yz, r4.xyxw, r1.y, c2.y
    mad_pp r4.x, r1.z, c0.x, r4.w
    mul_pp r4.y, r1.y, c1.x
    texld_pp r4, r4, s5
    mul r1.yzw, r4.xxyz, c63.x
    mad_pp r1.yzw, r1, r4.w, r4.xxyz
    mul r2.x, c64.z, c64.x
    mov r4.xz, c64
    mad r2.z, r4.x, -r4.z, r4.z
    mad_pp r1.x, r1.x, r2.z, r2.x
    mul_pp r1.xyz, r1.x, r1.yzww
    mul_pp r1.w, r0.w, r0.w
    mul_pp r1.w, r1.w, r1.w
    mul_pp r0.w, r0.w, r1.w
    lrp_pp r1.w, r0.w, r2.y, c62.x
    mul_pp r0.w, r1.w, c62.y
    mul_pp r1.xyz, r0.w, r1
    mad_pp r0.xyz, r0, r3, r1
    mul_pp r1.w, r3.w, c16.w
    mul_pp r1.w, r1.w, r1.w
    dp3_pp r1.x, r1, r1
    max_pp r2.x, r1.w, r1.x
    rsq_pp r1.x, r2.x
    rcp_pp r1.x, r1.x
    mul_pp r0.w, r1.x, c21.x
    mul_pp r0, r0, c89
    min_pp r1, r0, c0.y
    mul_pp r0.xyz, c75, v6.y
    mad_pp oC0.xyz, r1, v6.x, r0
    mov_pp oC0.w, r1.w

// approximately 136 instruction slots used (4 texture, 132 arithmetic)
