//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   float4 g_GI0Scale;
//   float4 g_GI1Scale;
//   sampler2D g_GISampler;
//   float4 g_LightScatteringColor;
//   float4 g_OffsetParam;
//   float4 g_OpacityReflectionRefractionSpectype;
//   float4 g_PowerGlossLevel;
//   float4 g_ShadowMapParams;
//   sampler2D g_ShadowMapSampler;
//   float4 g_Specular;
//   float4 mrgEyeLight_Attribute;
//   float4 mrgEyeLight_Diffuse;
//   float4 mrgEyeLight_Range;
//   float4 mrgEyeLight_Specular;
//   float4 mrgGlobalLight_Diffuse;
//   float4 mrgGlobalLight_Direction;
//   float4 mrgGlobalLight_Specular;
//   float4 mrgLocalLight0_Color;
//   float4 mrgLocalLight0_Position;
//   float4 mrgLocalLight0_Range;
//   float4 mrgLocalLight1_Color;
//   float4 mrgLocalLight1_Position;
//   float4 mrgLocalLight1_Range;
//   float4 mrgLocalLight2_Color;
//   float4 mrgLocalLight2_Position;
//   float4 mrgLocalLight2_Range;
//   float4 mrgLocalLight3_Color;
//   float4 mrgLocalLight3_Position;
//   float4 mrgLocalLight3_Range;
//   float4 mrgTexcoordIndex[4];
//   sampler2D sampDif;
//   sampler2D sampOffset0;
//   sampler2D sampOffsetMask;
//   sampler2D sampPower;
//
//
// Registers:
//
//   Name                                  Reg   Size
//   ------------------------------------- ----- ----
//   mrgGlobalLight_Direction              c10      1
//   g_Diffuse                             c16      1
//   g_Ambient                             c17      1
//   g_Specular                            c18      1
//   g_PowerGlossLevel                     c20      1
//   g_OpacityReflectionRefractionSpectype c21      1
//   g_EyePosition                         c22      1
//   g_EyeDirection                        c23      1
//   mrgTexcoordIndex                      c26      2
//   mrgGlobalLight_Diffuse                c36      1
//   mrgGlobalLight_Specular               c37      1
//   mrgLocalLight0_Position               c38      1
//   mrgLocalLight0_Color                  c39      1
//   mrgLocalLight0_Range                  c40      1
//   mrgLocalLight1_Position               c42      1
//   mrgLocalLight1_Color                  c43      1
//   mrgLocalLight1_Range                  c44      1
//   mrgLocalLight2_Position               c46      1
//   mrgLocalLight2_Color                  c47      1
//   mrgLocalLight2_Range                  c48      1
//   mrgLocalLight3_Position               c50      1
//   mrgLocalLight3_Color                  c51      1
//   mrgLocalLight3_Range                  c52      1
//   mrgEyeLight_Diffuse                   c58      1
//   mrgEyeLight_Specular                  c59      1
//   mrgEyeLight_Range                     c60      1
//   mrgEyeLight_Attribute                 c61      1
//   g_ShadowMapParams                     c65      1
//   g_GI0Scale                            c70      1
//   g_GI1Scale                            c71      1
//   g_LightScatteringColor                c75      1
//   g_ForceAlphaColor                     c89      1
//   g_OffsetParam                         c150     1
//   sampDif                               s0       1
//   sampPower                             s1       1
//   sampOffset0                           s3       1
//   sampOffsetMask                        s5       1
//   g_GISampler                           s10      1
//   g_ShadowMapSampler                    s13      1
//

    ps_3_0
    def c0, 0.298900008, 0.586600006, 0.114399999, 1024
    def c1, 2, -1, -2, 3
    def c2, 500, 5, 4, 0
    def c3, 0, 1, 2, 3
    dcl_texcoord v0
    dcl_texcoord1 v1
    dcl_texcoord2 v2.xyz
    dcl_texcoord3_pp v3
    dcl_texcoord4 v4
    dcl_texcoord5_pp v5.xyz
    dcl_color_pp v6
    dcl_2d s0
    dcl_2d s1
    dcl_2d s3
    dcl_2d s5
    dcl_2d s10
    dcl_2d s13
    frc r0.xy, c27.xzzw
    cmp r0.zw, -r0.xyxy, c3.x, c3.y
    add r0.xy, -r0, c27.xzzw
    mov r1.xy, c3
    cmp r0.zw, c27.xyxz, r1.x, r0
    add r0.xy, r0.zwzw, r0
    add r2, r0.x, -c3
    add r0, r0.y, -c3
    cmp r1.zw, -r2_abs.x, v0.xyxy, c3.x
    cmp r1.zw, -r2_abs.y, v0, r1
    cmp r1.zw, -r2_abs.z, v1.xyxy, r1
    cmp r1.zw, -r2_abs.w, v1, r1
    texld_pp r2, r1.zwzw, s3
    mad r1.zw, r2.xywx, c1.x, c1.y
    mul_pp r1.zw, r1, c150.xyxy
    cmp r2.xy, -r0_abs.x, v0, c3.x
    cmp r0.xy, -r0_abs.y, v0.zwzw, r2
    cmp r0.xy, -r0_abs.z, v1, r0
    cmp r0.xy, -r0_abs.w, v1.zwzw, r0
    texld r0, r0, s5
    mul_pp r0.xy, r0.x, r1.zwzw
    frc r0.zw, c26.xyxz
    cmp r1.zw, -r0, c3.x, c3.y
    add r0.zw, -r0, c26.xyxz
    cmp r1.xz, c26, r1.x, r1.zyww
    add r0.zw, r0, r1.xyxz
    add r2, r0.z, -c3
    add r3, r0.w, -c3
    cmp r0.zw, -r2_abs.x, v0.xyxy, c3.x
    cmp r0.zw, -r2_abs.y, v0, r0
    cmp r0.zw, -r2_abs.z, v1.xyxy, r0
    cmp r0.zw, -r2_abs.w, v1, r0
    mad r0.zw, r0.xyxy, v6.w, r0
    texld_pp r2, r0.zwzw, s0
    add r0.z, -c40.z, c40.w
    rcp r0.z, r0.z
    add r1.xzw, -c38.xyyz, v2.xyyz
    dp3 r0.w, r1.xzww, r1.xzww
    rsq r0.w, r0.w
    rcp r4.x, r0.w
    mul_pp r1.xzw, r0.w, r1
    add r0.w, r4.x, -c40.z
    mul_sat r0.z, r0.z, r0.w
    add r0.w, -c44.z, c44.w
    rcp r0.w, r0.w
    add r4.xyz, -c42, v2
    dp3 r4.w, r4, r4
    rsq r4.w, r4.w
    rcp r5.x, r4.w
    mul_pp r4.xyz, r4.w, r4
    add r4.w, r5.x, -c44.z
    mul_sat r0.w, r0.w, r4.w
    add_pp r0.zw, -r0, c3.y
    cmp r5.xy, -r3_abs.x, v0, c3.x
    cmp r3.xy, -r3_abs.y, v0.zwzw, r5
    cmp r3.xy, -r3_abs.z, v1, r3
    cmp r3.xy, -r3_abs.w, v1.zwzw, r3
    mad r0.xy, r0, v6.w, r3
    texld_pp r3, r0, s1
    mul_pp r0.xy, r3.x, c20.yzzw
    mul_pp r0.xy, r0, c2
    mul_pp r3.xyz, r0.y, c43
    max_pp r3.w, r0.x, c3.y
    min r0.x, r3.w, c0.w
    add_pp r5.xyz, c22, -v2
    dp3_pp r3.w, r5, r5
    rsq_pp r3.w, r3.w
    mad_pp r6.xyz, r5, r3.w, -r4
    nrm_pp r7.xyz, r6
    nrm_pp r6.xyz, v3
    dp3_sat_pp r4.w, r7, r6
    pow r5.w, r4.w, r0.x
    mul_pp r3.xyz, r3, r5.w
    mul_pp r3.xyz, r0.w, r3
    mul_pp r7.xyz, r0.y, c39
    mad_pp r8.xyz, r5, r3.w, -r1.xzww
    dp3_pp r1.x, r6, -r1.xzww
    nrm_pp r9.xyz, r8
    dp3_sat_pp r1.z, r9, r6
    pow r4.w, r1.z, r0.x
    mul_pp r7.xyz, r4.w, r7
    mad_pp r3.xyz, r0.z, r7, r3
    add r1.z, -c48.z, c48.w
    rcp r1.z, r1.z
    add r7.xyz, -c46, v2
    dp3 r1.w, r7, r7
    rsq r1.w, r1.w
    rcp r4.w, r1.w
    mul_pp r7.xyz, r1.w, r7
    add r1.w, r4.w, -c48.z
    mul_sat r1.z, r1.z, r1.w
    add_pp r1.z, -r1.z, c3.y
    mul_pp r8.xyz, r0.y, c47
    mad_pp r9.xyz, r5, r3.w, -r7
    dp3_pp r1.w, r6, -r7
    nrm_pp r7.xyz, r9
    dp3_sat_pp r4.w, r7, r6
    pow r5.w, r4.w, r0.x
    mul_pp r7.xyz, r5.w, r8
    mad_pp r3.xyz, r1.z, r7, r3
    add r4.w, -c52.z, c52.w
    rcp r4.w, r4.w
    add r7.xyz, -c50, v2
    dp3 r5.w, r7, r7
    rsq r5.w, r5.w
    rcp r6.w, r5.w
    mul_pp r7.xyz, r5.w, r7
    add r5.w, r6.w, -c52.z
    mul_sat r4.w, r4.w, r5.w
    add_pp r4.w, -r4.w, c3.y
    mul_pp r8.xyz, r0.y, c51
    mad_pp r9.xyz, r5, r3.w, -r7
    dp3_pp r5.w, r6, -r7
    nrm_pp r7.xyz, r9
    dp3_sat_pp r6.w, r7, r6
    pow r7.x, r6.w, r0.x
    mul_pp r7.xyz, r7.x, r8
    mad_pp r3.xyz, r4.w, r7, r3
    rcp r6.w, v4.w
    mul r7.xy, r6.w, v4
    mad r7.xy, r7, c1.x, c1.y
    abs_sat r7.xy, r7
    add_sat r7.xy, r7, -c65.x
    mul r7.xy, r7, c65.y
    max r6.w, r7.x, r7.y
    max r7.x, v4.z, c3.x
    add r7.y, r7.x, -v4.w
    cmp r7.z, r7.y, c3.x, r7.x
    mov r7.xyw, v4
    texldp_pp r7, r7, s13
    lrp_pp r8.x, v5.z, c3.y, r7.x
    lrp_pp r7.x, r6.w, c3.y, r8.x
    texld_pp r8, v0.zwzw, s10
    mul_pp r6.w, r7.x, r8.w
    mul_pp r7.yzw, r0.y, c37.xxyz
    mad_pp r9.xyz, r5, r3.w, -c10
    nrm_pp r10.xyz, r9
    dp3_sat_pp r8.w, r10, r6
    pow r9.x, r8.w, r0.x
    mul_pp r7.yzw, r7, r9.x
    mad_pp r3.xyz, r7.yzww, r6.w, r3
    add_pp r7.y, -c61.z, c61.y
    rcp_pp r7.y, r7.y
    add r9.xyz, -c22, v2
    dp3 r7.z, r9, r9
    rsq r7.z, r7.z
    mul_pp r9.xyz, r7.z, r9
    rcp r7.z, r7.z
    add r7.z, r7.z, -c60.z
    dp3_pp r7.w, r9, c23
    add_pp r7.w, r7.w, -c61.z
    mul_sat_pp r7.y, r7.y, r7.w
    mad_pp r7.w, r7.y, c1.z, c1.w
    mul_pp r7.y, r7.y, r7.y
    mul_pp r7.y, r7.y, r7.w
    pow_sat_pp r8.w, r7.y, c61.w
    add r7.y, r1.y, -c61.x
    cmp_pp r7.y, r7.y, c3.y, r8.w
    add r7.w, -c60.z, c60.w
    rcp r7.w, r7.w
    mul_sat r7.z, r7.w, r7.z
    add_pp r7.z, -r7.z, c3.y
    cmp_pp r1.y, -c61.x, r1.y, r7.z
    mul_pp r1.y, r7.y, r1.y
    mul_pp r7.yzw, c59.w, c59.xxyz
    mul_pp r7.yzw, r0.y, r7
    mad_pp r5.xyz, r5, r3.w, -r9
    dp3_pp r0.y, r6, -r9
    nrm_pp r9.xyz, r5
    dp3_sat_pp r3.w, r9, r6
    pow r5.x, r3.w, r0.x
    mul_pp r5.xyz, r5.x, r7.yzww
    mad_pp r3.xyz, r1.y, r5, r3
    mul_pp r3.xyz, r3, c18
    mul_pp r3.xyz, r3, v3.w
    dp3_pp r0.x, r6, -r4
    dp3_pp r3.w, r6, -c10
    mul_pp r4.xyz, r0.x, c43
    cmp_pp r4.xyz, r0.x, r4, c3.x
    mul_pp r4.xyz, r0.w, r4
    mul_pp r5.xyz, r1.x, c39
    cmp_pp r5.xyz, r1.x, r5, c3.x
    mad_pp r0.xzw, r0.z, r5.xyyz, r4.xyyz
    mul_pp r4.xyz, r1.w, c47
    cmp_pp r4.xyz, r1.w, r4, c3.x
    mad_pp r0.xzw, r1.z, r4.xyyz, r0
    mul_pp r1.xzw, r5.w, c51.xyyz
    cmp_pp r1.xzw, r5.w, r1, c3.x
    mad_pp r0.xzw, r4.w, r1, r0
    mul r1.xzw, r3.w, c36.xyyz
    mul_pp r1.xzw, r6.w, r1
    cmp_pp r1.xzw, r3.w, r1, c3.x
    add_pp r0.xzw, r0, r1
    mul_pp r1.xzw, c58.w, c58.xyyz
    mul_pp r1.xzw, r0.y, r1
    cmp_pp r1.xzw, r0.y, r1, c3.x
    mad_pp r0.xyz, r1.y, r1.xzww, r0.xzww
    mul_pp r1.xyz, r8, r8
    dp3_pp r0.w, r1, c0
    mad_pp r1.xyz, r8, r8, -r0.w
    mad_sat_pp r1.xyz, r1, c71.w, r0.w
    mul_pp r1.xyz, r1, c70
    mul_pp r4.xyz, r1, c17
    mul r4.xyz, r4, c70.w
    mad r1.xyz, r1, c17, -r4
    mad_pp r1.xyz, r7.x, r1, r4
    add_pp r0.xyz, r0, r1
    mul_pp r0.xyz, r0, c16
    mad_pp r0.xyz, r0, r2, r3
    mul_pp r0.w, r2.w, c16.w
    mul_pp r1.w, r0.w, c21.x
    add_pp r1.xyz, r0, v6
    mul_pp r0, r1, c89
    min_pp r1, r0, c2.z
    mul_pp r0.xyz, c75, v5.y
    mad_pp oC0.xyz, r1, v5.x, r0
    mov_pp oC0.w, r1.w

// approximately 245 instruction slots used (6 texture, 239 arithmetic)
