//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   float4 g_GI0Scale;
//   float4 g_GI1Scale;
//   sampler2D g_GISampler;
//   float4 g_LightScatteringColor;
//   float4 g_OffsetParam;
//   float4 g_OpacityReflectionRefractionSpectype;
//   float4 g_PowerGlossLevel;
//   float4 g_ShadowMapParams;
//   sampler2D g_ShadowMapSampler;
//   float4 g_Specular;
//   float4 mrgEyeLight_Attribute;
//   float4 mrgEyeLight_Diffuse;
//   float4 mrgEyeLight_Range;
//   float4 mrgEyeLight_Specular;
//   float4 mrgGlobalLight_Diffuse;
//   float4 mrgGlobalLight_Direction;
//   float4 mrgGlobalLight_Specular;
//   float4 mrgLocalLight0_Color;
//   float4 mrgLocalLight0_Position;
//   float4 mrgLocalLight0_Range;
//   float4 mrgLocalLight1_Color;
//   float4 mrgLocalLight1_Position;
//   float4 mrgLocalLight1_Range;
//   float4 mrgLocalLight2_Color;
//   float4 mrgLocalLight2_Position;
//   float4 mrgLocalLight2_Range;
//   float4 mrgLocalLight3_Color;
//   float4 mrgLocalLight3_Position;
//   float4 mrgLocalLight3_Range;
//   float4 mrgTexcoordIndex[4];
//   sampler2D sampDif;
//   sampler2D sampNrm;
//   sampler2D sampOffset0;
//   sampler2D sampOffsetMask;
//   sampler2D sampPower;
//
//
// Registers:
//
//   Name                                  Reg   Size
//   ------------------------------------- ----- ----
//   mrgGlobalLight_Direction              c10      1
//   g_Diffuse                             c16      1
//   g_Ambient                             c17      1
//   g_Specular                            c18      1
//   g_PowerGlossLevel                     c20      1
//   g_OpacityReflectionRefractionSpectype c21      1
//   g_EyePosition                         c22      1
//   g_EyeDirection                        c23      1
//   mrgTexcoordIndex                      c26      2
//   mrgGlobalLight_Diffuse                c36      1
//   mrgGlobalLight_Specular               c37      1
//   mrgLocalLight0_Position               c38      1
//   mrgLocalLight0_Color                  c39      1
//   mrgLocalLight0_Range                  c40      1
//   mrgLocalLight1_Position               c42      1
//   mrgLocalLight1_Color                  c43      1
//   mrgLocalLight1_Range                  c44      1
//   mrgLocalLight2_Position               c46      1
//   mrgLocalLight2_Color                  c47      1
//   mrgLocalLight2_Range                  c48      1
//   mrgLocalLight3_Position               c50      1
//   mrgLocalLight3_Color                  c51      1
//   mrgLocalLight3_Range                  c52      1
//   mrgEyeLight_Diffuse                   c58      1
//   mrgEyeLight_Specular                  c59      1
//   mrgEyeLight_Range                     c60      1
//   mrgEyeLight_Attribute                 c61      1
//   g_ShadowMapParams                     c65      1
//   g_GI0Scale                            c70      1
//   g_GI1Scale                            c71      1
//   g_LightScatteringColor                c75      1
//   g_ForceAlphaColor                     c89      1
//   g_OffsetParam                         c150     1
//   sampDif                               s0       1
//   sampPower                             s1       1
//   sampNrm                               s2       1
//   sampOffset0                           s3       1
//   sampOffsetMask                        s5       1
//   g_GISampler                           s10      1
//   g_ShadowMapSampler                    s13      1
//

    ps_3_0
    def c0, 2, -1, -2, 3
    def c1, 0.298900008, 0.586600006, 0.114399999, 1024
    def c2, 500, 5, 4, 0
    def c3, 0, 1, 2, 3
    dcl_texcoord v0
    dcl_texcoord1 v1
    dcl_texcoord2 v2.xyz
    dcl_texcoord3_pp v3
    dcl_texcoord4 v4
    dcl_texcoord5_pp v5.xyz
    dcl_texcoord7 v6.xyz
    dcl_texcoord8 v7.xyz
    dcl_color_pp v8
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s5
    dcl_2d s10
    dcl_2d s13
    rcp r0.x, v4.w
    mul r0.xy, r0.x, v4
    mad r0.xy, r0, c0.x, c0.y
    abs_sat r0.xy, r0
    add_sat r0.xy, r0, -c65.x
    mul r0.xy, r0, c65.y
    max r1.x, r0.x, r0.y
    max r0.x, v4.z, c3.x
    add r0.y, r0.x, -v4.w
    cmp r0.z, r0.y, c3.x, r0.x
    mov r0.xyw, v4
    texldp_pp r0, r0, s13
    lrp_pp r1.y, v5.z, c3.y, r0.x
    lrp_pp r0.x, r1.x, c3.y, r1.y
    add r0.y, -c40.z, c40.w
    rcp r0.y, r0.y
    add r1.xyz, -c38, v2
    dp3 r0.z, r1, r1
    rsq r0.z, r0.z
    rcp r0.w, r0.z
    mul_pp r1.xyz, r0.z, r1
    add r0.z, r0.w, -c40.z
    mul_sat r0.y, r0.y, r0.z
    add r0.z, -c44.z, c44.w
    rcp r0.z, r0.z
    add r2.xyz, -c42, v2
    dp3 r0.w, r2, r2
    rsq r0.w, r0.w
    rcp r1.w, r0.w
    mul_pp r2.xyz, r0.w, r2
    add r0.w, r1.w, -c44.z
    mul_sat r0.z, r0.z, r0.w
    add_pp r0.yz, -r0, c3.y
    frc r3.xy, c27.xzzw
    cmp r3.zw, -r3.xyxy, c3.x, c3.y
    add r3.xy, -r3, c27.xzzw
    mov r4.xy, c3
    cmp r3.zw, c27.xyxz, r4.x, r3
    add r3.xy, r3.zwzw, r3
    add r5, r3.x, -c3
    add r3, r3.y, -c3
    cmp r4.zw, -r5_abs.x, v0.xyxy, c3.x
    cmp r4.zw, -r5_abs.y, v0, r4
    cmp r4.zw, -r5_abs.z, v1.xyxy, r4
    cmp r4.zw, -r5_abs.w, v1, r4
    texld_pp r5, r4.zwzw, s3
    mad r4.zw, r5.xywx, c0.x, c0.y
    mul_pp r4.zw, r4, c150.xyxy
    cmp r5.xy, -r3_abs.x, v0, c3.x
    cmp r3.xy, -r3_abs.y, v0.zwzw, r5
    cmp r3.xy, -r3_abs.z, v1, r3
    cmp r3.xy, -r3_abs.w, v1.zwzw, r3
    texld r3, r3, s5
    mul_pp r3.xy, r3.x, r4.zwzw
    frc r5.xyz, c26.xzww
    cmp r6.xyz, -r5, c3.x, c3.y
    add r5.xyz, -r5, c26.xzww
    cmp r4.xzw, c26, r4.x, r6.xyyz
    add r4.xzw, r4, r5.xyyz
    add r5, r4.z, -c3
    cmp r3.zw, -r5_abs.x, v0.xyxy, c3.x
    cmp r3.zw, -r5_abs.y, v0, r3
    cmp r3.zw, -r5_abs.z, v1.xyxy, r3
    cmp r3.zw, -r5_abs.w, v1, r3
    mad r3.zw, r3.xyxy, v8.w, r3
    texld_pp r5, r3.zwzw, s1
    mul_pp r3.zw, r5.x, c20.xyyz
    mul_pp r3.zw, r3, c2.xyxy
    mul_pp r5.xyz, r3.w, c43
    max_pp r0.w, r3.z, c3.y
    min r1.w, r0.w, c1.w
    add r6, r4.w, -c3
    add r7, r4.x, -c3
    cmp r4.xz, -r6_abs.x, v0.xyyw, c3.x
    cmp r4.xz, -r6_abs.y, v0.zyww, r4
    cmp r4.xz, -r6_abs.z, v1.xyyw, r4
    cmp r4.xz, -r6_abs.w, v1.zyww, r4
    mad r4.xz, r3.xyyw, v8.w, r4
    texld_pp r6, r4.xzzw, s2
    mul_pp r6.x, r6.w, r6.x
    mad_pp r4.xz, r6.xyyw, c0.x, c0.y
    nrm_pp r6.xyz, v7
    mul_pp r6.xyz, r4.z, r6
    nrm_pp r8.xyz, v6
    mad_pp r6.xyz, r4.x, r8, r6
    dp2add_pp r0.w, r4.xzzw, -r4.xzzw, c3.y
    rsq_pp r0.w, r0.w
    rcp_pp r0.w, r0.w
    nrm_pp r8.xyz, v3
    mad_pp r4.xzw, r0.w, r8.xyyz, r6.xyyz
    add_pp r6.xyz, c22, -v2
    dp3_pp r0.w, r6, r6
    rsq_pp r0.w, r0.w
    mad_pp r8.xyz, r6, r0.w, -r2
    dp3_pp r2.x, r4.xzww, -r2
    nrm_pp r9.xyz, r8
    dp3_sat_pp r2.y, r9, r4.xzww
    pow r3.z, r2.y, r1.w
    mul_pp r2.yzw, r3.z, r5.xxyz
    mul_pp r2.yzw, r0.z, r2
    mul_pp r5.xyz, r3.w, c39
    mad_pp r8.xyz, r6, r0.w, -r1
    dp3_pp r1.x, r4.xzww, -r1
    nrm_pp r9.xyz, r8
    dp3_sat_pp r1.y, r9, r4.xzww
    pow r3.z, r1.y, r1.w
    mul_pp r5.xyz, r3.z, r5
    mad_pp r2.yzw, r0.y, r5.xxyz, r2
    add r1.y, -c48.z, c48.w
    rcp r1.y, r1.y
    add r5.xyz, -c46, v2
    dp3 r1.z, r5, r5
    rsq r1.z, r1.z
    rcp r3.z, r1.z
    mul_pp r5.xyz, r1.z, r5
    add r1.z, r3.z, -c48.z
    mul_sat r1.y, r1.y, r1.z
    add_pp r1.y, -r1.y, c3.y
    mul_pp r8.xyz, r3.w, c47
    mad_pp r9.xyz, r6, r0.w, -r5
    dp3_pp r1.z, r4.xzww, -r5
    nrm_pp r5.xyz, r9
    dp3_sat_pp r3.z, r5, r4.xzww
    pow r5.x, r3.z, r1.w
    mul_pp r5.xyz, r5.x, r8
    mad_pp r2.yzw, r1.y, r5.xxyz, r2
    add r3.z, -c52.z, c52.w
    rcp r3.z, r3.z
    add r5.xyz, -c50, v2
    dp3 r5.w, r5, r5
    rsq r5.w, r5.w
    rcp r6.w, r5.w
    mul_pp r5.xyz, r5.w, r5
    add r5.w, r6.w, -c52.z
    mul_sat r3.z, r3.z, r5.w
    add_pp r3.z, -r3.z, c3.y
    mul_pp r8.xyz, r3.w, c51
    mad_pp r9.xyz, r6, r0.w, -r5
    dp3_pp r5.x, r4.xzww, -r5
    nrm_pp r10.xyz, r9
    dp3_sat_pp r5.y, r10, r4.xzww
    pow r6.w, r5.y, r1.w
    mul_pp r5.yzw, r6.w, r8.xxyz
    mad_pp r2.yzw, r3.z, r5, r2
    mul_pp r5.yzw, r3.w, c37.xxyz
    mad_pp r8.xyz, r6, r0.w, -c10
    nrm_pp r9.xyz, r8
    dp3_sat_pp r6.w, r9, r4.xzww
    pow r8.x, r6.w, r1.w
    mul_pp r5.yzw, r5, r8.x
    mad_pp r2.yzw, r5, r0.x, r2
    add_pp r5.y, -c61.z, c61.y
    rcp_pp r5.y, r5.y
    add r8.xyz, -c22, v2
    dp3 r5.z, r8, r8
    rsq r5.z, r5.z
    mul_pp r8.xyz, r5.z, r8
    rcp r5.z, r5.z
    add r5.z, r5.z, -c60.z
    dp3_pp r5.w, r8, c23
    add_pp r5.w, r5.w, -c61.z
    mul_sat_pp r5.y, r5.y, r5.w
    mad_pp r5.w, r5.y, c0.z, c0.w
    mul_pp r5.y, r5.y, r5.y
    mul_pp r5.y, r5.y, r5.w
    pow_sat_pp r6.w, r5.y, c61.w
    add r5.y, r4.y, -c61.x
    cmp_pp r5.y, r5.y, c3.y, r6.w
    add r5.w, -c60.z, c60.w
    rcp r5.w, r5.w
    mul_sat r5.z, r5.w, r5.z
    add_pp r5.z, -r5.z, c3.y
    cmp_pp r4.y, -c61.x, r4.y, r5.z
    mul_pp r4.y, r5.y, r4.y
    mad_pp r5.yzw, r6.xxyz, r0.w, -r8.xxyz
    dp3_pp r0.w, r4.xzww, -r8
    nrm_pp r6.xyz, r5.yzww
    dp3_sat_pp r5.y, r6, r4.xzww
    dp3_pp r4.x, r4.xzww, -c10
    pow r4.z, r5.y, r1.w
    mul_pp r5.yzw, c59.w, c59.xxyz
    mul_pp r5.yzw, r3.w, r5
    mul_pp r5.yzw, r4.z, r5
    mad_pp r2.yzw, r4.y, r5, r2
    mul_pp r2.yzw, r2, c18.xxyz
    mul_pp r2.yzw, r2, v3.w
    mul_pp r5.yzw, r2.x, c43.xxyz
    cmp_pp r5.yzw, r2.x, r5, c3.x
    mul_pp r5.yzw, r0.z, r5
    mul_pp r6.xyz, r1.x, c39
    cmp_pp r6.xyz, r1.x, r6, c3.x
    mad_pp r5.yzw, r0.y, r6.xxyz, r5
    mul_pp r6.xyz, r1.z, c47
    cmp_pp r1.xzw, r1.z, r6.xyyz, c3.x
    mad_pp r1.xyz, r1.y, r1.xzww, r5.yzww
    mul_pp r5.yzw, r5.x, c51.xxyz
    cmp_pp r5.xyz, r5.x, r5.yzww, c3.x
    mad_pp r1.xyz, r3.z, r5, r1
    mul r5.xyz, r4.x, c36
    mul_pp r5.xyz, r0.x, r5
    cmp_pp r4.xzw, r4.x, r5.xyyz, c3.x
    add_pp r1.xyz, r1, r4.xzww
    mul_pp r4.xzw, c58.w, c58.xyyz
    mul_pp r4.xzw, r0.w, r4
    cmp_pp r0.yzw, r0.w, r4.xxzw, c3.x
    mad_pp r0.yzw, r4.y, r0, r1.xxyz
    texld_pp r1, v0.zwzw, s10
    mul_pp r4.xyz, r1, r1
    dp3_pp r1.w, r4, c1
    mad_pp r1.xyz, r1, r1, -r1.w
    mad_sat_pp r1.xyz, r1, c71.w, r1.w
    mul_pp r1.xyz, r1, c70
    mul_pp r4.xyz, r1, c17
    mul r4.xyz, r4, c70.w
    mad r1.xyz, r1, c17, -r4
    mad_pp r1.xyz, r0.x, r1, r4
    add_pp r0.xyz, r0.yzww, r1
    mul_pp r0.xyz, r0, c16
    cmp r1.xy, -r7_abs.x, v0, c3.x
    cmp r1.xy, -r7_abs.y, v0.zwzw, r1
    cmp r1.xy, -r7_abs.z, v1, r1
    cmp r1.xy, -r7_abs.w, v1.zwzw, r1
    mad r1.xy, r3, v8.w, r1
    texld_pp r1, r1, s0
    mad_pp r0.xyz, r0, r1, r2.yzww
    mul_pp r0.w, r1.w, c16.w
    mul_pp r1.w, r0.w, c21.x
    add_pp r1.xyz, r0, v8
    mul_pp r0, r1, c89
    min_pp r1, r0, c2.z
    mul_pp r0.xyz, c75, v5.y
    mad_pp oC0.xyz, r1, v5.x, r0
    mov_pp oC0.w, r1.w

// approximately 266 instruction slots used (7 texture, 259 arithmetic)
