//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   float4 g_GI0Scale;
//   float4 g_GI1Scale;
//   sampler2D g_GISampler;
//   float4 g_LightScatteringColor;
//   row_major float4x4 g_MtxView;
//   float4 g_OpacityReflectionRefractionSpectype;
//   float4 g_PowerGlossLevel;
//   float4 g_ShadowMapParams;
//   sampler2D g_ShadowMapSampler;
//   float4 g_Specular;
//   float4 g_ViewportSize;
//   float4 mrgEyeLight_Attribute;
//   float4 mrgEyeLight_Diffuse;
//   float4 mrgEyeLight_Range;
//   float4 mrgEyeLight_Specular;
//   float4 mrgGlobalLight_Diffuse;
//   float4 mrgGlobalLight_Direction;
//   float4 mrgGlobalLight_Specular;
//   float4 mrgInShadowScale;
//   float4 mrgLuminanceRange;
//   float4 mrgPlayableParam;
//   float4 mrgTexcoordIndex[4];
//   sampler2D sampDif;
//   sampler2D sampEmi;
//   sampler2D sampEnv;
//   sampler2D sampNrm;
//   sampler2D sampPow;
//
//
// Registers:
//
//   Name                                  Reg   Size
//   ------------------------------------- ----- ----
//   mrgGlobalLight_Direction              c10      1
//   g_Diffuse                             c16      1
//   g_Ambient                             c17      1
//   g_Specular                            c18      1
//   g_PowerGlossLevel                     c20      1
//   g_OpacityReflectionRefractionSpectype c21      1
//   g_EyePosition                         c22      1
//   g_EyeDirection                        c23      1
//   g_ViewportSize                        c24      1
//   mrgTexcoordIndex                      c26      2
//   mrgGlobalLight_Diffuse                c36      1
//   mrgGlobalLight_Specular               c37      1
//   mrgEyeLight_Diffuse                   c58      1
//   mrgEyeLight_Specular                  c59      1
//   mrgEyeLight_Range                     c60      1
//   mrgEyeLight_Attribute                 c61      1
//   mrgLuminanceRange                     c63      1
//   mrgInShadowScale                      c64      1
//   g_ShadowMapParams                     c65      1
//   g_GI0Scale                            c70      1
//   g_GI1Scale                            c71      1
//   g_LightScatteringColor                c75      1
//   mrgPlayableParam                      c86      1
//   g_ForceAlphaColor                     c89      1
//   g_MtxView                             c90      3
//   sampDif                               s0       1
//   sampPow                               s2       1
//   sampNrm                               s3       1
//   sampEmi                               s4       1
//   sampEnv                               s5       1
//   g_GISampler                           s10      1
//   g_ShadowMapSampler                    s13      1
//

    ps_3_0
    def c0, 0.298900008, 0.586600006, 0.114399999, 1024
    def c1, 0.5, 2, -1, -3
    def c2, 4, 0, 0, 0
    def c3, 0, 1, 2, 3
    def c4, 500, 5, 0.5, -0.5
    dcl_texcoord v0
    dcl_texcoord1 v1
    dcl_texcoord2 v2.xyz
    dcl_texcoord3_pp v3
    dcl_texcoord4 v4
    dcl_texcoord5_pp v5.xyz
    dcl_texcoord7 v6.xyz
    dcl_texcoord8 v7.xyz
    dcl_color_pp v8
    dcl vPos.y
    dcl_2d s0
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s5
    dcl_2d s10
    dcl_2d s13
    add_pp r0.x, -c61.z, c61.y
    rcp_pp r0.x, r0.x
    add r0.yzw, -c22.xxyz, v2.xxyz
    dp3 r1.x, r0.yzww, r0.yzww
    rsq r1.x, r1.x
    mul_pp r0.yzw, r0, r1.x
    rcp r1.x, r1.x
    add r1.x, r1.x, -c60.z
    dp3_pp r1.y, r0.yzww, c23
    add_pp r1.y, r1.y, -c61.z
    mul_sat_pp r0.x, r0.x, r1.y
    mad_pp r1.y, r0.x, -c1.y, -c1.w
    mul_pp r0.x, r0.x, r0.x
    mul_pp r0.x, r0.x, r1.y
    pow_sat_pp r1.y, r0.x, c61.w
    mov r2.xy, c3
    add r0.x, r2.y, -c61.x
    cmp_pp r0.x, r0.x, c3.y, r1.y
    add r1.y, -c60.z, c60.w
    rcp r1.y, r1.y
    mul_sat r1.x, r1.y, r1.x
    add_pp r1.x, -r1.x, c3.y
    cmp_pp r1.x, -c61.x, r2.y, r1.x
    mul_pp r0.x, r0.x, r1.x
    add_pp r1.xyz, c22, -v2
    dp3_pp r1.w, r1, r1
    rsq_pp r1.w, r1.w
    mad_pp r2.yzw, r1.xxyz, r1.w, -r0
    mad_pp r1.xyz, r1, r1.w, -c10
    nrm_pp r3.xyz, r1
    nrm_pp r1.xyz, r2.yzww
    frc r2.yz, c27.xxyw
    cmp r4.xy, -r2.yzzw, c3.x, c3.y
    add r2.yz, -r2, c27.xxyw
    cmp r4.xy, c27, r2.x, r4
    add r2.yz, r2, r4.xxyw
    add r4, r2.y, -c3
    add r5, r2.z, -c3
    cmp r2.yz, -r4_abs.x, v0.xxyw, c3.x
    cmp r2.yz, -r4_abs.y, v0.xzww, r2
    cmp r2.yz, -r4_abs.z, v1.xxyw, r2
    cmp r2.yz, -r4_abs.w, v1.xzww, r2
    texld_pp r4, r2.yzzw, s3
    mul_pp r4.x, r4.w, r4.x
    mad_pp r2.yz, r4.xxyw, c1.y, c1.z
    nrm_pp r4.xyz, v7
    mul_pp r4.xyz, r2.z, r4
    nrm_pp r6.xyz, v6
    mad_pp r4.xyz, r2.y, r6, r4
    dp2add_pp r1.w, r2.yzzw, -r2.yzzw, c3.y
    rsq_pp r1.w, r1.w
    rcp_pp r1.w, r1.w
    nrm_pp r6.xyz, v3
    mad_pp r2.yzw, r1.w, r6.xxyz, r4.xxyz
    dp3_sat_pp r1.x, r1, r2.yzww
    frc r1.yz, c26.xxww
    cmp r4.xy, -r1.yzzw, c3.x, c3.y
    add r1.yz, -r1, c26.xxww
    cmp r4.xy, c26.xwzw, r2.x, r4
    add r1.yz, r1, r4.xxyw
    add r4, r1.z, -c3
    add r6, r1.y, -c3
    cmp r1.yz, -r4_abs.x, v0.xxyw, c3.x
    cmp r1.yz, -r4_abs.y, v0.xzww, r1
    cmp r1.yz, -r4_abs.z, v1.xxyw, r1
    cmp r1.yz, -r4_abs.w, v1.xzww, r1
    texld_pp r4, r1.yzzw, s2
    mul_pp r1.yz, r4.x, c20
    mul_pp r1.yz, r1, c4.xxyw
    max_pp r2.x, r1.y, c3.y
    min r1.y, r2.x, c0.w
    pow r2.x, r1.x, r1.y
    mul_pp r4.yzw, c59.w, c59.xxyz
    mul_pp r4.yzw, r1.z, r4
    mul_pp r1.xzw, r1.z, c37.xyyz
    mul_pp r4.yzw, r2.x, r4
    mul_pp r4.yzw, r0.x, r4
    dp3_sat_pp r2.x, r3, r2.yzww
    pow r3.x, r2.x, r1.y
    mul_pp r1.xyz, r1.xzww, r3.x
    rcp r1.w, v4.w
    mul r3.xy, r1.w, v4
    mad r3.xy, r3, c1.y, c1.z
    abs_sat r3.xy, r3
    add_sat r3.xy, r3, -c65.x
    mul r3.xy, r3, c65.y
    max r1.w, r3.x, r3.y
    max r2.x, v4.z, c3.x
    add r3.x, r2.x, -v4.w
    cmp r3.z, r3.x, c3.x, r2.x
    mov r3.xyw, v4
    texldp_pp r3, r3, s13
    lrp_pp r2.x, v5.z, c3.y, r3.x
    lrp_pp r3.x, r1.w, c3.y, r2.x
    texld_pp r7, v0.zwzw, s10
    mul r1.w, r3.x, r7.w
    mad_pp r1.xyz, r1, r1.w, r4.yzww
    mul r8, r2.z, c91
    mad r8, r2.y, c90, r8
    mad r8, r2.w, c92, r8
    dp4 r2.x, r8, r8
    rsq r2.x, r2.x
    mul r3.yz, r2.x, r8.xxyw
    mad_pp r3.yz, r3, c4.xzww, c4.z
    texld_pp r8, r3.yzzw, s5
    mul r3.yzw, r8.xxyz, c63.x
    mad_pp r3.yzw, r3, r8.w, r8.xxyz
    mul_pp r3.yzw, r4.x, r3
    mul r2.x, c64.z, c64.x
    mov r4.xz, c64
    mad r4.x, r4.x, -r4.z, r4.z
    mad_pp r2.x, r1.w, r4.x, r2.x
    mul_pp r3.yzw, r2.x, r3
    mad_pp r1.xyz, r1, c18, r3.yzww
    mul_pp r1.xyz, r1, v3.w
    mul_pp r3.yzw, r7.xxyz, r7.xxyz
    dp3_pp r2.x, r3.yzww, c0
    mad_pp r3.yzw, r7.xxyz, r7.xxyz, -r2.x
    mad_sat_pp r3.yzw, r3, c71.w, r2.x
    mul_pp r4.xyz, r3.yzww, c70
    mul r4.xyz, r4, c70.w
    mad r3.yzw, r3, c70.xxyz, -r4.xxyz
    mad_pp r3.xyz, r3.x, r3.yzww, r4
    dp3_pp r2.x, r2.yzww, -c10
    dp3_pp r0.y, r2.yzww, -r0.yzww
    mul r2.yzw, r2.x, c36.xxyz
    mul_pp r2.yzw, r1.w, r2
    cmp_pp r2.xyz, r2.x, r2.yzww, c3.x
    mul_pp r4.xyz, c58.w, c58
    mul_pp r4.xyz, r0.y, r4
    cmp_pp r0.yzw, r0.y, r4.xxyz, c3.x
    mad_pp r0.xyz, r0.x, r0.yzww, r2
    add_pp r0.xyz, r0, r3
    mul_pp r0.xyz, r0, c16
    cmp r2.xy, -r6_abs.x, v0, c3.x
    cmp r2.xy, -r6_abs.y, v0.zwzw, r2
    cmp r2.xy, -r6_abs.z, v1, r2
    cmp r2.xy, -r6_abs.w, v1.zwzw, r2
    texld_pp r2, r2, s0
    mul_pp r0.w, r2.w, c16.w
    mul_pp r0.w, r0.w, v8.w
    mul_pp r3.w, r0.w, c21.x
    add r0.w, c1.x, vPos.y
    mov r4.x, c86.x
    mad r0.w, r0.w, c24.w, -r4.x
    mul_sat_pp r0.w, r0.w, c86.y
    lrp_pp r4.xyz, r0.w, r2, c3.y
    mad_pp r0.xyz, r0, r4, r1
    cmp r1.xy, -r5_abs.x, v0, c3.x
    cmp r1.xy, -r5_abs.y, v0.zwzw, r1
    cmp r1.xy, -r5_abs.z, v1, r1
    cmp r1.xy, -r5_abs.w, v1.zwzw, r1
    texld_pp r1, r1, s4
    mul_pp r1.xyz, r1, c17
    mad_pp r0.xyz, r1, r0.w, r0
    mul_pp r3.xyz, r0, v8
    mul_pp r0, r3, c89
    min_pp r1, r0, c2.x
    mul_pp r0.xyz, c75, v5.y
    mad_pp oC0.xyz, r1, v5.x, r0
    mov_pp oC0.w, r1.w

// approximately 178 instruction slots used (7 texture, 171 arithmetic)
