//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Diffuse;
//   float4 g_ForceAlphaColor;
//   float4 g_OpacityReflectionRefractionSpectype;
//   float4 g_ParticleParam;
//   sampler2D sampDif;
//
//
// Registers:
//
//   Name                                  Reg   Size
//   ------------------------------------- ----- ----
//   g_Diffuse                             c16      1
//   g_OpacityReflectionRefractionSpectype c21      1
//   g_ForceAlphaColor                     c89      1
//   g_ParticleParam                       c150     1
//   sampDif                               s0       1
//

    ps_3_0
    def c0, 4, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_color_pp v1
    dcl_2d s0
    texld_pp r0, v0, s0
    mul_pp r0.w, r0.w, c16.w
    mul_pp r0, r0, v1
    mul_pp r0.w, r0.w, c21.x
    mul_pp r0, r0, c150
    mul_pp r0, r0, c89
    min_pp oC0, r0, c0.x

// approximately 7 instruction slots used (1 texture, 6 arithmetic)
