//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   float4 g_GI0Scale;
//   float4 g_GI1Scale;
//   sampler2D g_GISampler;
//   float4 g_LightScatteringColor;
//   float4 g_OpacityReflectionRefractionSpectype;
//   sampler2D g_ReflectionMapSampler2;
//   float4 g_ShadowMapParams;
//   sampler2D g_ShadowMapSampler;
//   float4 g_ViewportSize;
//   float4 mrgEyeLight_Attribute;
//   float4 mrgEyeLight_Diffuse;
//   float4 mrgEyeLight_Range;
//   float4 mrgGlobalLight_Diffuse;
//   float4 mrgGlobalLight_Direction;
//   float4 mrgPlayableParam;
//   float4 mrgTexcoordIndex[4];
//   sampler2D sampDif;
//
//
// Registers:
//
//   Name                                  Reg   Size
//   ------------------------------------- ----- ----
//   mrgGlobalLight_Direction              c10      1
//   g_Diffuse                             c16      1
//   g_Ambient                             c17      1
//   g_OpacityReflectionRefractionSpectype c21      1
//   g_EyePosition                         c22      1
//   g_EyeDirection                        c23      1
//   g_ViewportSize                        c24      1
//   mrgTexcoordIndex                      c26      1
//   mrgGlobalLight_Diffuse                c36      1
//   mrgEyeLight_Diffuse                   c58      1
//   mrgEyeLight_Range                     c60      1
//   mrgEyeLight_Attribute                 c61      1
//   g_ShadowMapParams                     c65      1
//   g_GI0Scale                            c70      1
//   g_GI1Scale                            c71      1
//   g_LightScatteringColor                c75      1
//   mrgPlayableParam                      c86      1
//   g_ForceAlphaColor                     c89      1
//   sampDif                               s0       1
//   g_GISampler                           s10      1
//   g_ShadowMapSampler                    s13      1
//   g_ReflectionMapSampler2               s15      1
//

    ps_3_0
    def c0, 0.5, 0.298900008, 0.586600006, 0.114399999
    def c1, 2, -1, -2, 3
    def c2, 1, 0, -1, 4
    def c3, 0, 1, 2, 3
    dcl_texcoord v0
    dcl_texcoord1 v1
    dcl_texcoord2 v2.xyz
    dcl_texcoord3_pp v3
    dcl_texcoord4 v4
    dcl_texcoord5_pp v5.xyz
    dcl_color_pp v6
    dcl vPos.xy
    dcl_2d s0
    dcl_2d s10
    dcl_2d s13
    dcl_2d s15
    add_pp r0.x, -c61.z, c61.y
    rcp_pp r0.x, r0.x
    add r0.yzw, -c22.xxyz, v2.xxyz
    dp3 r1.x, r0.yzww, r0.yzww
    rsq r1.x, r1.x
    mul_pp r0.yzw, r0, r1.x
    rcp r1.x, r1.x
    add r1.x, r1.x, -c60.z
    dp3_pp r1.y, r0.yzww, c23
    add_pp r1.y, r1.y, -c61.z
    mul_sat_pp r0.x, r0.x, r1.y
    mad_pp r1.y, r0.x, c1.z, c1.w
    mul_pp r0.x, r0.x, r0.x
    mul_pp r0.x, r0.x, r1.y
    pow_sat_pp r1.y, r0.x, c61.w
    mov r2.xy, c3
    add r0.x, r2.y, -c61.x
    cmp_pp r0.x, r0.x, c3.y, r1.y
    add r1.y, -c60.z, c60.w
    rcp r1.y, r1.y
    mul_sat r1.x, r1.y, r1.x
    add_pp r1.x, -r1.x, c3.y
    cmp_pp r1.x, -c61.x, r2.y, r1.x
    mul_pp r0.x, r0.x, r1.x
    rcp r1.x, v4.w
    mul r1.xy, r1.x, v4
    mad r1.xy, r1, c1.x, c1.y
    abs_sat r1.xy, r1
    add_sat r1.xy, r1, -c65.x
    mul r1.xy, r1, c65.y
    max r2.y, r1.x, r1.y
    max r1.x, v4.z, c3.x
    add r1.y, r1.x, -v4.w
    cmp r1.z, r1.y, c3.x, r1.x
    mov r1.xyw, v4
    texldp_pp r1, r1, s13
    lrp_pp r2.z, v5.z, c3.y, r1.x
    lrp_pp r1.x, r2.y, c3.y, r2.z
    texld_pp r3, v0.zwzw, s10
    mul_pp r1.y, r1.x, r3.w
    nrm_pp r4.xyz, v3
    dp3_pp r1.z, r4, -c10
    dp3_pp r0.y, r4, -r0.yzww
    mul r2.yzw, r1.z, c36.xxyz
    mul_pp r2.yzw, r1.y, r2
    cmp_pp r1.yzw, r1.z, r2, c3.x
    mul_pp r2.yzw, c58.w, c58.xxyz
    mul_pp r2.yzw, r0.y, r2
    cmp_pp r0.yzw, r0.y, r2, c3.x
    mad_pp r0.xyz, r0.x, r0.yzww, r1.yzww
    mul_pp r1.yzw, r3.xxyz, r3.xxyz
    dp3_pp r0.w, r1.yzww, c0.yzww
    mad_pp r1.yzw, r3.xxyz, r3.xxyz, -r0.w
    mad_sat_pp r1.yzw, r1, c71.w, r0.w
    mul_pp r1.yzw, r1, c70.xxyz
    mul_pp r2.yzw, r1, c17.xxyz
    mul r2.yzw, r2, c70.w
    mad r1.yzw, r1, c17.xxyz, -r2
    mad_pp r1.xyz, r1.x, r1.yzww, r2.yzww
    add_pp r0.xyz, r0, r1
    mul_pp r0.xyz, r0, c16
    mul r1.xy, c24.zwzw, vPos
    mov r3.xyz, c2
    mad r3, c24.zzzw, r3.xyyz, r3.yzzy
    mad r1.xy, r1, c3.z, r3
    mov r1.z, -r1.y
    add r1.xy, r3.zwzw, r1.xzzw
    mad r1.xy, r1, c0.x, c0.x
    texld_pp r1, r1, s15
    mul_pp r1.xyz, r1, v3.w
    frc r0.w, c26.x
    cmp r1.w, -r0.w, c3.x, c3.y
    add r0.w, -r0.w, c26.x
    cmp r1.w, c26.x, r2.x, r1.w
    add r0.w, r0.w, r1.w
    add r2, r0.w, -c3
    cmp r3.xy, -r2_abs.x, v0, c3.x
    cmp r2.xy, -r2_abs.y, v0.zwzw, r3
    cmp r2.xy, -r2_abs.z, v1, r2
    cmp r2.xy, -r2_abs.w, v1.zwzw, r2
    texld_pp r2, r2, s0
    mul_pp r0.w, r2.w, c16.w
    mul_pp r0.w, r0.w, v6.w
    mul_pp r3.w, r0.w, c21.x
    add r0.w, c0.x, vPos.y
    mov r1.w, c24.w
    mad r0.w, r0.w, r1.w, -c86.x
    mul_sat_pp r0.w, r0.w, c86.y
    lrp_pp r4.xyz, r0.w, r2, c3.y
    mad_pp r0.xyz, r0, r4, r1
    mul_pp r3.xyz, r0, v6
    mul_pp r0, r3, c89
    min_pp r1, r0, c2.w
    mul_pp r0.xyz, c75, v5.y
    mad_pp oC0.xyz, r1, v5.x, r0
    mov_pp oC0.w, r1.w

// approximately 100 instruction slots used (4 texture, 96 arithmetic)
