//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   float4 g_GI0Scale;
//   float4 g_LightScatteringColor;
//   float4 g_PowerGlossLevel;
//   float4 g_ShadowMapParams;
//   sampler2D g_ShadowMapSampler;
//   float4 g_Specular;
//   sampler2D g_VerticalShadowMapSampler;
//   float4 g_aLightField[6];
//   float4 mrgEyeLight_Attribute;
//   float4 mrgEyeLight_Diffuse;
//   float4 mrgEyeLight_Range;
//   float4 mrgEyeLight_Specular;
//   float4 mrgGlobalLight_Diffuse;
//   float4 mrgGlobalLight_Direction;
//   float4 mrgGlobalLight_Specular;
//   sampler2D sampDif;
//   sampler2D sampHeight;
//   sampler2D sampNrm;
//   sampler2D sampPower;
//
//
// Registers:
//
//   Name                       Reg   Size
//   -------------------------- ----- ----
//   mrgGlobalLight_Direction   c10      1
//   g_Diffuse                  c16      1
//   g_Ambient                  c17      1
//   g_Specular                 c18      1
//   g_PowerGlossLevel          c20      1
//   g_EyePosition              c22      1
//   g_EyeDirection             c23      1
//   mrgGlobalLight_Diffuse     c36      1
//   mrgGlobalLight_Specular    c37      1
//   mrgEyeLight_Diffuse        c58      1
//   mrgEyeLight_Specular       c59      1
//   mrgEyeLight_Range          c60      1
//   mrgEyeLight_Attribute      c61      1
//   g_ShadowMapParams          c65      1
//   g_GI0Scale                 c70      1
//   g_LightScatteringColor     c75      1
//   g_aLightField              c77      6
//   g_ForceAlphaColor          c89      1
//   sampDif                    s0       1
//   sampPower                  s2       1
//   sampNrm                    s3       1
//   sampHeight                 s4       1
//   g_VerticalShadowMapSampler s7       1
//   g_ShadowMapSampler         s13      1
//

    ps_3_0
    def c0, 0.0299999993, 2, -1, 1
    def c1, 0.5, 0, -2, 3
    def c2, 500, 5, 1024, 4
    dcl_texcoord v0.xy
    dcl_texcoord2 v1.xyz
    dcl_texcoord3_pp v2
    dcl_texcoord4_pp v3
    dcl_texcoord5_pp v4
    dcl_texcoord6 v5
    dcl_texcoord8 v6
    dcl_texcoord7_pp v7
    dcl_2d s0
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s7
    dcl_2d s13
    add_pp r0.x, -c61.z, c61.y
    rcp_pp r0.x, r0.x
    add r0.yzw, -c22.xxyz, v1.xxyz
    dp3 r1.x, r0.yzww, r0.yzww
    rsq r1.x, r1.x
    mul_pp r0.yzw, r0, r1.x
    rcp r1.x, r1.x
    add r1.x, r1.x, -c60.z
    dp3_pp r1.y, r0.yzww, c23
    add_pp r1.y, r1.y, -c61.z
    mul_sat_pp r0.x, r0.x, r1.y
    mad_pp r1.y, r0.x, c1.z, c1.w
    mul_pp r0.x, r0.x, r0.x
    mul_pp r0.x, r0.x, r1.y
    pow_sat_pp r1.y, r0.x, c61.w
    mov_pp r1.w, c0.w
    add r0.x, r1.w, -c61.x
    cmp_pp r0.x, r0.x, c0.w, r1.y
    add r1.y, -c60.z, c60.w
    rcp r1.y, r1.y
    mul_sat r1.x, r1.y, r1.x
    add_pp r1.x, -r1.x, c0.w
    cmp_pp r1.x, -c61.x, r1.w, r1.x
    mul_pp r0.x, r0.x, r1.x
    max r1.x, v5.z, c1.y
    add r1.y, r1.x, -v5.w
    cmp r1.z, r1.y, c1.y, r1.x
    mov r1.xyw, v5
    texldp_pp r1, r1, s13
    max r1.y, v6.z, c1.y
    add r1.z, r1.y, -v6.w
    cmp r2.z, r1.z, c1.y, r1.y
    mov r2.xyw, v6
    texldp_pp r2, r2, s7
    min_pp r3.x, r2.x, r1.x
    lrp_pp r1.x, v7.z, c0.w, r2.x
    lrp_pp r1.y, v7.z, c0.w, r3.x
    rcp r1.z, v5.w
    mul r1.zw, r1.z, v5.xyxy
    mad r1.zw, r1, c0.y, c0.z
    abs_sat r1.zw, r1
    add_sat r1.zw, r1, -c65.x
    mul r1.zw, r1, c65.y
    max r2.x, r1.z, r1.w
    lrp_pp r3.x, r2.x, c0.w, r1.y
    lrp_pp r3.y, r2.x, c0.w, r1.x
    mul_pp r1.x, r3.x, c77.w
    mov_pp r2.z, v4.w
    mov_pp r2.x, v2.w
    mov_pp r2.y, v3.w
    dp3_pp r1.y, r2, r2
    rsq_pp r1.y, r1.y
    mul_pp r1.yz, r1.y, r2.xxyw
    texld_pp r2, v0, s4
    mul_pp r1.w, r2.x, c0.x
    mad r1.yz, r1, r1.w, v0.xxyw
    texld_pp r2, r1.yzzw, s3
    mul_pp r2.x, r2.w, r2.x
    mad_pp r2.xy, r2, c0.y, c0.z
    nrm_pp r4.xyz, v3
    mul_pp r3.xzw, r2.y, r4.xyyz
    nrm_pp r4.xyz, v2
    mad_pp r3.xzw, r2.x, r4.xyyz, r3
    dp2add_pp r1.w, r2, -r2, c0.w
    rsq_pp r1.w, r1.w
    rcp_pp r1.w, r1.w
    nrm_pp r2.xyz, v4
    mad_pp r2.xyz, r1.w, r2, r3.xzww
    dp3_pp r1.w, r2, -c10
    mul r3.xzw, r1.w, c36.xyyz
    mul_pp r3.xzw, r1.x, r3
    cmp_pp r3.xzw, r1.w, r3, c1.y
    dp3_pp r1.w, r2, -r0.yzww
    mul_pp r4.xyz, c58.w, c58
    mul_pp r4.xyz, r1.w, r4
    cmp_pp r4.xyz, r1.w, r4, c1.y
    mad_pp r3.xzw, r0.x, r4.xyyz, r3
    mad_pp r4.xyz, r2, c1.x, c1.x
    mov r5.xyz, c79
    add r5.xyz, -r5, c80
    mad r5.xyz, r4.y, r5, c79
    mul_pp r6.xyz, r2, r2
    mul r5.xyz, r5, r6.y
    mov r7.xyz, c77
    add r7.xyz, -r7, c78
    mad r4.xyw, r4.x, r7.xyzz, c77.xyzz
    mad_pp r4.xyw, r6.x, r4, r5.xyzz
    mov r5.xyz, c81
    add r5.xyz, -r5, c82
    mad r5.xyz, r4.z, r5, c81
    mad_pp r4.xyz, r6.z, r5, r4.xyww
    mul_pp r5.xyz, r4, c17
    mul r5.xyz, r5, c70.w
    mad r4.xyz, r4, c17, -r5
    mad_pp r4.xyz, r3.y, r4, r5
    add_pp r3.xyz, r3.xzww, r4
    mul_pp r3.xyz, r3, c16
    add_pp r4.xyz, c22, -v1
    dp3_pp r1.w, r4, r4
    rsq_pp r1.w, r1.w
    mad_pp r0.yzw, r4.xxyz, r1.w, -r0
    mad_pp r4.xyz, r4, r1.w, -c10
    nrm_pp r5.xyz, r4
    dp3_sat_pp r1.w, r5, r2
    nrm_pp r4.xyz, r0.yzww
    dp3_sat_pp r0.y, r4, r2
    texld_pp r2, r1.yzzw, s2
    texld_pp r4, r1.yzzw, s0
    mul_pp r0.zw, r2.x, c20.xyyz
    mul_pp r0.zw, r0, c2.xyxy
    max_pp r1.y, r0.z, c0.w
    min r0.z, r1.y, c2.z
    pow r1.y, r0.y, r0.z
    pow r2.x, r1.w, r0.z
    mul_pp r2.yzw, c59.w, c59.xxyz
    mul_pp r2.yzw, r0.w, r2
    mul_pp r0.yzw, r0.w, c37.xxyz
    mul_pp r0.yzw, r2.x, r0
    mul_pp r1.yzw, r1.y, r2
    mul_pp r1.yzw, r0.x, r1
    mad_pp r0.xyz, r0.yzww, r1.x, r1.yzww
    mul_pp r0.xyz, r0, c18
    mul_pp r0.xyz, r0, v7.w
    mad_pp r0.xyz, r3, r4, r0
    mul_pp r0.w, r4.w, c16.w
    mul_pp r0, r0, c89
    min_pp r1, r0, c2.w
    mul_pp r0.xyz, c75, v7.y
    mad_pp oC0.xyz, r1, v7.x, r0
    mov_pp oC0.w, r1.w

// approximately 147 instruction slots used (6 texture, 141 arithmetic)
