//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   row_major float4x4 g_MtxProjection;
//   row_major float4x4 g_MtxView;
//   row_major float4x4 g_MtxWorld;
//
//
// Registers:
//
//   Name            Reg   Size
//   --------------- ----- ----
//   g_MtxProjection c0       4
//   g_MtxView       c4       4
//   g_MtxWorld      c8       3
//

    vs_3_0
    dcl_position v0
    dcl_texcoord v1
    dcl_color v2
    dcl_position o0
    dcl_texcoord o1.xy
    dcl_texcoord2 o2
    dcl_color o3
    mul r0.xyz, c9, v0.y
    mad r0.xyz, v0.x, c8, r0
    mad r0.xyz, v0.z, c10, r0
    mul r1, r0.y, c5
    mad r1, r0.x, c4, r1
    mad r0, r0.z, c6, r1
    add r0, r0, c7
    mul r1, r0.y, c1
    mad r1, r0.x, c0, r1
    mad r1, r0.z, c2, r1
    mad r0, r0.w, c3, r1
    mov o0, r0
    mov o2, r0
    mov o1.xy, v1
    mov o3, v2

// approximately 15 instruction slots used
