//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_MiddleGray_Scale_LuminanceLow_LuminanceHigh;
//   sampler2D sampDif0;
//
//
// Registers:
//
//   Name                                          Reg   Size
//   --------------------------------------------- ----- ----
//   g_MiddleGray_Scale_LuminanceLow_LuminanceHigh c150     1
//   sampDif0                                      s0       1
//

    ps_3_0
    dcl_texcoord v0.xy
    dcl_2d s0
    texld_pp r0, v0, s0
    mul_pp oC0.xyz, r0, c150.y
    mov_pp oC0.w, r0.w

// approximately 3 instruction slots used (1 texture, 2 arithmetic)
