//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   sampler2D g_DepthSampler;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   sampler2D g_FramebufferSampler;
//   float4 g_LightScatteringColor;
//   row_major float4x4 g_MtxInvProjection;
//   float4 g_PowerGlossLevel;
//   sampler2D g_ReflectionMapSampler;
//   float4 g_Specular;
//   float4 g_ViewportSize;
//   float4 g_aLightField[6];
//   float4 mrgGlobalLight_Direction;
//   float4 mrgGlobalLight_Specular;
//   float4 mrgTexcoordIndex[4];
//   sampler2D sampDecal;
//   sampler2D sampNrm1;
//   sampler2D sampNrm2;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   g_MtxInvProjection       c4       4
//   mrgGlobalLight_Direction c10      1
//   g_Diffuse                c16      1
//   g_Ambient                c17      1
//   g_Specular               c18      1
//   g_PowerGlossLevel        c20      1
//   g_EyePosition            c22      1
//   g_EyeDirection           c23      1
//   g_ViewportSize           c24      1
//   mrgTexcoordIndex         c26      1
//   mrgGlobalLight_Specular  c37      1
//   g_LightScatteringColor   c75      1
//   g_aLightField            c77      6
//   g_ForceAlphaColor        c89      1
//   sampDecal                s0       1
//   sampNrm1                 s1       1
//   sampNrm2                 s2       1
//   g_FramebufferSampler     s11      1
//   g_DepthSampler           s12      1
//   g_ReflectionMapSampler   s14      1
//

    ps_3_0
    def c0, 2, -1, 0.5, -2
    def c1, 0.5, -0.5, 500, 5
    def c2, 1024, 0.212500006, 0.715399981, 0.0720999986
    def c3, 0, 1, 2, 3
    def c8, 4, 0, 0, 0
    def c9, 1, 0, -1, 0.0500000007
    dcl_texcoord v0.xyz
    dcl_texcoord1 v1
    dcl_texcoord2 v2.xyz
    dcl_texcoord3 v3.xyz
    dcl_texcoord4 v4.xyz
    dcl_texcoord5 v5
    dcl_texcoord6 v6
    dcl_color_pp v7
    dcl_texcoord7_pp v8.xyw
    dcl vPos.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s11
    dcl_2d s12
    dcl_2d s14
    frc r0.xyz, c26.xzww
    cmp r1.xyz, -r0, c3.x, c3.y
    add r0.xyz, -r0, c26.xzww
    mov r2.x, c3.x
    cmp r1.xyz, c26.xzww, r2.x, r1
    add r0.xyz, r0, r1
    add r1, r0.y, -c3
    cmp r0.yw, -r1_abs.x, v5.xxzy, c3.x
    cmp r0.yw, -r1_abs.y, v5.xzzw, r0
    cmp r0.yw, -r1_abs.z, v6.xxzy, r0
    cmp r1.xy, -r1_abs.w, v6.zwzw, r0.ywzw
    add r1.z, r1.y, v1.x
    texld_pp r1, r1.xzzw, s1
    mul_pp r1.x, r1.w, r1.x
    mad_pp r1.xy, r1, c0.x, c0.y
    dp2add r0.y, r1, -r1, c3.y
    rsq r0.y, r0.y
    rcp_pp r1.z, r0.y
    add r2, r0.z, -c3
    add r0, r0.x, -c3
    cmp r3.xy, -r2_abs.x, v5, c3.x
    cmp r2.xy, -r2_abs.y, v5.zwzw, r3
    cmp r2.xy, -r2_abs.z, v6, r2
    cmp r2.xy, -r2_abs.w, v6.zwzw, r2
    add r2.z, r2.y, v1.y
    texld_pp r2, r2.xzzw, s2
    mul_pp r2.x, r2.w, r2.x
    mad_pp r2.xy, r2, c0.x, c0.y
    dp2add r1.w, r2, -r2, c3.y
    rsq r1.w, r1.w
    rcp_pp r2.z, r1.w
    add_pp r1.xyz, r1, r2
    mul_pp r1.xyz, r1, c0.z
    nrm_pp r2.xyz, r1
    nrm_pp r1.xyz, v4
    mul_pp r1.xyz, r1, r2.y
    nrm_pp r3.xyz, v3
    mad_pp r1.xyz, r2.x, r3, r1
    nrm_pp r3.xyz, v2
    mad_pp r1.xyz, r2.z, r3, r1
    mad_pp r3.xyz, r1, c0.z, c0.z
    mov r4.xyz, c77
    add r4.xyz, -r4, c78
    mad r4.xyz, r3.x, r4, c77
    mul_pp r5.xyz, r1, r1
    mov r6.xyz, c79
    add r6.xyz, -r6, c80
    mad r3.xyw, r3.y, r6.xyzz, c79.xyzz
    mul r3.xyw, r3, r5.y
    mad_pp r3.xyw, r5.x, r4.xyzz, r3
    mov r4.xyz, c81
    add r4.xyz, -r4, c82
    mad r4.xyz, r3.z, r4, c81
    mad_pp r3.xyz, r5.z, r4, r3.xyww
    mul_pp r3.xyz, r3, c17
    dp3 r1.w, r1, c23
    mov_pp r2.zw, c1
    mul_pp r2.zw, r2, c20.xyyz
    max r3.w, r2.z, c3.y
    mul_pp r4.xyz, r2.w, c37
    min r2.z, r3.w, c2.x
    pow r3.w, r1_abs.w, r2.z
    mul r3.xyz, r3, r3.w
    add_pp r5.xyz, c22, -v0
    dp3_pp r1.w, r5, r5
    rsq_pp r1.w, r1.w
    mul_pp r6.xyz, r1.w, r5
    mad_pp r5.xyz, r5, r1.w, -c10
    nrm_pp r7.xyz, r5
    dp3_sat_pp r1.w, r7, r1
    dp3_pp r1.x, r1, r6
    add_pp r1.x, -r1_abs.x, c3.y
    mul_pp r1.x, r1.x, r1.x
    pow r3.w, r1.w, r2.z
    mul_pp r1.yzw, r2.z, c18.xxyz
    mul_pp r4.xyz, r3.w, r4
    mul_pp r1.yzw, r1, r4.xxyz
    mad r2.z, r1.x, -r1.x, c3.y
    mul_pp r1.x, r1.x, r1.x
    mul r3.xyz, r2.z, r3
    mad_pp r1.yzw, r1, c77.w, r3.xxyz
    dp3_sat r2.z, r1.yzww, c2.yzww
    add r2.z, -r2.z, c3.y
    cmp r3.xy, -r0_abs.x, v5, c3.x
    cmp r0.xy, -r0_abs.y, v5.zwzw, r3
    cmp r0.xy, -r0_abs.z, v6, r0
    cmp r0.xy, -r0_abs.w, v6.zwzw, r0
    add r0.z, r0.y, v1.x
    texld_pp r0, r0.xzzw, s0
    mul_pp r0, r0, v7
    mul r3.xy, c24.zwzw, vPos
    mov r4.xyz, c9
    mad r4, c24.zzww, r4.xyyz, r4.yxzy
    mad r3.xy, r3, c0.xwzw, r4
    add r3.xy, r4.zwzw, r3
    mad r3.zw, r2.xyxy, c9.w, r3.xyxy
    mad r2.xy, r2, -c9.w, r3
    mad r2.xy, r2, c0.z, c0.z
    texld_pp r4, r2, s14
    mul_pp r2.xyw, r1.x, r4.xyzz
    mad r3.zw, r3, c1.xyxy, c1.x
    texld r4, r3.zwzw, s12
    texld_pp r5, r3.zwzw, s11
    rcp r1.x, v1.w
    mad r1.x, v1.z, -r1.x, r4.x
    mad r3.zw, r3.xyxy, c1.xyxy, c1.x
    texld_pp r4, r3.zwzw, s11
    texld r6, r3.zwzw, s12
    cmp_pp r4.xyz, r1.x, r5, r4
    mad_pp r0.xyz, r4, r0, r1.yzww
    mul_pp r0.w, r0.w, c16.w
    mad_pp r1.xyz, r2.xyww, r2.z, r0
    mul r0.xy, r3.y, c5.zwzw
    mad r0.xy, r3.x, c4.zwzw, r0
    mad r0.xy, r6.x, c6.zwzw, r0
    add r0.xy, r0, c7.zwzw
    rcp r0.y, r0.y
    mad_sat_pp r0.x, r0.x, -r0.y, v8.w
    mul_pp r1.w, r0.x, r0.w
    mul_pp r0, r1, c89
    min_pp r1, r0, c8.x
    mul_pp r0.xyz, c75, v8.y
    mad_pp oC0.xyz, r1, v8.x, r0
    mov_pp oC0.w, r1.w

// approximately 140 instruction slots used (8 texture, 132 arithmetic)
