//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   sampler2D g_DepthSampler;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   sampler2D g_FramebufferSampler;
//   float4 g_LightScatteringColor;
//   float4 g_OffsetParam;
//   float4 g_PowerGlossLevel;
//   float4 g_Specular;
//   float4 g_TimeParam;
//   float4 g_ViewportSize;
//   float4 g_aLightField[6];
//   float4 mrgGlobalLight_Direction;
//   float4 mrgGlobalLight_Specular;
//   float4 mrgTexcoordIndex[4];
//   sampler2D sampDecal;
//   sampler2D sampEnv;
//   sampler2D sampNrm1;
//   sampler2D sampNrm2;
//   sampler2D sampOffset;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   mrgGlobalLight_Direction c10      1
//   g_Diffuse                c16      1
//   g_Ambient                c17      1
//   g_Specular               c18      1
//   g_PowerGlossLevel        c20      1
//   g_EyePosition            c22      1
//   g_EyeDirection           c23      1
//   g_ViewportSize           c24      1
//   mrgTexcoordIndex         c26      2
//   mrgGlobalLight_Specular  c37      1
//   g_TimeParam              c68      1
//   g_LightScatteringColor   c75      1
//   g_aLightField            c77      6
//   g_ForceAlphaColor        c89      1
//   g_OffsetParam            c151     1
//   sampDecal                s0       1
//   sampNrm1                 s1       1
//   sampNrm2                 s2       1
//   sampEnv                  s3       1
//   sampOffset               s4       1
//   g_FramebufferSampler     s11      1
//   g_DepthSampler           s12      1
//

    ps_3_0
    def c0, 0.0799999982, 2, -1, 0.5
    def c1, 2, -2, 0.5, -0.5
    def c2, 500, 5, 1024, 0.25
    def c3, 0.212500006, 0.715399981, 0.0720999986, 4
    def c4, 1, 0, -1, 0.0500000007
    def c5, 0, 1, 2, 3
    def c6, -1, 1, 0, 0.5
    dcl_texcoord v0.xyz
    dcl_texcoord1 v1
    dcl_texcoord2 v2.xyz
    dcl_texcoord3 v3.xyz
    dcl_texcoord4 v4.xyz
    dcl_texcoord5 v5
    dcl_texcoord6 v6
    dcl_color_pp v7
    dcl_texcoord7_pp v8.xy
    dcl vPos.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    dcl_2d s11
    dcl_2d s12
    frc r0.x, c27.y
    cmp r0.y, -r0.x, c5.x, c5.y
    add r0.x, -r0.x, c27.y
    mov r1.x, c5.x
    cmp r0.y, c27.y, r1.x, r0.y
    add r0.x, r0.y, r0.x
    add r0, r0.x, -c5
    cmp r1.yz, -r0_abs.x, v5.xxyw, c5.x
    cmp r0.xy, -r0_abs.y, v5.zwzw, r1.yzzw
    cmp r0.xy, -r0_abs.z, v6, r0
    cmp r0.xy, -r0_abs.w, v6.zwzw, r0
    mov r0.zw, c151
    mul r0.zw, r0, c68.y
    mad r0.xy, r0.zwzw, c0.x, r0
    texld_pp r0, r0, s4
    mad r0.xy, r0.wxzw, c0.y, c0.z
    frc r1.yzw, c26.xxzw
    cmp r2.xyz, -r1.yzww, c5.x, c5.y
    add r1.yzw, -r1, c26.xxzw
    cmp r2.xyz, c26.xzww, r1.x, r2
    add r1.xyz, r1.yzww, r2
    add r2, r1.y, -c5
    cmp r0.zw, -r2_abs.x, v5.xyxy, c5.x
    cmp r0.zw, -r2_abs.y, v5, r0
    cmp r0.zw, -r2_abs.z, v6.xyxy, r0
    cmp r2.xy, -r2_abs.w, v6.zwzw, r0.zwzw
    add r2.z, r2.y, v1.x
    mad r0.zw, r0.xyxy, c151.xyxy, r2.xyxz
    texld_pp r2, r0.zwzw, s1
    mul_pp r2.x, r2.w, r2.x
    mad_pp r2.xy, r2, c0.y, c0.z
    dp2add r0.z, r2, -r2, c5.y
    rsq r0.z, r0.z
    rcp_pp r2.z, r0.z
    add r3, r1.z, -c5
    add r1, r1.x, -c5
    cmp r0.zw, -r3_abs.x, v5.xyxy, c5.x
    cmp r0.zw, -r3_abs.y, v5, r0
    cmp r0.zw, -r3_abs.z, v6.xyxy, r0
    cmp r3.xy, -r3_abs.w, v6.zwzw, r0.zwzw
    add r3.z, r3.y, v1.y
    mad r0.zw, r0.xyxy, c151.xyxy, r3.xyxz
    texld_pp r3, r0.zwzw, s2
    mul_pp r3.x, r3.w, r3.x
    mad_pp r3.xy, r3, c0.y, c0.z
    dp2add r0.z, r3, -r3, c5.y
    rsq r0.z, r0.z
    rcp_pp r3.z, r0.z
    add_pp r2.xyz, r2, r3
    mul_pp r2.xyz, r2, c0.w
    nrm_pp r3.xyz, r2
    mul r0.zw, c24, vPos.xyxy
    mov r2.xyz, c4
    mad r2, c24.zzww, r2.xyyz, r2.yxzy
    mad r0.zw, r0, c1.xyxy, r2.xyxy
    add r0.zw, r2, r0
    mad r2.xy, r3, c4.w, r0.zwzw
    mad r0.zw, r0, c1, c1.z
    texld_pp r4, r0.zwzw, s11
    mad r0.zw, r2.xyxy, c1, c1.z
    texld r2, r0.zwzw, s12
    texld_pp r5, r0.zwzw, s11
    rcp r0.z, v1.w
    mad r0.z, v1.z, -r0.z, r2.x
    cmp_pp r2.xyz, r0.z, r5, r4
    nrm_pp r4.xyz, v4
    mul_pp r4.xyz, r3.y, r4
    nrm_pp r5.xyz, v3
    mad_pp r3.xyw, r3.x, r5.xyzz, r4.xyzz
    nrm_pp r4.xyz, v2
    mad_pp r3.xyz, r3.z, r4, r3.xyww
    add_pp r4, c22.xyzx, -v0.xyzx
    dp3_pp r0.z, r4.yzww, r4.yzww
    rsq_pp r0.z, r0.z
    mad_pp r5.xyz, r4, r0.z, -c10
    mul_pp r4, r0.z, r4
    nrm_pp r6.xyz, r5
    dp3_sat_pp r0.z, r6, r3
    mov_pp r5.xy, c2
    mul_pp r5.xy, r5, c20.yzzw
    max r0.w, r5.x, c5.y
    mul_pp r5.xyz, r5.y, c37
    min r2.w, r0.w, c2.z
    pow r3.w, r0.z, r2.w
    mul_pp r5.xyz, r3.w, r5
    mul_pp r6.xyz, r2.w, c18
    mul_pp r5.xyz, r5, r6
    mad_pp r6.xyz, r3, c0.w, c0.w
    mov r7.xyz, c79
    add r7.xyz, -r7, c80
    mad r7.xyz, r6.y, r7, c79
    mul_pp r8.xyz, r3, r3
    mul r7.xyz, r7, r8.y
    mov r9.xyz, c77
    add r9.xyz, -r9, c78
    mad r6.xyw, r6.x, r9.xyzz, c77.xyzz
    mad_pp r6.xyw, r8.x, r6, r7.xyzz
    mov r7.xyz, c81
    add r7.xyz, -r7, c82
    mad r7.xyz, r6.z, r7, c81
    mad_pp r6.xyz, r8.z, r7, r6.xyww
    mul_pp r6.xyz, r6, c17
    dp3 r0.z, r3, c23
    pow r3.w, r0_abs.z, r2.w
    mul r6.xyz, r6, r3.w
    dp3_pp r0.z, r4.wyzw, r3
    add_pp r0.w, -r0_abs.z, c5.y
    add_pp r0.z, r0.z, r0.z
    mad r3, r0.z, r3.xyzx, -r4
    mul_pp r0.z, r0.w, r0.w
    mad r0.w, r0.z, -r0.z, c5.y
    mul_pp r0.z, r0.z, r0.z
    mul r4.xyz, r0.w, r6
    mad_pp r4.xyz, r5, c77.w, r4
    cmp r5.xy, -r1_abs.x, v5, c5.x
    cmp r1.xy, -r1_abs.y, v5.zwzw, r5
    cmp r1.xy, -r1_abs.z, v6, r1
    cmp r1.xy, -r1_abs.w, v6.zwzw, r1
    add r1.z, r1.y, v1.x
    mad r0.xy, r0, c151, r1.xzzw
    texld_pp r1, r0, s0
    mul_pp r1, r1, v7
    mad_pp r0.xyw, r2.xyzz, r1.xyzz, r4.xyzz
    dp3_sat r1.x, r4, c3
    add r1.x, -r1.x, c5.y
    mul_pp r2.w, r1.w, c16.w
    mad r4, r3.wyzw, c6.xxyz, c6.zzzw
    mul r5, r3, c4.xzzy
    cmp_pp r3, r3.z, r4, r5
    add_pp r1.y, r3.z, c5.y
    rcp r1.y, r1.y
    mad_pp r1.yz, r3.xyxw, r1.y, c5.y
    mad_pp r3.x, r1.z, c2.w, r3.w
    mul_pp r3.y, r1.y, c0.w
    texld_pp r3, r3, s3
    mul_pp r1.yzw, r0.z, r3.xxyz
    mad_pp r2.xyz, r1.yzww, r1.x, r0.xyww
    mul_pp r0, r2, c89
    min_pp r1, r0, c3.w
    mul_pp r0.xyz, c75, v8.y
    mad_pp oC0.xyz, r1, v8.x, r0
    mov_pp oC0.w, r1.w

// approximately 158 instruction slots used (8 texture, 150 arithmetic)
