//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
// Parameters:
//
//   float4 g_Ambient;
//   sampler2D g_DepthSampler;
//   float4 g_Diffuse;
//   float4 g_EyeDirection;
//   float4 g_EyePosition;
//   float4 g_ForceAlphaColor;
//   sampler2D g_FramebufferSampler;
//   float4 g_GI0Scale;
//   float4 g_GI1Scale;
//   sampler2D g_GISampler;
//   float4 g_LightScatteringColor;
//   float4 g_PowerGlossLevel;
//   sampler2D g_ReflectionMapSampler;
//   float4 g_Specular;
//   float4 g_ViewportSize;
//   float4 mrgGlobalLight_Direction;
//   float4 mrgGlobalLight_Specular;
//   float4 mrgTexcoordIndex[4];
//   sampler2D sampDecal;
//   sampler2D sampNrm1;
//   sampler2D sampNrm2;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   mrgGlobalLight_Direction c10      1
//   g_Diffuse                c16      1
//   g_Ambient                c17      1
//   g_Specular               c18      1
//   g_PowerGlossLevel        c20      1
//   g_EyePosition            c22      1
//   g_EyeDirection           c23      1
//   g_ViewportSize           c24      1
//   mrgTexcoordIndex         c26      1
//   mrgGlobalLight_Specular  c37      1
//   g_GI0Scale               c70      1
//   g_GI1Scale               c71      1
//   g_LightScatteringColor   c75      1
//   g_ForceAlphaColor        c89      1
//   sampDecal                s0       1
//   sampNrm1                 s1       1
//   sampNrm2                 s2       1
//   g_GISampler              s10      1
//   g_FramebufferSampler     s11      1
//   g_DepthSampler           s12      1
//   g_ReflectionMapSampler   s14      1
//

    ps_3_0
    def c0, 2, -1, 0.5, -2
    def c1, 0.298900008, 0.586600006, 0.114399999, 0.0500000007
    def c2, 0.5, -0.5, 500, 5
    def c3, 1, 0, -1, 1024
    def c4, 0.212500006, 0.715399981, 0.0720999986, 4
    def c5, 0, 1, 2, 3
    dcl_texcoord v0.xyz
    dcl_texcoord1 v1
    dcl_texcoord2 v2.xyz
    dcl_texcoord3 v3.xyz
    dcl_texcoord4 v4.xyz
    dcl_texcoord5 v5
    dcl_texcoord6 v6
    dcl_color_pp v7
    dcl_texcoord7_pp v8.xy
    dcl vPos.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s10
    dcl_2d s11
    dcl_2d s12
    dcl_2d s14
    frc r0.xyz, c26.xzww
    cmp r1.xyz, -r0, c5.x, c5.y
    add r0.xyz, -r0, c26.xzww
    mov r2.x, c5.x
    cmp r1.xyz, c26.xzww, r2.x, r1
    add r0.xyz, r0, r1
    add r1, r0.y, -c5
    cmp r0.yw, -r1_abs.x, v5.xxzy, c5.x
    cmp r0.yw, -r1_abs.y, v5.xzzw, r0
    cmp r0.yw, -r1_abs.z, v6.xxzy, r0
    cmp r1.xy, -r1_abs.w, v6.zwzw, r0.ywzw
    add r1.z, r1.y, v1.x
    texld_pp r1, r1.xzzw, s1
    mul_pp r1.x, r1.w, r1.x
    mad_pp r1.xy, r1, c0.x, c0.y
    dp2add r0.y, r1, -r1, c5.y
    rsq r0.y, r0.y
    rcp_pp r1.z, r0.y
    add r2, r0.z, -c5
    add r0, r0.x, -c5
    cmp r3.xy, -r2_abs.x, v5, c5.x
    cmp r2.xy, -r2_abs.y, v5.zwzw, r3
    cmp r2.xy, -r2_abs.z, v6, r2
    cmp r2.xy, -r2_abs.w, v6.zwzw, r2
    add r2.z, r2.y, v1.y
    texld_pp r2, r2.xzzw, s2
    mul_pp r2.x, r2.w, r2.x
    mad_pp r2.xy, r2, c0.x, c0.y
    dp2add r1.w, r2, -r2, c5.y
    rsq r1.w, r1.w
    rcp_pp r2.z, r1.w
    add_pp r1.xyz, r1, r2
    mul_pp r1.xyz, r1, c0.z
    nrm_pp r2.xyz, r1
    nrm_pp r1.xyz, v4
    mul_pp r1.xyz, r1, r2.y
    nrm_pp r3.xyz, v3
    mad_pp r1.xyz, r2.x, r3, r1
    nrm_pp r3.xyz, v2
    mad_pp r1.xyz, r2.z, r3, r1
    add_pp r3.xyz, c22, -v0
    dp3_pp r1.w, r3, r3
    rsq_pp r1.w, r1.w
    mad_pp r4.xyz, r3, r1.w, -c10
    mul_pp r3.xyz, r1.w, r3
    dp3_pp r1.w, r1, r3
    add_pp r1.w, -r1_abs.w, c5.y
    mul_pp r1.w, r1.w, r1.w
    nrm_pp r3.xyz, r4
    dp3_sat_pp r2.z, r3, r1
    dp3 r1.x, r1, c23
    mov_pp r3.zw, c2
    mul_pp r1.yz, r3.xzww, c20
    max r2.w, r1.y, c5.y
    mul_pp r3.xyz, r1.z, c37
    min r1.y, r2.w, c3.w
    pow r3.w, r2.z, r1.y
    mul_pp r3.xyz, r3.w, r3
    mul_pp r4.xyz, r1.y, c18
    pow r2.z, r1_abs.x, r1.y
    mul_pp r1.xyz, r3, r4
    texld_pp r3, v5.zwzw, s10
    mul_pp r4.xyz, r3, r3
    dp3_pp r2.w, r4, c1
    mad_pp r3.xyz, r3, r3, -r2.w
    mad_sat_pp r3.xyz, r3, c71.w, r2.w
    mul_pp r3.xyz, r3, c70
    mul_pp r3.xyz, r3, c17
    mul r3.xyz, r2.z, r3
    mad r2.z, r1.w, -r1.w, c5.y
    mul_pp r1.w, r1.w, r1.w
    mul r3.xyz, r2.z, r3
    mad_pp r1.xyz, r1, r3.w, r3
    cmp r2.zw, -r0_abs.x, v5.xyxy, c5.x
    cmp r0.xy, -r0_abs.y, v5.zwzw, r2.zwzw
    cmp r0.xy, -r0_abs.z, v6, r0
    cmp r0.xy, -r0_abs.w, v6.zwzw, r0
    add r0.z, r0.y, v1.x
    texld_pp r0, r0.xzzw, s0
    mul r2.zw, c24, vPos.xyxy
    mov r3.xyz, c3
    mad r3, c24.zzww, r3.xyyz, r3.yxzy
    mad r2.zw, r2, c0.xyxw, r3.xyxy
    add r2.zw, r3, r2
    mad r3.xy, r2, c1.w, r2.zwzw
    mad r2.xy, r2, -c1.w, r2.zwzw
    mad r2.zw, r2, c2.xyxy, c2.x
    texld_pp r4, r2.zwzw, s11
    mad r2.xy, r2, c0.z, c0.z
    texld_pp r2, r2, s14
    mul_pp r2.xyz, r1.w, r2
    mad r3.xy, r3, c2, c2.x
    texld r5, r3, s12
    texld_pp r3, r3, s11
    rcp r1.w, v1.w
    mad r1.w, v1.z, -r1.w, r5.x
    cmp_pp r3.xyz, r1.w, r3, r4
    mad_pp r0.xyz, r0, v7, r3
    mul_pp r0.w, r0.w, v7.w
    mul_pp r3.w, r0.w, c16.w
    add_pp r0.xyz, r1, r0
    dp3_sat r0.w, r1, c4
    add r0.w, -r0.w, c5.y
    mad_pp r3.xyz, r2, r0.w, r0
    mul_pp r0, r3, c89
    min_pp r1, r0, c4.w
    mul_pp r0.xyz, c75, v8.y
    mad_pp oC0.xyz, r1, v8.x, r0
    mov_pp oC0.w, r1.w

// approximately 125 instruction slots used (8 texture, 117 arithmetic)
