/* This file was generated by syncqt. */
#ifndef QT_ENGINIO_VERSION_H
#define QT_ENGINIO_VERSION_H

#define ENGINIO_VERSION_STR "1.2.0"

#define ENGINIO_VERSION 0x010200

#endif // QT_ENGINIO_VERSION_H
