#include "stdafx.h"
#include "moc_EditorTerrainStreamer.cpp"
#include "moc_EditorViewport.cpp"
#include "moc_EditorViewportsWidget.cpp"
#include "moc_EditorWindow.cpp"
#include "moc_OgreViewportWidget.cpp"
#include "qrc_EditorResource.cpp"